import { useState, type FormEvent, type ReactNode } from "react";
import { Activity, ArrowRight, BookOpen, BrainCircuit, Check, CircleUserRound, Database, FileHeart, Globe2, HeartHandshake, Hospital, Laptop, ReceiptText, Stethoscope, Workflow } from "lucide-react";
import { Link } from "react-router-dom";
import { cn } from "@/lib/cn";
import { Status } from "@/public/components";
import { DOCTOR_SIGN_IN_URL, TELEMEDICINE_SIGN_IN_URL } from "@/public/ecosystemLinks";
import { CONTACT_LINES, whatsappUrl } from "@/public/contact";
import { Action, ContactLines, CtaBand, INK, MUTED, PageHero, Reveal, SectionTitle } from "@/public/ui";

// Inner company pages. Product, solutions, pricing and security pages live in ProductPages.tsx;
// all of them share the hero, headings and closing band from @/public/ui so the site reads as one.

function EndCta({ title }: { title: string }) {
  return <CtaBand eyebrow="Next step" title={title} actions={<><Action variant="light" to="/register/organization">Register your facility</Action><Action variant="ghost" to="/book-demo">Book a demo</Action></>} />;
}

export function AIPage() {
  const areas = [[Stethoscope, "Clinical assistance", "Structured clinical summaries, documentation support and relevant-history surfacing.", "Controlled pilot"], [Hospital, "Hospital intelligence", "Operational trends, abnormal-activity signals and capacity insights.", "Pilot"], [Workflow, "Administrative automation", "Reports, workflow monitoring and task prioritization.", "Early access"], [Database, "Data intelligence", "Completeness checks, intelligent search and analytics.", "Early access"]] as const;
  return <div className={INK}><PageHero eyebrow="Sabi Intelligence" title="AI assistance designed around accountable healthcare." copy="Sabi Intelligence supports professionals with structure, context and workflow signals. It does not replace professional judgment or autonomously diagnose patients." actions={<Action to="/book-demo">Discuss an AI pilot</Action>}
    aside={<div className="mx-auto max-w-[460px] rounded-[28px] border border-violet-200 bg-white p-7 shadow-[0_30px_60px_-36px_rgba(11,43,32,.45)]"><BrainCircuit size={32} className="text-violet-600" /><p className="mt-6 text-xs font-bold uppercase tracking-widest text-violet-700">A governed assistance layer</p><div className="mt-4 space-y-3">{["Human review", "Role-aware context", "Traceable workflows", "Controlled rollout"].map((x) => <div className="flex items-center gap-3 rounded-xl bg-violet-50 p-3 text-sm font-semibold" key={x}><Check size={15} className="text-brand-600" />{x}</div>)}</div></div>} />
    <section className="bg-white px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto max-w-[1200px]"><SectionTitle eyebrow="Current direction" title="Practical intelligence, clearly labelled." copy="The experiences below describe controlled implementation and roadmap areas, not autonomous clinical functionality." className="mb-10" /><div className="grid gap-4 md:grid-cols-2">{areas.map(([Icon, title, copy, status], i) => <Reveal key={title} delay={i * .04}><article className="h-full rounded-[24px] border border-[#e3ebe5] bg-[#fcfefc] p-7"><div className="flex items-start justify-between gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-50 text-violet-700"><Icon /></span><Status tone="pilot">{status}</Status></div><h2 className="mt-6 font-display text-xl font-bold">{title}</h2><p className={cn("mt-3 text-sm leading-6", MUTED)}>{copy}</p></article></Reveal>)}</div><div className="mt-10 rounded-2xl border border-brand-200 bg-brand-50 p-6"><b className="font-display text-brand-900">Responsible use principle</b><p className="mt-2 text-sm leading-6 text-brand-900/70">AI supports healthcare professionals. Clinical decisions remain with qualified healthcare professionals. Outputs should be reviewed in context, with appropriate access, audit and safety controls.</p></div></div></section>
    <EndCta title="Explore a supervised AI pilot with your team." />
  </div>;
}

export function AboutPage() {
  const team = [["SD", "Sanusi Damilare", "Founder"], ["DA", "Dapo Adediran", "Co-Founder"], ["RO", "Rufia Opeyemoi", "Co-Founder"], ["WB", "Williams Bashir", "Co-Founder"]];
  return <div className={INK}><PageHero eyebrow="About Sabi Health" title="Building healthcare infrastructure for the next generation." copy="Healthcare systems across Africa are often fragmented. Sabi Health is working toward secure, structured and connected information that helps facilities, professionals and patients coordinate care." actions={<Action to="/book-demo">Talk with us</Action>}
    aside={<div className="mx-auto max-w-[460px] rounded-[28px] bg-[#0b2b20] p-8 text-white shadow-[0_30px_60px_-30px_rgba(11,43,32,.7)]"><HeartHandshake size={38} className="text-brand-300" /><p className="mt-8 text-xs font-bold uppercase tracking-widest text-brand-200">Long-term vision</p><h2 className="mt-3 font-display text-3xl font-bold">One patient.<br />One connected health journey.</h2></div>} />
    <section className="bg-white px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto grid max-w-[1200px] gap-12 lg:grid-cols-2"><SectionTitle eyebrow="The problem" title="Fragmentation makes everyone carry more." copy="Patient information may live in paper files and disconnected systems. Departments may operate independently. Clinicians may lack longitudinal context, while administrators struggle to see the whole organization." /><Reveal><div className="rounded-[28px] border border-[#e3ebe5] bg-[#fcfefc] p-8"><h2 className="font-display text-2xl font-bold">Our mission</h2><p className={cn("mt-5 text-base leading-8", MUTED)}>Help healthcare organizations deliver more connected, efficient and data-driven healthcare while giving patients greater continuity across their healthcare journey.</p><div className="mt-7 rounded-2xl bg-brand-50 p-5 text-sm leading-6 text-brand-900">A healthcare ecosystem where authorized professionals can access the right information at the right time, and patients do not repeatedly rebuild their medical story.</div></div></Reveal></div></section>
    <section id="team" className="bg-[#f6f9f5] px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto max-w-[1200px]"><SectionTitle eyebrow="Founding team" title="A team focused on the mission." copy="We use initials until approved founder photographs are available." className="mb-10" /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{team.map(([initials, name, role], i) => <Reveal key={name} delay={i * .05}><article className="rounded-2xl border border-[#e3ebe5] bg-white p-6"><div className="grid h-20 w-20 place-items-center rounded-2xl bg-[#0b2b20] font-display text-xl font-bold text-brand-300">{initials}</div><h2 className="mt-6 font-display text-lg font-bold">{name}</h2><p className={cn("mt-1 text-sm", MUTED)}>{role}</p></article></Reveal>)}</div></div></section>
    <EndCta title="Build the connected healthcare future with us." />
  </div>;
}

export function ResourcesPage() {
  const resources = [[BookOpen, "Documentation", "Approved product documentation will be published here."], [Laptop, "Help Centre", "Guided help and support articles are being prepared."], [Activity, "System Status", "A public status page is planned."], [FileHeart, "Privacy", "Our privacy notice is pending formal approval."], [ReceiptText, "Terms", "Terms of use are pending formal approval."], [Globe2, "Careers", "Open roles will be listed here."]] as const;
  return <div className={INK}><PageHero eyebrow="Resources" title="Product guidance and company resources." copy="Legal and policy pages are marked as pending until they're formally approved — we won't publish placeholder legal text. For anything urgent, call or WhatsApp us." actions={<Action href={whatsappUrl(CONTACT_LINES[0])}>Ask us on WhatsApp</Action>} />
    <section className="bg-white px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto grid max-w-[1200px] gap-4 md:grid-cols-2 lg:grid-cols-3">{resources.map(([Icon, title, copy], i) => <Reveal key={title} delay={i * .04}><article id={title.toLowerCase().replaceAll(" ", "-")} className="h-full scroll-mt-24 rounded-2xl border border-[#e3ebe5] bg-[#fcfefc] p-6"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-50 text-brand-700"><Icon size={20} /></span><Status tone="soon">Coming soon</Status></div><h2 className="mt-5 font-display text-xl font-bold">{title}</h2><p className={cn("mt-3 text-sm leading-6", MUTED)}>{copy}</p></article></Reveal>)}</div></section>
  </div>;
}

export function RegisterEntryPage() {
  return <div className={INK}><PageHero eyebrow="Get started" title="How would you like to use Sabi?" copy="Choose the path that matches who you are. Facility onboarding and patient accounts are kept separate." />
    <section className="bg-white px-5 py-16 sm:px-8 lg:px-10 lg:py-20"><div className="mx-auto grid max-w-[1100px] gap-5 md:grid-cols-3">
      <EntryCard icon={<Hospital />} title="Hospital or clinic" copy="Run your facility on Sabi EMR: registration, consultation, laboratory, pharmacy, wards and billing." status="Sabi EMR" action="Register your facility" to="/register/organization" />
      <EntryCard icon={<Stethoscope />} title="Doctor or professional" copy="See patients on Sabi Health once your licence and credentials are reviewed." status="Verified access" action="Open the professional portal" href={DOCTOR_SIGN_IN_URL} />
      <EntryCard icon={<CircleUserRound />} title="Patient" copy="Book video and in-person visits, manage prescriptions and care for your family." status="Free account" action="Open Sabi Health" href={TELEMEDICINE_SIGN_IN_URL} />
    </div><p className={cn("mx-auto mt-8 max-w-2xl text-center text-sm leading-6", MUTED)}>Facility applications are saved as you go and stay separate from live workspaces until verification and approval are complete.</p></section>
  </div>;
}

export function BookDemoPage() {
  const [submissionError, setSubmissionError] = useState("");
  const [facilityType, setFacilityType] = useState("Hospital");
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmissionError("Online demo requests aren't connected yet, so nothing was sent."); window.scrollTo({ top: 0, behavior: "smooth" }); }
  if (submissionError) return <section className={cn("grid min-h-[70vh] place-items-center bg-[#f6f9f5] px-5 py-20", INK)}><div className="max-w-xl rounded-[28px] border border-[#f3e3c8] bg-white p-9 text-center shadow-xl"><h1 className="font-display text-3xl font-bold">Request not sent</h1><p className={cn("mt-4 text-sm leading-6", MUTED)}>{submissionError} Please call or WhatsApp us instead — we'll set up your demo directly.</p><div className="mx-auto mt-6 w-fit text-left"><ContactLines /></div><div className="mt-7"><Action to="/book-demo" variant="secondary">Back to the form</Action></div></div></section>;
  return <div className={INK}><PageHero eyebrow="Book a demo" title="See how Sabi could fit your organization." copy="Tell us about your facility and priorities, or skip the form and call or WhatsApp us directly." aside={<div className="mx-auto max-w-[420px] rounded-[26px] border border-[#e3ebe5] bg-white p-7 shadow-[0_30px_60px_-36px_rgba(11,43,32,.45)]"><p className="text-xs font-bold uppercase tracking-[0.16em] text-brand-700">Fastest way to reach us</p><p className={cn("mb-5 mt-1 text-sm", MUTED)}>Speak with the Sabi team now.</p><ContactLines /></div>} />
    <section className="bg-white px-5 py-16 sm:px-8 lg:px-10 lg:py-20"><form onSubmit={submit} className="mx-auto max-w-4xl rounded-[28px] border border-[#e3ebe5] bg-[#fcfefc] p-6 shadow-[0_30px_60px_-40px_rgba(11,43,32,.4)] sm:p-9"><div className="grid gap-5 sm:grid-cols-2"><DemoField label="Name"><input required name="name" autoComplete="name" className="input" /></DemoField><DemoField label="Work email"><input required type="email" name="email" autoComplete="email" className="input" /></DemoField><DemoField label="Phone"><input required type="tel" name="phone" autoComplete="tel" className="input" placeholder="+234…" /></DemoField><DemoField label="Organization"><input required name="organization" autoComplete="organization" className="input" /></DemoField><DemoField label="Role"><input required name="role" className="input" /></DemoField><DemoField label="Facility type"><select required name="facilityType" className="input" value={facilityType} onChange={(e) => setFacilityType(e.target.value)}>{["Hospital", "Clinic", "Laboratory", "Diagnostic Centre", "Maternity Centre", "Hospital Group", "Other Healthcare Facility"].map((x) => <option key={x}>{x}</option>)}</select></DemoField><DemoField label="Approximate staff"><input required type="number" min="1" name="staff" className="input" /></DemoField><DemoField label="Number of locations"><input required type="number" min="1" name="locations" className="input" /></DemoField><DemoField label="Current system"><input name="currentSystem" className="input" placeholder="Paper, spreadsheets, another EMR…" /></DemoField><DemoField label="Desired timeline"><select name="timeline" className="input"><option>Exploring options</option><option>Within 3 months</option><option>Within 6 months</option><option>Within 12 months</option></select></DemoField><div className="sm:col-span-2"><DemoField label="Main challenge"><textarea required name="challenge" className="input min-h-28 resize-y" /></DemoField></div></div><div className="mt-7 flex flex-col items-start justify-between gap-4 border-t border-[#e3ebe5] pt-6 sm:flex-row sm:items-center"><p className="max-w-lg text-xs leading-5 text-[#7a8a82]">Do not include patient, clinical or regulatory document information in this form.</p><button className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#0b2b20] px-5 text-sm font-bold text-white transition hover:bg-brand-800" type="submit">Request demo <ArrowRight size={16} /></button></div></form></section>
  </div>;
}

function DemoField({ label, children }: { label: string; children: ReactNode }) { return <label className="block"><span className="label">{label}</span>{children}</label>; }

function EntryCard({ icon, title, copy, status, action, to, href }: { icon: ReactNode; title: string; copy: string; status: string; action: string; to?: string; href?: string }) {
  const cls = "mt-7 inline-flex items-center gap-2 text-sm font-bold text-brand-700 hover:text-brand-900";
  return <Reveal className="h-full"><article className="flex h-full flex-col rounded-[24px] border border-[#e3ebe5] bg-[#fcfefc] p-6"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-brand-50 text-brand-700">{icon}</span><Status>{status}</Status></div><h2 className="mt-5 font-display text-xl font-bold">{title}</h2><p className={cn("mt-3 flex-1 text-sm leading-6", MUTED)}>{copy}</p>{to ? <Link to={to} className={cls}>{action}<ArrowRight size={15} /></Link> : <a href={href} className={cls}>{action}<ArrowRight size={15} /></a>}</article></Reveal>;
}
