import { useState, type FormEvent, type ReactNode } from "react";
import { Link, useParams } from "react-router-dom";
import { Activity, ArrowRight, BadgeCheck, BookOpen, BrainCircuit, Building2, Check, CircleUserRound, Database, FileCheck2, FileHeart, Fingerprint, Globe2, HeartHandshake, Hospital, Laptop, LockKeyhole, Network, PackageCheck, ReceiptText, ShieldCheck, Stethoscope, Workflow } from "lucide-react";
import { PRODUCTS, modulesByProduct, type ProductKey } from "@/platform/entitlements";
import { useCommandCenter } from "@/command-center/useCommandCenter";
import { CheckList, Eyebrow, JourneyMap, ProductWindow, PublicCta, SectionHeading, Status } from "@/public/components";
import { categoryCards } from "@/public/content";
import { TELEMEDICINE_SIGN_IN_URL } from "@/public/ecosystemLinks";
import { apiConfigured } from "@/config/runtime";
import { useLivePackages } from "@/registration/useLivePackages";

function PageHero({ eyebrow, title, copy, actions, aside }: { eyebrow: string; title: string; copy: string; actions?: ReactNode; aside?: ReactNode }) {
  return <section className="relative overflow-hidden bg-[#071e16] px-5 py-20 text-white lg:px-8 lg:py-28"><div className="public-grid absolute inset-0 opacity-25" /><div className="relative mx-auto grid max-w-[1350px] gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><Eyebrow>{eyebrow}</Eyebrow><h1 className="text-balance font-display text-4xl font-extrabold leading-[1.02] tracking-[-.05em] sm:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-emerald-50/65">{copy}</p>{actions && <div className="mt-9 flex flex-wrap gap-3">{actions}</div>}</div>{aside && <div>{aside}</div>}</div></section>;
}

export function SabiOsPage() {
  const [product, setProduct] = useState<ProductKey>("emr");
  const productDef = PRODUCTS[product];
  return <><PageHero eyebrow="Sabi OS" title="One operating system for the whole healthcare organization." copy="Sabi OS connects clinical care, operations, people and finance through one modular, tenant-aware platform." actions={<><PublicCta to="/register">Get Started</PublicCta><PublicCta to="/book-demo" secondary>Book a Demo</PublicCta></>} aside={<ProductWindow />} />
    <section className="px-5 py-24 lg:px-8"><div className="mx-auto max-w-[1350px]"><div className="flex flex-wrap items-end justify-between gap-6"><SectionHeading eyebrow="Product explorer" title="Configure the platform around your organization." copy="Modules are activated through packages, subscriptions and entitlements managed in Sabi Command Center." /><Status>Available</Status></div><div className="mt-12 grid gap-7 lg:grid-cols-[260px_1fr]"><div className="space-y-2">{(Object.keys(PRODUCTS) as ProductKey[]).map((key) => <button key={key} onClick={() => setProduct(key)} className={`w-full rounded-2xl border p-4 text-left transition ${product === key ? "border-brand-400 bg-brand-50 shadow-sm" : "border-slate-200 bg-white hover:border-brand-200"}`}><b className="block font-display">{PRODUCTS[key].label}</b><span className="mt-1 block text-xs leading-5 text-slate-500">{PRODUCTS[key].tagline}</span></button>)}</div><div className="rounded-[28px] bg-slate-950 p-6 text-white sm:p-9"><p className="text-xs font-bold uppercase tracking-widest text-brand-300">{productDef.releaseStatus}</p><h2 className="mt-3 font-display text-3xl font-extrabold">{productDef.label}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/55">{productDef.description}</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{modulesByProduct(product).map((module) => <div key={module.key} className="rounded-xl border border-white/10 bg-white/[.05] p-4"><div className="flex items-center justify-between gap-2"><b className="text-sm">{module.label}</b>{module.core && <span className="rounded-full bg-brand-300/15 px-2 py-1 text-[9px] font-bold uppercase text-brand-200">Core</span>}</div><p className="mt-2 text-xs leading-5 text-white/45">{module.description}</p></div>)}</div></div></div></div></section>
    <section className="bg-white px-5 py-24 lg:px-8"><div className="mx-auto max-w-[1350px]"><SectionHeading eyebrow="Connected capabilities" title="Depth where healthcare organizations need it." /><div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{categoryCards.map(({icon:Icon,title,items})=><article key={title} className="rounded-2xl border border-slate-200 p-5"><Icon className="text-brand-700" size={21}/><h3 className="mt-4 font-display font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{items}</p></article>)}</div></div></section>
    <EndCta title="Bring your healthcare organization onto one connected foundation." />
  </>;
}

export function SabiHealthPage() {
  const capabilities = [["Health records","Backend connection required","Patient records remain unavailable until the records service is connected."],["Prescriptions","Backend partial","The available backend can persist structured prescriptions; pharmacy fulfilment is not connected."],["Virtual consultations","Service unavailable","Video, voice and consultation scheduling require backend services."],["Pharmacy fulfilment","Service unavailable","Marketplace, quotes, payment and fulfilment services are not connected."],["Medication reminders","Service unavailable","Reminder scheduling and delivery require backend notification services."],["Health monitoring","Backend partial","The available vitals backend covers the signed-in patient only."]];
  return <><PageHero eyebrow="Sabi Health" title="Healthcare that follows the patient." copy="A patient-facing digital health experience for continuity across visits, prescriptions, records and virtual care — separate from the hospital's EMR." actions={<PublicCta to={TELEMEDICINE_SIGN_IN_URL}>Open Sabi Health</PublicCta>} aside={<div className="mx-auto max-w-md rounded-[30px] border border-white/10 bg-white/[.06] p-6"><div className="rounded-[24px] bg-[#effaf4] p-6 text-slate-900"><CircleUserRound className="text-brand-700"/><p className="mt-8 text-xs font-bold uppercase tracking-widest text-brand-700">Sabi ID</p><h2 className="mt-2 font-display text-2xl font-extrabold">Your care journey, in view.</h2><div className="mt-6 space-y-3">{["Visits & records","Prescriptions","Care reminders"].map((x,i)=><div key={x} className="flex items-center gap-3 rounded-xl bg-white p-4 shadow-sm"><span className="grid h-8 w-8 place-items-center rounded-lg bg-brand-50 text-brand-700">{i+1}</span><b className="text-sm">{x}</b></div>)}</div><p className="mt-5 text-[10px] font-semibold text-slate-400">Unavailable data is shown as an empty state until its service is connected.</p></div></div>} />
    <section className="px-5 py-24 lg:px-8"><div className="mx-auto max-w-[1200px]"><SectionHeading eyebrow="Patient platform" title="Continuity without confusing the patient portal with the hospital workspace." copy="Each capability reports whether the service needed to supply its data is connected." /><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{capabilities.map(([title,status,copy])=><article key={title} className="rounded-2xl border border-slate-200 bg-white p-6"><Status tone="soon">{status}</Status><h2 className="mt-5 font-display text-xl font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-500">{copy}</p></article>)}</div><p className="mt-8 rounded-2xl bg-slate-100 p-5 text-sm leading-6 text-slate-600">Unavailable services display empty or unavailable states. The interface does not substitute generated clinical or commercial information.</p></div></section>
    <section className="bg-white px-5 py-24 lg:px-8"><div className="mx-auto max-w-[1200px]"><JourneyMap /></div></section>
    <EndCta title="Help shape a more connected patient journey." primary="Register interest" />
  </>;
}

export function AIPage() {
  const areas = [[Stethoscope,"Clinical assistance","Structured clinical summaries, documentation support and relevant-history surfacing.","Controlled pilot"],[Hospital,"Hospital intelligence","Operational trends, abnormal-activity signals and capacity insights.","Pilot"],[Workflow,"Administrative automation","Reports, workflow monitoring and task prioritization.","Early access"],[Database,"Data intelligence","Completeness checks, intelligent search and analytics.","Early access"]] as const;
  return <><PageHero eyebrow="Sabi Intelligence" title="AI assistance designed around accountable healthcare." copy="Sabi Intelligence supports professionals with structure, context and workflow signals. It does not replace professional judgment or autonomously diagnose patients." actions={<PublicCta to="/book-demo">Discuss an AI pilot</PublicCta>} aside={<div className="rounded-[28px] border border-violet-300/20 bg-violet-300/10 p-7"><BrainCircuit size={32} className="text-violet-300"/><p className="mt-6 text-xs font-bold uppercase tracking-widest text-violet-200">A governed assistance layer</p><div className="mt-4 space-y-3">{["Human review","Role-aware context","Traceable workflows","Controlled rollout"].map(x=><div className="flex items-center gap-3 rounded-xl bg-black/15 p-3 text-sm font-semibold" key={x}><Check size={15} className="text-brand-300"/>{x}</div>)}</div></div>} />
    <section className="px-5 py-24 lg:px-8"><div className="mx-auto max-w-[1250px]"><SectionHeading eyebrow="Current direction" title="Practical intelligence, clearly labelled." copy="The current repository includes an AI assistant feature flag in Draft status. The experiences below describe controlled implementation and roadmap areas, not autonomous clinical functionality." /><div className="mt-12 grid gap-4 md:grid-cols-2">{areas.map(([Icon,title,copy,status])=><article key={title} className="rounded-[24px] border border-slate-200 bg-white p-7"><div className="flex items-start justify-between gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-50 text-violet-700"><Icon/></span><Status tone="pilot">{status}</Status></div><h2 className="mt-6 font-display text-xl font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-500">{copy}</p></article>)}</div><div className="mt-10 rounded-2xl border border-brand-200 bg-brand-50 p-6"><b className="font-display text-brand-900">Responsible use principle</b><p className="mt-2 text-sm leading-6 text-brand-900/70">AI supports healthcare professionals. Clinical decisions remain with qualified healthcare professionals. Outputs should be reviewed in context, with appropriate access, audit and safety controls.</p></div></div></section>
  </>;
}

export function SecurityPage() {
  const principles = [[Fingerprint,"Role-based access","Access is designed around roles, memberships and least privilege."],[Network,"Tenant isolation","Organization data and configuration are scoped to the active tenant."],[FileCheck2,"Audit trails","Important access and configuration activity can be recorded for review."],[LockKeyhole,"Secure authentication","The target architecture includes central identity, MFA readiness and session controls."],[Database,"Secure document storage","Sensitive documents belong in protected object storage, not browser local storage."],[ShieldCheck,"Privacy by design","Data minimization and controlled access guide feature design."]];
  return <><PageHero eyebrow="Security & privacy" title="Trust is not a badge. It is a system of controls." copy="Sabi Health is designed around access control, tenant isolation, auditability and privacy-conscious data handling. We do not claim certifications the product has not obtained." actions={<PublicCta to="/book-demo">Discuss security</PublicCta>} aside={<div className="rounded-[28px] border border-white/10 bg-white/[.06] p-8"><ShieldCheck size={42} className="text-brand-300"/><h2 className="mt-8 font-display text-2xl font-bold">Security principles</h2><p className="mt-3 text-sm leading-6 text-white/55">Architecture, hosting, configuration and organizational procedure must work together.</p></div>} />
    <section className="px-5 py-24 lg:px-8"><div className="mx-auto max-w-[1250px]"><SectionHeading eyebrow="Architecture" title="Layered controls for healthcare environments." /><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{principles.map(([Icon,title,copy])=>{const C=Icon as typeof ShieldCheck;return <article className="rounded-2xl border border-slate-200 bg-white p-6" key={String(title)}><C className="text-brand-700"/><h2 className="mt-5 font-display font-bold">{String(title)}</h2><p className="mt-3 text-sm leading-6 text-slate-500">{String(copy)}</p></article>})}</div><div className="mt-12 grid gap-5 lg:grid-cols-2"><InfoPanel title="Security roadmap" items={["Multi-factor authentication readiness","Session and device management","Access monitoring and revocation","Backup and recovery architecture","Encryption in transit and at rest in production infrastructure"]}/><InfoPanel title="Important qualification" items={["Compliance depends on configuration and hosting","Organizational procedures remain essential","Applicable regulatory requirements vary","No ISO 27001, HIPAA, SOC 2 or NDPC certification is claimed"]}/></div></div></section>
  </>;
}

export function AboutPage() {
  const team = [["SD","Sanusi Damilare","Founder"],["DA","Dapo Adediran","Co-Founder"],["RO","Rufia Opeyemoi","Co-Founder"],["WB","Williams Bashir","Co-Founder"]];
  return <><PageHero eyebrow="About Sabi Health" title="Building healthcare infrastructure for the next generation." copy="Healthcare systems across Africa are often fragmented. Sabi Health is working toward secure, structured and connected information that helps facilities, professionals and patients coordinate care." actions={<PublicCta to="/book-demo">Talk with us</PublicCta>} aside={<div className="rounded-[28px] border border-white/10 bg-white/[.06] p-8"><HeartHandshake size={38} className="text-brand-300"/><p className="mt-8 text-xs font-bold uppercase tracking-widest text-brand-200">Long-term vision</p><h2 className="mt-3 font-display text-3xl font-extrabold">One Patient.<br/>One Connected Health Journey.</h2></div>} />
    <section className="px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-[1250px] gap-12 lg:grid-cols-2"><SectionHeading eyebrow="The problem" title="Fragmentation makes everyone carry more." copy="Patient information may live in paper files and disconnected systems. Departments may operate independently. Clinicians may lack longitudinal context, while administrators struggle to see the whole organization."/><div className="rounded-[28px] bg-white p-8 shadow-xl ring-1 ring-slate-200"><h2 className="font-display text-2xl font-bold">Our mission</h2><p className="mt-5 text-base leading-8 text-slate-600">Help healthcare organizations deliver more connected, efficient and data-driven healthcare while giving patients greater continuity across their healthcare journey.</p><div className="mt-7 rounded-2xl bg-brand-50 p-5 text-sm leading-6 text-brand-900">A healthcare ecosystem where authorized professionals can access the right information at the right time, and patients do not repeatedly rebuild their medical story.</div></div></div></section>
    <section id="team" className="bg-white px-5 py-24 lg:px-8"><div className="mx-auto max-w-[1250px]"><SectionHeading eyebrow="Founding team" title="A team focused on the mission." copy="We use initials until approved founder photographs are available; no invented biographies or credentials are presented."/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{team.map(([initials,name,role])=><article key={name} className="rounded-2xl border border-slate-200 bg-[#f8fbf9] p-6"><div className="grid h-20 w-20 place-items-center rounded-2xl bg-slate-950 font-display text-xl font-extrabold text-brand-300">{initials}</div><h2 className="mt-6 font-display text-lg font-bold">{name}</h2><p className="mt-1 text-sm text-slate-500">{role}</p></article>)}</div></div></section>
    <EndCta title="Build the connected healthcare future with us." />
  </>;
}

export function PricingPage() {
  return apiConfigured ? <LivePricingPage /> : <FixturePricingPage />;
}

function LivePricingPage() {
  const { packages, loading, error } = useLivePackages();
  const money = (minor: number) => new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(minor / 100);
  return <><PageHero eyebrow="Sabi OS pricing" title="Published Sabi packages." copy="These are the price versions published by Sabi Command Center. Choosing a plan starts an application, not a subscription or payment." actions={<PublicCta to="/book-demo">Request pricing consultation</PublicCta>} />
    <section className="px-5 py-24 lg:px-8"><div className="mx-auto max-w-[1350px]"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{packages.map((item) => { const version = item.versions.find((candidate) => candidate.version === item.publishedVersion); if (!version) return null; return <article key={item.id} className={`relative flex flex-col rounded-[26px] border bg-white p-6 ${item.recommended ? "border-brand-400 shadow-xl" : "border-slate-200"}`}><h2 className="font-display text-2xl font-extrabold">{item.name}</h2><p className="mt-3 min-h-12 text-sm leading-6 text-slate-500">{item.description}</p><p className="mt-7 font-display text-3xl font-extrabold">{money(version.monthlyPriceMinor)}</p><p className="mt-1 text-xs text-slate-400">per month · before applicable taxes</p><div className="my-6 h-px bg-slate-100"/><CheckList items={[`Up to ${item.branchLimit} branches`, `${item.storageLimitGb} GB storage limit`, `${item.supportLevel.toLowerCase()} support`, `${version.moduleKeys.length} included products`]} /><div className="mt-auto pt-7"><PublicCta to={`/register/organization?plan=${encodeURIComponent(item.code.toLowerCase())}&billing=monthly`}>Choose package</PublicCta></div></article>; })}
      {loading && <p role="status" className="col-span-full text-center text-sm text-slate-500">Loading published packages…</p>}
      {error && <p role="alert" className="col-span-full rounded-xl bg-red-50 p-4 text-center text-sm text-red-700">{error}</p>}
      {!loading && !error && packages.length === 0 && <div className="col-span-full rounded-[26px] border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="font-display text-xl font-bold">No packages are published yet.</h2><p className="mt-2 text-sm text-slate-500">Sabi operations must publish a package before applicants can choose a plan.</p></div>}</div><p className="mt-8 text-center text-xs leading-5 text-slate-500">Choosing a package records a preference. It does not create a tenant, activate a subscription or process a payment.</p></div></section>
  </>;
}

function FixturePricingPage() {
  const packages = useCommandCenter((state) => state.packages);
  const versions = useCommandCenter((state) => state.packageVersions);
  const rows = packages.filter((item) => item.active).map((item) => ({ ...item, version: versions.find((v) => v.id === item.currentVersionId) })).filter((item) => item.version?.status === "Published");
  const money = (value: number) => new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(value);
  return <><PageHero eyebrow="Sabi OS pricing" title="Packages sourced from one commercial catalog." copy="These package names, limits and prices come directly from the same Command Center state used for subscriptions and entitlements." actions={<PublicCta to="/book-demo">Request pricing consultation</PublicCta>} />
    <section className="px-5 py-24 lg:px-8"><div className="mx-auto max-w-[1350px]"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{rows.map((item)=><article key={item.id} className={`relative flex flex-col rounded-[26px] border bg-white p-6 ${item.recommended ? "border-brand-400 shadow-xl" : "border-slate-200"}`}>{item.recommended && <span className="absolute -top-3 left-6 rounded-full bg-brand-600 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-white">Recommended</span>}<h2 className="font-display text-2xl font-extrabold">{item.name}</h2><p className="mt-3 min-h-12 text-sm leading-6 text-slate-500">{item.description}</p><p className="mt-7 font-display text-3xl font-extrabold">{item.version!.monthlyPrice ? money(item.version!.monthlyPrice) : "Talk to Sales"}</p><p className="mt-1 text-xs text-slate-400">{item.version!.monthlyPrice ? "per month · before applicable taxes" : "custom commercial terms"}</p><div className="my-6 h-px bg-slate-100"/><CheckList items={[`${item.minimumUsers}${item.maximumUsers ? `–${item.maximumUsers}` : "+"} users`, `Up to ${item.branchLimit} branches`, `${item.storageLimitGb} GB storage limit`, `${item.supportLevel} support`, `${item.version!.moduleIds.length} catalog modules`]} /><div className="mt-auto pt-7">{item.version!.monthlyPrice ? <PublicCta to={`/register/organization?plan=${encodeURIComponent(item.code.toLowerCase())}&billing=monthly`}>Choose package</PublicCta> : <PublicCta to="/book-demo">Talk to Sales</PublicCta>}</div></article>)}{rows.length===0&&<div className="col-span-full rounded-[26px] border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="font-display text-xl font-bold">No packages are available yet.</h2><p className="mt-2 text-sm text-slate-500">Published package information will appear here when the commercial catalog is connected.</p></div>}</div><p className="mt-8 text-center text-xs leading-5 text-slate-500">Choosing a package records your preference for onboarding. It does not activate a subscription or process a payment. Final pricing, implementation scope, taxes and terms require confirmation.</p></div></section>
  </>;
}

const solutionContent: Record<string, { title: string; copy: string; focus: string[] }> = {
  hospitals: { title: "Connected hospital operations, from care to finance.", copy: "Bring clinical, diagnostic, workforce and financial workflows into a modular hospital workspace.", focus: ["Longitudinal patient records","Wards, nursing and diagnostics","Billing, inventory and equipment","Workforce and accounting options"] },
  clinics: { title: "A focused operating system for growing clinics.", copy: "Start with the workflows your clinic needs and expand through packages and entitlements.", focus: ["Registration and appointments","Consultation and patient history","Billing and pharmacy options","Lean workforce operations"] },
  laboratories: { title: "Structured diagnostic workflows with connected context.", copy: "Support laboratory order, sample, result and approval flows within the wider care journey.", focus: ["Orders and sample tracking","Result entry and approval","Turnaround visibility","Patient and encounter context"] },
  "hospital-groups": { title: "One control plane for multi-branch healthcare groups.", copy: "Manage organizations, branches, users, subscriptions and entitlements with tenant-aware platform controls.", focus: ["Multi-facility tenant model","Branch-aware entitlements","Shared platform governance","Consolidated operational visibility"] },
};

export function SolutionsPage() {
  const { type = "hospitals" } = useParams();
  const content = solutionContent[type] ?? { title: "A configurable foundation for healthcare facilities.", copy: "Sabi OS is architected to adapt terminology, modules and workflows to different facility models.", focus: ["Configurable terminology","Modular entitlements","Tenant-aware data","Expandable facility types"] };
  return <><PageHero eyebrow="Solutions" title={content.title} copy={content.copy} actions={<><PublicCta to="/register">Get Started</PublicCta><PublicCta to="/book-demo" secondary>Book a Demo</PublicCta></>} aside={<div className="grid grid-cols-2 gap-3">{content.focus.map((item,i)=><div key={item} className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><span className="text-xs font-extrabold text-brand-300">0{i+1}</span><p className="mt-5 text-sm font-bold leading-6">{item}</p></div>)}</div>} /><section className="px-5 py-24 lg:px-8"><div className="mx-auto max-w-[1150px]"><SectionHeading eyebrow="Modular by design" title="Start from your real workflow." copy="Facility types are configuration inputs, not separate disconnected products. Packages establish the baseline while entitlements control the modules available to each organization."/><div className="mt-12 grid gap-4 md:grid-cols-3">{[[PackageCheck,"Choose a package","Use the shared commercial catalog."],[Building2,"Configure the organization","Set branches, identity and terminology."],[BadgeCheck,"Resolve entitlements","Expose only licensed products and modules."]].map(([Icon,title,copy])=>{const C=Icon as typeof PackageCheck; return <article key={String(title)} className="rounded-2xl border border-slate-200 bg-white p-6"><C className="text-brand-700"/><h2 className="mt-5 font-display font-bold">{String(title)}</h2><p className="mt-2 text-sm text-slate-500">{String(copy)}</p></article>})}</div></div></section></>;
}

export function ResourcesPage() {
  const resources = [[BookOpen,"Documentation","Placeholder route for approved product documentation."],[Laptop,"Help Centre","Placeholder route for support content and guided help."],[Activity,"System Status","Placeholder route for a future public status experience."],[FileHeart,"Privacy","Placeholder for legal copy pending formal approval."],[ReceiptText,"Terms","Placeholder for terms pending formal approval."],[Globe2,"Careers","Placeholder for future careers information."]];
  return <><PageHero eyebrow="Resources" title="Product guidance and company resources." copy="Routes are in place for future approved content. Legal and policy copy is explicitly marked as pending rather than fabricated." /><section className="px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-[1200px] gap-4 md:grid-cols-2 lg:grid-cols-3">{resources.map(([Icon,title,copy])=>{const C=Icon as typeof BookOpen; const id=String(title).toLowerCase().replaceAll(" ","-"); return <article id={id} key={String(title)} className="scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-6"><C className="text-brand-700"/><Status tone="soon">Content pending</Status><h2 className="mt-5 font-display text-xl font-bold">{String(title)}</h2><p className="mt-3 text-sm leading-6 text-slate-500">{String(copy)}</p></article>})}</div></section></>;
}

export function RegisterEntryPage() {
  return <><PageHero eyebrow="Get started" title="How would you like to use Sabi?" copy="Choose the pathway that matches who you are. Organization onboarding and patient registration remain separate." /><section className="px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-[1050px] gap-5 md:grid-cols-3"><EntryCard icon={<Hospital/>} title="Healthcare Organization" copy="Hospital, clinic, laboratory, diagnostic centre or healthcare organization." status="Available" action="Begin organization application" to="/register/organization"/><EntryCard icon={<Stethoscope/>} title="Healthcare Professional" copy="Professional registration requires backend verification before access can be granted." status="Registration pending" action="View product information" to="/products/sabi-health"/><EntryCard icon={<CircleUserRound/>} title="Patient" copy="Use the existing Sabi Health patient and telemedicine platform." status="Available" action="Open Sabi Health" to={TELEMEDICINE_SIGN_IN_URL}/></div><p className="mx-auto mt-8 max-w-2xl text-center text-sm leading-6 text-slate-500">Organization applications are saved progressively and remain separate from production tenants until verification, approval and authorized provisioning are complete.</p></section></>;
}

export function BookDemoPage() {
  const [submissionError, setSubmissionError] = useState("");
  const [facilityType, setFacilityType] = useState("Hospital");
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmissionError("Sales request submission is not connected yet. No information was sent."); window.scrollTo({ top: 0, behavior: "smooth" }); }
  if (submissionError) return <section className="grid min-h-[70vh] place-items-center px-5 py-20"><div className="max-w-xl rounded-[28px] border border-amber-200 bg-white p-9 text-center shadow-xl"><h1 className="font-display text-3xl font-extrabold">Request not sent</h1><p className="mt-4 text-sm leading-6 text-slate-500">{submissionError} Please contact Sabi Health through an approved support channel.</p><div className="mt-7"><PublicCta to="/book-demo">Return to the form</PublicCta></div></div></section>;
  return <><PageHero eyebrow="Book a demo" title="See how Sabi could fit your organization." copy="Tell us about your facility and priorities. A demo request is a sales lead, not a tenant or regulatory application." /><section className="px-5 py-20 lg:px-8"><form onSubmit={submit} className="mx-auto max-w-4xl rounded-[28px] border border-slate-200 bg-white p-6 shadow-xl sm:p-9"><div className="grid gap-5 sm:grid-cols-2"><DemoField label="Name"><input required name="name" autoComplete="name" className="input"/></DemoField><DemoField label="Work email"><input required type="email" name="email" autoComplete="email" className="input"/></DemoField><DemoField label="Phone"><input required type="tel" name="phone" autoComplete="tel" className="input" placeholder="+234…"/></DemoField><DemoField label="Organization"><input required name="organization" autoComplete="organization" className="input"/></DemoField><DemoField label="Role"><input required name="role" className="input"/></DemoField><DemoField label="Facility type"><select required name="facilityType" className="input" value={facilityType} onChange={(e)=>setFacilityType(e.target.value)}>{["Hospital","Clinic","Laboratory","Diagnostic Centre","Maternity Centre","Hospital Group","Other Healthcare Facility"].map(x=><option key={x}>{x}</option>)}</select></DemoField><DemoField label="Approximate staff"><input required type="number" min="1" name="staff" className="input"/></DemoField><DemoField label="Number of locations"><input required type="number" min="1" name="locations" className="input"/></DemoField><DemoField label="Current system"><input name="currentSystem" className="input" placeholder="Paper, spreadsheets, another EMR…"/></DemoField><DemoField label="Desired timeline"><select name="timeline" className="input"><option>Exploring options</option><option>Within 3 months</option><option>Within 6 months</option><option>Within 12 months</option></select></DemoField><div className="sm:col-span-2"><DemoField label="Main challenge"><textarea required name="challenge" className="input min-h-28 resize-y"/></DemoField></div></div><div className="mt-7 flex flex-col items-start justify-between gap-4 border-t border-slate-100 pt-6 sm:flex-row sm:items-center"><p className="max-w-lg text-xs leading-5 text-slate-400">Do not include patient, clinical or regulatory document information in this form.</p><button className="public-button-primary" type="submit">Request demo <ArrowRight size={16}/></button></div></form></section></>;
}

function DemoField({label,children}:{label:string;children:ReactNode}) { return <label className="block"><span className="label">{label}</span>{children}</label>; }
function EntryCard({icon,title,copy,status,action,to}:{icon:ReactNode;title:string;copy:string;status:string;action:string;to:string}) { return <article className="flex flex-col rounded-[24px] border border-slate-200 bg-white p-6 shadow-sm"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-brand-50 text-brand-700">{icon}</span><Status tone="soon">{status}</Status><h2 className="mt-5 font-display text-xl font-bold">{title}</h2><p className="mt-3 flex-1 text-sm leading-6 text-slate-500">{copy}</p><Link to={to} className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-brand-700">{action}<ArrowRight size={15}/></Link></article>; }
function InfoPanel({title,items}:{title:string;items:string[]}) { return <div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-display text-lg font-bold">{title}</h2><div className="mt-5"><CheckList items={items}/></div></div>; }
function EndCta({title,primary="Register Organization"}:{title:string;primary?:string}) { return <section className="bg-slate-950 px-5 py-20 text-white lg:px-8"><div className="mx-auto flex max-w-[1200px] flex-col gap-7 rounded-[28px] border border-white/10 bg-white/[.05] p-8 sm:p-11 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-brand-300">Next step</p><h2 className="mt-3 max-w-2xl font-display text-3xl font-extrabold">{title}</h2></div><div className="flex shrink-0 flex-wrap gap-3"><PublicCta to="/register">{primary}</PublicCta><PublicCta to="/book-demo" secondary>Book a Demo</PublicCta></div></div></section>; }
