import { Link } from "react-router-dom";
import { ArrowDown, ArrowRight, BrainCircuit, Building2, CheckCircle2, CircleUserRound, DatabaseZap, FileHeart, Globe2, Hospital, LockKeyhole, Network, ShieldCheck, Sparkles, Workflow } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";
import { PublicCta, ProductWindow, SectionHeading, Status, JourneyMap } from "@/public/components";
import { categoryCards } from "@/public/content";

const flow = ["Registration", "Consultation", "Laboratory", "Pharmacy", "Billing", "Follow-up"];
const facilities = ["Hospitals", "Clinics", "Diagnostic Centres", "Laboratories", "Maternity Centres", "Dental Clinics", "Multi-Branch Hospital Groups", "Healthcare Networks"];

export default function HomePage() {
  const reduceMotion = useReducedMotion();
  return (
    <>
      <section className="relative overflow-hidden bg-[#061d15] text-white">
        <div className="public-grid absolute inset-0 opacity-30" />
        <div className="absolute -left-24 top-28 h-72 w-72 rounded-full bg-brand-500/20 blur-[100px]" /><div className="absolute right-0 top-0 h-96 w-96 rounded-full bg-cyan-400/10 blur-[120px]" />
        <div className="relative mx-auto grid min-h-[calc(100vh-72px)] max-w-[1500px] items-center gap-12 px-5 py-20 lg:grid-cols-[.82fr_1.18fr] lg:px-8 lg:py-24">
          <motion.div initial={reduceMotion ? false : { opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .65 }}>
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-brand-300/20 bg-brand-300/10 px-3 py-1.5 text-xs font-bold text-brand-200"><Sparkles size={13} /> Intelligent Healthcare. Connected.</div>
            <h1 className="text-balance font-display text-5xl font-extrabold leading-[.98] tracking-[-0.055em] sm:text-6xl xl:text-7xl">Healthcare,<br /><span className="text-brand-300">intelligently</span> connected.</h1>
            <p className="mt-7 max-w-xl text-lg leading-8 text-emerald-50/70">Sabi Health brings clinical care, hospital operations and digital health services together in one connected healthcare ecosystem.</p>
            <div className="mt-9 flex flex-wrap gap-3"><PublicCta to="/register">Get Started</PublicCta><PublicCta to="/book-demo" secondary>Book a Demo</PublicCta><Link to="/products/sabi-os" className="inline-flex items-center gap-2 px-2 py-3 text-sm font-bold text-brand-200 hover:text-white">Explore Sabi OS <ArrowRight size={16} /></Link></div>
            <div className="mt-10 flex flex-wrap items-center gap-x-7 gap-y-3 border-t border-white/10 pt-6 text-xs font-semibold text-white/50"><span className="inline-flex items-center gap-2"><ShieldCheck size={15} className="text-brand-300" /> Tenant-aware architecture</span><span className="inline-flex items-center gap-2"><Workflow size={15} className="text-brand-300" /> Connected workflows</span><span className="inline-flex items-center gap-2"><CircleUserRound size={15} className="text-brand-300" /> Human-centred care</span></div>
          </motion.div>
          <motion.div initial={reduceMotion ? false : { opacity: 0, scale: .97, x: 18 }} animate={{ opacity: 1, scale: 1, x: 0 }} transition={{ delay: .15, duration: .7 }}><ProductWindow /></motion.div>
          <a href="#fragmentation" className="absolute bottom-6 left-1/2 hidden -translate-x-1/2 animate-bounce text-white/35 lg:block" aria-label="Scroll to next section"><ArrowDown size={20} /></a>
        </div>
      </section>

      <section className="border-b border-slate-200 bg-white py-7"><p className="mx-auto max-w-[1500px] px-5 text-center text-sm font-semibold text-slate-500 lg:px-8">Built for modern healthcare organizations — without invented customer counts, logos or certification claims.</p></section>

      <section id="fragmentation" className="px-5 py-24 lg:px-8 lg:py-32">
        <div className="mx-auto max-w-[1350px]"><SectionHeading eyebrow="The connected record" title="Patient records should not live in silos." copy="Care becomes harder when every department sees only one fragment of the patient's journey. Sabi OS is designed to connect the operational handoffs around care into structured, longitudinal information." centered />
          <div className="mt-14 grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{flow.map((item, i) => <div key={item} className="relative rounded-2xl border border-slate-200 bg-white px-4 py-5 text-center shadow-sm"><span className="mx-auto grid h-8 w-8 place-items-center rounded-full bg-brand-50 text-xs font-extrabold text-brand-700">{i + 1}</span><b className="mt-3 block text-sm text-slate-800">{item}</b>{i < flow.length - 1 && <ArrowRight className="absolute -right-3 top-1/2 z-10 hidden -translate-y-1/2 text-brand-400 lg:block" size={18} />}</div>)}</div>
          <div className="mt-7 rounded-2xl border border-brand-200 bg-brand-50/70 p-5 text-center text-sm font-semibold text-brand-900"><FileHeart className="mr-2 inline" size={18} /> One connected health journey, with the right information available to authorized care teams.</div>
        </div>
      </section>

      <section className="bg-white px-5 py-24 lg:px-8 lg:py-32">
        <div className="mx-auto max-w-[1350px]"><div className="flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><SectionHeading eyebrow="Sabi OS" title="The operating system for modern healthcare organizations." copy="Clinical care, people, operations and finance share one modular platform instead of becoming separate islands." /><div className="shrink-0"><Status>Available</Status></div></div>
          <div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{categoryCards.map(({ icon: Icon, title, items }, i) => <motion.article key={title} initial={reduceMotion ? false : { opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .05 }} className="group rounded-[22px] border border-slate-200 bg-[#f8fbf9] p-5 transition hover:-translate-y-1 hover:border-brand-300 hover:bg-white hover:shadow-xl"><span className="grid h-11 w-11 place-items-center rounded-xl bg-slate-950 text-brand-300"><Icon size={20} /></span><h3 className="mt-5 font-display text-lg font-extrabold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-550">{items}</p></motion.article>)}</div>
          <div className="mt-10"><PublicCta to="/products/sabi-os">Explore the product</PublicCta></div>
        </div>
      </section>

      <section className="overflow-hidden bg-[#0b221a] px-5 py-24 text-white lg:px-8 lg:py-32"><div className="mx-auto grid max-w-[1350px] gap-14 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><Status tone="pilot">Controlled pilot</Status><div className="mt-5"><SectionHeading eyebrow="Sabi Intelligence" title="Intelligence embedded into healthcare workflows." copy="Sabi is designed to assist with documentation, workflow monitoring, anomaly signals and structured summaries — with people firmly in control." /></div><p className="mt-6 rounded-xl border border-brand-300/20 bg-brand-300/10 p-4 text-sm leading-6 text-brand-100">AI supports healthcare professionals. Clinical decisions remain with qualified healthcare professionals.</p><div className="mt-7"><PublicCta to="/ai" secondary>Explore responsible AI</PublicCta></div></div><div className="grid gap-3 sm:grid-cols-2">{[[BrainCircuit,"Clinical assistance","Structured summaries and documentation support."],[Building2,"Hospital intelligence","Operational trends and capacity signals."],[Workflow,"Administrative automation","Workflow monitoring and task prioritization."],[DatabaseZap,"Data intelligence","Completeness checks, search and analytics."]].map(([Icon,title,copy]) => { const C = Icon as typeof BrainCircuit; return <div key={String(title)} className="rounded-2xl border border-white/10 bg-white/[.06] p-6"><C size={21} className="text-brand-300" /><h3 className="mt-4 font-display font-bold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-white/55">{String(copy)}</p></div>; })}</div></div></section>

      <section className="px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto grid max-w-[1350px] gap-14 lg:grid-cols-2 lg:items-center"><div><Status tone="pilot">Beta direction</Status><div className="mt-5"><SectionHeading eyebrow="Sabi Health for patients" title="Healthcare that follows the patient." copy="The patient-facing direction is distinct from the hospital EMR: one place for personal records, prescriptions, pharmacy journeys and future virtual care." /></div><div className="mt-7 flex flex-wrap gap-2">{["Health records · Beta", "Prescriptions · Beta", "Medication reminders · Planned", "Virtual consultation · Planned", "Pharmacy fulfilment · Planned"].map((item) => <span key={item} className="rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-600">{item}</span>)}</div><div className="mt-8"><PublicCta to="/products/sabi-health">Explore Sabi Health</PublicCta></div></div><PhonePair /></div></section>

      <section className="bg-white px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-[1350px]"><SectionHeading eyebrow="Connected ecosystem" title="One patient. One connected health journey." copy="Sabi Identity is the architectural bridge between people, their organization memberships and the products they are authorized to use." centered /><div className="mt-14"><JourneyMap /></div></div></section>

      <section className="px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-[1350px]"><SectionHeading eyebrow="Solutions by facility" title="Different facilities. One adaptable foundation." copy="The architecture is designed for configurable workflows, terminology and entitlements across many types of healthcare organizations." /><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{facilities.map((item) => <Link key={item} to={`/solutions/${item.toLowerCase().replaceAll(" ", "-")}`} className="group flex min-h-32 flex-col justify-between rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-brand-300 hover:shadow-lg"><Hospital size={20} className="text-brand-700" /><span className="flex items-end justify-between gap-3 font-display font-bold text-slate-800">{item}<ArrowRight size={16} className="shrink-0 transition group-hover:translate-x-1" /></span></Link>)}</div></div></section>

      <section className="bg-[#eaf8f0] px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-[1350px] gap-12 lg:grid-cols-2"><div><SectionHeading eyebrow="Security & privacy" title="Trust is part of the architecture." copy="Role-based access, tenant isolation, audit trails, secure session design and least privilege guide the platform's implementation." /><div className="mt-8"><PublicCta to="/security">Review our principles</PublicCta></div></div><div className="grid gap-3 sm:grid-cols-2">{[[LockKeyhole,"Access control"],[ShieldCheck,"Auditability"],[Network,"Tenant isolation"],[Globe2,"Interoperability-ready"]].map(([Icon,label]) => { const C = Icon as typeof LockKeyhole; return <div key={String(label)} className="flex items-center gap-4 rounded-2xl bg-white p-5 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-50 text-brand-700"><C size={19} /></span><b>{String(label)}</b></div>; })}</div><p className="lg:col-span-2 text-xs leading-5 text-slate-500">Compliance depends on configuration, hosting, organizational procedures and applicable regulatory requirements. No certification is implied.</p></div></section>

      <section className="px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-[1100px] text-center"><SectionHeading eyebrow="Our mission" title="Building healthcare infrastructure for the next generation." copy="We want authorized healthcare professionals to have the right information at the right time, while patients no longer have to rebuild their medical story from scratch." centered /><div className="mt-9"><PublicCta to="/about">Meet Sabi Health</PublicCta></div></div></section>

      <section className="bg-slate-950 px-5 py-20 text-white lg:px-8"><div className="mx-auto grid max-w-[1350px] gap-5 lg:grid-cols-2"><PersonaCta title="Bring your organization to Sabi." copy="Start the path toward a connected healthcare workspace." primary="Register Organization" to="/register" secondary="Book a Demo" secondaryTo="/book-demo" /><PersonaCta title="Your healthcare journey, connected." copy="Explore the patient-facing Sabi Health direction." primary="Explore Sabi Health" to="/products/sabi-health" /></div></section>
    </>
  );
}

function PhonePair() { return <div className="relative mx-auto h-[430px] max-w-lg"><div className="absolute left-[8%] top-10 h-[370px] w-[210px] -rotate-6 rounded-[35px] border-[7px] border-slate-900 bg-white p-4 shadow-2xl"><div className="mx-auto h-1.5 w-16 rounded-full bg-slate-200" /><p className="mt-7 text-[10px] font-bold text-brand-700">GOOD MORNING</p><h3 className="mt-1 font-display text-lg font-extrabold">Your health, together.</h3><div className="mt-5 rounded-2xl bg-brand-gradient p-4 text-white"><p className="text-[9px] text-white/70">Health snapshot</p><p className="mt-2 text-2xl font-bold">Connected</p></div><div className="mt-3 grid grid-cols-2 gap-2">{["Records","Medicines","Visits","Profile"].map(x=><div key={x} className="rounded-xl bg-slate-50 p-3 text-[9px] font-bold">{x}</div>)}</div></div><div className="absolute right-[8%] top-0 h-[390px] w-[220px] rotate-6 rounded-[38px] border-[7px] border-slate-900 bg-[#effaf4] p-4 shadow-2xl"><div className="mx-auto h-1.5 w-16 rounded-full bg-slate-300" /><div className="mt-8 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-white"><CircleUserRound className="text-brand-700" /></span><div><p className="text-[9px] text-slate-400">Sabi ID</p><b className="text-xs">Patient profile</b></div></div><div className="mt-6 space-y-3">{["Latest consultation","Prescription history","Laboratory results","Care reminders"].map((x,i)=><div key={x} className="rounded-xl bg-white p-3 shadow-sm"><div className="flex items-center gap-2"><CheckCircle2 size={13} className={i<2?"text-brand-600":"text-slate-300"}/><span className="text-[10px] font-semibold">{x}</span></div></div>)}</div><p className="mt-5 text-center text-[9px] font-bold uppercase tracking-widest text-slate-400">Patient experience concept</p></div></div>; }

function PersonaCta({ title, copy, primary, to, secondary, secondaryTo }: { title: string; copy: string; primary: string; to: string; secondary?: string; secondaryTo?: string }) { return <div className="rounded-[26px] border border-white/10 bg-white/[.05] p-7 sm:p-10"><h2 className="font-display text-2xl font-extrabold tracking-tight">{title}</h2><p className="mt-3 text-sm text-white/55">{copy}</p><div className="mt-7 flex flex-wrap gap-3"><PublicCta to={to}>{primary}</PublicCta>{secondary && secondaryTo && <PublicCta to={secondaryTo} secondary>{secondary}</PublicCta>}</div></div>; }
