import React, { useEffect, useRef, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowLeft, ArrowRight, CheckCircle2, Eye, EyeOff, FileCheck2, LockKeyhole, Save, Upload, X } from "lucide-react";
import AuthLayout from "./AuthLayout";
import { EMPTY_REGISTRATION, DRAFT_KEY, SPECIALTIES, STATES, draftValues, loadRegistrationDraft, documentError, validateRegistrationStep, registrationPayload } from "./registrationModel";
import { AUTH_CONFIGURED, PREVIEW_ENABLED, REGISTRATION_CONFIGURED, TERMS_URL, PRIVACY_URL, getRegistrationConfig, registerDoctor } from "../../services/doctorAuth";
import { toISO } from "../../utils/dateFormat";

import RegistrationProgress, {REGISTRATION_STEPS as STEPS} from "./RegistrationProgress";
function Field({ name, label, errors, children, hint }) {
  return <div className="sh-auth-field"><label htmlFor={name}>{label}</label>{children}{hint && <small id={`${name}-hint`}>{hint}</small>}{errors[name] && <span className="sh-field-error" id={`${name}-error`}>{errors[name]}</span>}</div>;
}
export function LegalNotice({ kind, onClose, profession = 'DOCTOR' }) {
  const dialog = useRef(null);
  const close = useRef(onClose);
  close.current = onClose;
  useEffect(() => {
    const previous = document.activeElement;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    dialog.current?.querySelector("button")?.focus();
    function keydown(event) {
      if (event.key === "Escape") { event.preventDefault(); close.current(); }
      if (event.key !== "Tab") return;
      const focusable = [...dialog.current.querySelectorAll("button, a[href], input")];
      const first = focusable[0], last = focusable[focusable.length - 1];
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); }
      if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); }
    }
    document.addEventListener("keydown", keydown);
    return () => { document.removeEventListener("keydown", keydown); document.body.style.overflow = previousOverflow; previous?.focus(); };
  }, []);
  if (profession !== 'DOCTOR') return <div className="sh-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section ref={dialog} className="sh-legal-modal" role="dialog" aria-modal="true" aria-label="Professional registration information"><button className="sh-icon-button" onClick={onClose} aria-label="Close notice"><X size={20}/></button><h2>{kind==='terms'?'Professional registration conditions':'Registration privacy information'}</h2>{kind==='terms'?<><p>Provide accurate qualifications and evidence appropriate to your selected discipline. Sabi operations independently reviews professional eligibility before enabling services. Registration or uploaded documents alone do not grant clinical access.</p><p>Work only within your reviewed professional scope. Maintain applicable registration and licensing, protect your account and patient confidentiality, and do not represent platform approval as statutory registration. Non-doctor roles do not receive medication prescribing or general patient medical-record access.</p></>:<><p>Sabi collects contact information, qualifications and credential evidence for verification. Authorised Sabi reviewers can inspect it. Files are held privately in Supabase and sent to Cloudmersive for malware screening; Resend sends account emails. Do not submit patient records in this form.</p><p>Contact Sabi for privacy, retention and account assistance. Review the platform's published privacy policy before providing real personal information. No password or credential document is saved in a browser registration draft.</p></>}<button className="sh-primary-button" onClick={onClose}>Back to registration</button></section></div>;
  return <div className="sh-modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><section ref={dialog} className="sh-legal-modal" role="dialog" aria-modal="true" aria-label={kind === "terms" ? "Doctor registration conditions" : "Registration privacy information"}><button className="sh-icon-button" onClick={onClose} aria-label="Close notice"><X size={20} /></button><h2>{kind === "terms" ? "Doctor registration conditions" : "Registration privacy information"}</h2>{kind === "terms" ? <><p>Provide accurate qualifications and current practising credentials. Sabi operations must independently verify your documents before clinical access is granted. Email verification does not grant permission to practise.</p><p>You must maintain your professional registration, protect your account and comply with your professional responsibilities. Access may be restricted or suspended when eligibility cannot be confirmed.</p></> : <><p>Sabi collects your contact details, qualifications and licensing evidence for account setup and professional verification. Authorized Sabi reviewers can inspect submitted credentials.</p><p>Credential files are kept in private Supabase storage and sent to Cloudmersive for malware screening. Resend delivers verification and approval emails. Do not upload patient records in this application.</p><p>Saving a draft stores contact and professional details in this browser tab, but not passwords or documents. Review the published platform privacy policy for retention, privacy contacts and your rights before providing real personal information.</p></>}{PREVIEW_ENABLED && <p>Local preview: no account, document upload or email is created.</p>}<button className="sh-primary-button" onClick={onClose}>Back to registration</button></section></div>;
}
function DocumentUpload({ name, title, description, file, error, onChange }) {
  return <div className={`sh-upload${error ? " sh-upload-error" : ""}`}><div className="sh-upload-icon">{file ? <FileCheck2 size={24} /> : <Upload size={24} />}</div><div className="sh-upload-content"><strong>{title}</strong><p>{description}</p>{file ? <div className="sh-file-selected"><CheckCircle2 size={15} /><span>{file.name} · {(file.size / 1024).toFixed(0)} KB</span><button type="button" onClick={() => onChange(name, null)} aria-label={`Remove ${title}`}><X size={15} /></button></div> : <small>PDF, JPG or PNG · up to 5 MB</small>}<label className="sh-upload-button" htmlFor={name}>{file ? "Replace file" : "Choose file"}<input id={name} type="file" accept="application/pdf,image/jpeg,image/png" aria-label={title} onChange={(e) => { onChange(name, e.target.files?.[0] || null); e.target.value = ""; }} /></label>{error && <span className="sh-field-error" id={`${name}-error`}>{error}</span>}</div></div>;
}

export default function DoctorRegistrationPage({ onChooseProfession } = {}) {
  const navigate = useNavigate();
  const [values, setValues] = useState(loadRegistrationDraft);
  const [documents, setDocuments] = useState({ licence: null, registrationCertificate: null });
  const [step, setStep] = useState(0);
  const [errors, setErrors] = useState({});
  const [showPassword, setShowPassword] = useState(false);
  const [notice, setNotice] = useState("");
  const [legal, setLegal] = useState(null);
  const [busy, setBusy] = useState(false);
  const [intake, setIntake] = useState({ enabled: PREVIEW_ENABLED, loaded: PREVIEW_ENABLED });
  useEffect(() => { if (PREVIEW_ENABLED || !REGISTRATION_CONFIGURED) return; let active = true; getRegistrationConfig().then((config) => { if (active) setIntake({ ...config, loaded: true }); }).catch(() => { if (active) setIntake({ enabled: false, loaded: true }); }); return () => { active = false; }; }, []);
  const heading = useRef(null);
  function update(name, value) { setValues((v) => ({ ...v, [name]: value })); setErrors((e) => ({ ...e, [name]: undefined })); setNotice(""); }
  function input(name, extra = {}) { return { id: name, name, value: values[name], onChange: (e) => update(name, e.target.value), "aria-invalid": !!errors[name], "aria-describedby": errors[name] ? `${name}-error` : undefined, ...extra }; }
  function changeStep(next) { setStep(next); setErrors({}); setNotice(""); requestAnimationFrame(() => heading.current?.focus()); }
  function chooseFile(name, file) { const error = file ? documentError(file) : ""; setDocuments((d) => ({ ...d, [name]: error ? null : file })); setErrors((e) => ({ ...e, [name]: error || undefined })); }
  function saveDraft() { try { sessionStorage.setItem(DRAFT_KEY, JSON.stringify(draftValues(values))); setNotice("Draft saved in this tab. Re-enter your password when you return. Documents are uploaded after email verification."); } catch { setNotice("We couldn't save your draft. Please keep this tab open."); } }
  async function submit(event) {
    event.preventDefault();
    if (busy) return;
    const currentErrors = validateRegistrationStep(step, values, documents, new Date(), PREVIEW_ENABLED);
    setErrors(currentErrors);
    if (Object.keys(currentErrors).length) { setNotice("Please check the highlighted fields."); requestAnimationFrame(() => document.getElementById(Object.keys(currentErrors)[0])?.focus()); return; }
    if (step < 3) { changeStep(step + 1); return; }
    for (let i = 0; i < 3; i++) { const checks = validateRegistrationStep(i, values, documents, new Date(), PREVIEW_ENABLED); if (Object.keys(checks).length) { changeStep(i); setErrors(checks); return; } }
    setBusy(true); setNotice("");
    try {
      const result = PREVIEW_ENABLED ? { mode: "preview", status: "ready", email: values.email, applicationId: `PREVIEW-${crypto.randomUUID().slice(0, 8).toUpperCase()}` } : await registerDoctor(registrationPayload(values));
      // Never persist passwords or licensing documents in browser storage.
      try { sessionStorage.removeItem(DRAFT_KEY); } catch { /* draft cleanup only */ }
      setValues({ ...EMPTY_REGISTRATION }); setDocuments({ licence: null, registrationCertificate: null });
      navigate("/registration/status", { state: { ...result, email: result.email || values.email } });
    } catch (error) { setNotice(error.name === "TimeoutError" ? "This request took too long. Please try again." : error.message); } finally { setBusy(false); }
  }
  function policy(kind) { const url = kind === "terms" ? TERMS_URL : PRIVACY_URL; return url ? <a href={url} target="_blank" rel="noreferrer">{kind === "terms" ? "Doctor Terms" : "Privacy Notice"}</a> : <button type="button" className="sh-inline-link" onClick={() => setLegal(kind)}>{kind === "terms" ? "Doctor Terms" : "Privacy Notice"}</button>; }
  return <AuthLayout><div className="sh-auth-topline"><span>DOCTOR REGISTRATION</span>{onChooseProfession && <button type="button" className="sh-inline-link" onClick={onChooseProfession}>Choose another profession</button>}<div>Already registered? <Link to="/login">Sign in</Link></div></div>
    <div className="sh-register-content"><div className="sh-register-intro"><span className="sh-auth-kicker">WELCOME TO SABI HEALTH</span><h1>Create your doctor account</h1><p>Tell us about your practice. We'll review your credentials before activating your clinical workspace.</p></div>
      {!PREVIEW_ENABLED && !intake.enabled && <div className="sh-form-notice" role="status">{intake.loaded ? "Doctor registration is temporarily unavailable." : "Checking registration availability…"} Existing approved doctors can <Link to="/login">sign in</Link>. You can review the application form below.</div>}
      <RegistrationProgress step={step}/>
      <form className="sh-register-form" onSubmit={submit} noValidate><div className="sh-form-heading"><div><span>STEP {step + 1} OF 4</span><h2 ref={heading} tabIndex={-1}>{STEPS[step]}</h2></div>{!AUTH_CONFIGURED && <span className="sh-preview-pill">Preview</span>}</div>
        {notice && <div className="sh-form-notice" role={Object.values(errors).some(Boolean) ? "alert" : "status"}>{notice}</div>}
        {step === 0 && <><div className="sh-form-grid"><Field name="firstName" label="First name" errors={errors}><input {...input("firstName", { autoComplete: "given-name", maxLength: 80, placeholder: "First name" })} /></Field><Field name="lastName" label="Last name" errors={errors}><input {...input("lastName", { autoComplete: "family-name", maxLength: 80, placeholder: "Last name" })} /></Field></div><Field name="email" label="Email address" hint="Use an email you can access. You'll need to verify it." errors={errors}><input {...input("email", { type: "email", autoComplete: "email", maxLength: 254, placeholder: "you@example.com" })} /></Field><Field name="phone" label="Phone number" errors={errors}><input {...input("phone", { type: "tel", autoComplete: "tel", maxLength: 22, placeholder: "+234 801 234 5678" })} /></Field><Field name="password" label="Create password" errors={errors} hint="At least 15 characters. Spaces and passphrases are welcome."><div className="sh-password-input"><input {...input("password", { type: showPassword ? "text" : "password", autoComplete: "new-password", maxLength: 128 })} /><button type="button" aria-label={showPassword ? "Hide password" : "Show password"} aria-pressed={showPassword} onClick={() => setShowPassword((v) => !v)}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></Field><Field name="confirmPassword" label="Confirm password" errors={errors}><input {...input("confirmPassword", { type: showPassword ? "text" : "password", autoComplete: "new-password", maxLength: 128 })} /></Field></>}
        {step === 1 && <><div className="sh-form-grid"><Field name="specialty" label="Primary specialty" errors={errors}><select {...input("specialty")}><option value="">Select specialty</option>{SPECIALTIES.map((v) => <option key={v}>{v}</option>)}</select></Field><Field name="qualification" label="Primary medical qualification" errors={errors}><select {...input("qualification")}><option value="">Select qualification</option>{["MBBS", "MBChB", "MD", "Other medical degree"].map((v) => <option key={v}>{v}</option>)}</select></Field></div>{values.qualification === "Other medical degree" && <Field name="otherQualification" label="Your medical qualification" errors={errors}><input {...input("otherQualification", { maxLength: 100 })} /></Field>}{values.specialty === "Other" && <Field name="otherSpecialty" label="Your specialty" errors={errors}><input {...input("otherSpecialty", { maxLength: 100 })} /></Field>}<div className="sh-form-grid"><Field name="university" label="Medical school / university" errors={errors}><input {...input("university", { maxLength: 200, placeholder: "Institution name" })} /></Field><Field name="graduationYear" label="Graduation year" errors={errors}><input {...input("graduationYear", { inputMode: "numeric", maxLength: 4, placeholder: "e.g. 2016" })} /></Field></div><Field name="registrationNumber" label="MDCN folio / registration number" errors={errors} hint="Enter the number shown on your MDCN registration certificate."><input {...input("registrationNumber", { maxLength: 60, placeholder: "Your registration number" })} /></Field><div className="sh-form-grid"><Field name="practiceState" label="State of practice" errors={errors}><select {...input("practiceState")}><option value="">Select state</option>{STATES.map((v) => <option key={v}>{v}</option>)}</select></Field><Field name="city" label="City / town" errors={errors}><input {...input("city", { autoComplete: "address-level2", maxLength: 100, placeholder: "e.g. Lagos" })} /></Field></div><Field name="hospital" label="Hospital / practice name (optional)" errors={errors}><input {...input("hospital", { autoComplete: "organization", maxLength: 160, placeholder: "Hospital, clinic or independent practice" })} /></Field><p className="sh-small-note">Registering here applies for a Sabi Health account. It does not replace MDCN registration or licensing.</p></>}
        {step === 2 && <><div className="sh-verification-note"><LockKeyhole size={20} /><div><strong>Help us verify your professional credentials</strong><p>Use clear, readable copies with your name and registration number visible. Sabi Health reviews these before clinical access is approved.</p></div></div><div className="sh-form-grid"><Field name="licenceType" label="Practising licence type" errors={errors}><select {...input("licenceType")}><option value="annual">Annual practising licence</option><option value="life">Life practising licence</option></select></Field>{values.licenceType === "annual" && <Field name="licenceExpiry" label="Licence expiry date" errors={errors}><input {...input("licenceExpiry", { type: "date", min: toISO(new Date()) })} /></Field>}</div>{PREVIEW_ENABLED ? <><DocumentUpload name="licence" title="Practising licence" description="Your current annual or life practising licence." file={documents.licence} error={errors.licence} onChange={chooseFile} /><DocumentUpload name="registrationCertificate" title="MDCN registration certificate" description="Your full registration certificate issued by MDCN." file={documents.registrationCertificate} error={errors.registrationCertificate} onChange={chooseFile} /></> : <div className="sh-form-notice">After creating your account, verify your email and sign in to upload your practising licence and MDCN registration certificate. Files stay private and are screened before staff can review them.</div>}</>}
        {step === 3 && <><p className="sh-review-intro">Check your information before submitting. You can edit any section.</p><section className="sh-review-section"><div><h3>Account details</h3><button type="button" onClick={() => changeStep(0)}>Edit</button></div><dl><dt>Full name</dt><dd>{values.firstName} {values.lastName}</dd><dt>Email</dt><dd>{values.email}</dd><dt>Phone</dt><dd>{values.phone}</dd><dt>Password</dt><dd>Entered securely</dd></dl></section><section className="sh-review-section"><div><h3>Professional details</h3><button type="button" onClick={() => changeStep(1)}>Edit</button></div><dl><dt>Specialty</dt><dd>{values.specialty === "Other" ? values.otherSpecialty : values.specialty}</dd><dt>Qualification</dt><dd>{values.qualification === "Other medical degree" ? values.otherQualification : values.qualification} · {values.university}, {values.graduationYear}</dd><dt>MDCN number</dt><dd>{values.registrationNumber}</dd><dt>Location</dt><dd>{values.city}, {values.practiceState}, Nigeria</dd>{values.hospital && <><dt>Practice</dt><dd>{values.hospital}</dd></>}</dl></section><section className="sh-review-section"><div><h3>Verification documents</h3><button type="button" onClick={() => changeStep(2)}>Edit</button></div><dl><dt>Practising licence</dt><dd>{documents.licence?.name || "Upload after email verification"}</dd><dt>Registration</dt><dd>{documents.registrationCertificate?.name || "Upload after email verification"}</dd>{values.licenceType === "annual" && <><dt>Licence expires</dt><dd>{values.licenceExpiry}</dd></>}</dl></section><label className="sh-consent"><input type="checkbox" checked={values.declaration} onChange={(e) => update("declaration", e.target.checked)} /><span>I confirm that my details and documents are accurate, and authorize Sabi Health to verify my professional credentials.</span></label>{errors.declaration && <p className="sh-field-error">{errors.declaration}</p>}<div className="sh-consent"><input id="termsAccepted" aria-label="Agree to Doctor Terms and acknowledge Privacy Notice" type="checkbox" checked={values.termsAccepted} onChange={(e) => update("termsAccepted", e.target.checked)} /><div><label htmlFor="termsAccepted">I agree to the </label>{policy("terms")}<span> and acknowledge the </span>{policy("privacy")}{!AUTH_CONFIGURED && <small>Preview consent only; no legal agreement is created.</small>}</div></div>{errors.termsAccepted && <p className="sh-field-error">{errors.termsAccepted}</p>}<label className="sh-consent"><input type="checkbox" checked={values.updatesOptIn} onChange={(e) => update("updatesOptIn", e.target.checked)} /><span>Send me optional product updates and practice resources.</span></label><div className="sh-next-note"><CheckCircle2 size={19} /><p>Next: verify your email, sign in to upload credentials, and submit for staff review. Approval is required before clinical access.</p></div></>}
        <div className="sh-form-actions">{step > 0 ? <button type="button" className="sh-secondary-button" disabled={busy} onClick={() => changeStep(step - 1)}><ArrowLeft size={16} /> Back</button> : <span className="sh-account-note"><LockKeyhole size={14} /> Your account starts with you.</span>}<button className="sh-primary-button" type="submit" disabled={busy || step === 3 && !PREVIEW_ENABLED && !intake.enabled}>{busy ? "Submitting…" : step === 3 ? AUTH_CONFIGURED ? "Submit registration" : "Preview submission" : "Continue"}<ArrowRight size={17} /></button></div>
      </form><div className="sh-register-bottom"><button className="sh-inline-link" onClick={saveDraft}><Save size={15} /> Save and finish later</button><span>Only verified doctors can access clinical tools.</span></div>{!AUTH_CONFIGURED && <p className="sh-preview-disclosure">Registration preview · No account is created and no verification email is sent. <Link to="/preview">Explore the portal preview</Link></p>}</div>{legal && <LegalNotice kind={legal} onClose={() => setLegal(null)} />}
  </AuthLayout>;
}
