import { defineConfig, loadEnv } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import { sabiPwaOptions } from "../shared-portal/pwa/pwaOptions.ts";

export default defineConfig(({ mode }) => {
  const { SABI_DEV_API_TARGET } = loadEnv(mode, process.cwd(), "SABI_DEV_");
  return {
    // Icons shared with the professional portal (generated by `npm run icons` at the repo root).
    publicDir: "../shared-portal/public",
    plugins: [
      react(),
      VitePWA(sabiPwaOptions({
        cacheId: "patient",
        name: "Sabi Health Patient",
        shortName: "Sabi Patient",
        description: "Book doctors, join video consultations and keep your health records in one place.",
        themeColor: "#113c30",
        backgroundColor: "#f6f7f2",
        // The professional portal is deployed inside this one.
        nestedApps: [/(?:^|\/)doctor-portal(?:\/|$)/],
        // Shows phone notifications and answers their Taken / Remind me later buttons.
        importScripts: ["push-sw.js"],
      })),
    ],
    server: SABI_DEV_API_TARGET
      ? { proxy: { "/api": { target: SABI_DEV_API_TARGET, changeOrigin: true } } }
      : undefined,
  };
});
