import React, { useEffect, useState } from "react";
import { BadgeCheck, Building2, ChevronRight, Hospital, KeyRound, Laptop, Landmark, MonitorSmartphone, Plus, ShieldCheck, SlidersHorizontal, Smartphone, TriangleAlert, Video } from "lucide-react";
import { PageTransition } from "design-system";
import PortalLayout from "../../components/PortalLayout";
import "./SettingsPage.css";

import { readDoctorStorage, writeDoctorStorage } from "../../store/scopedStore";
import { PRIMARY_DOCTOR_ID } from "../../store/doctorSession";
import { DOCTOR_PROFILE } from "../../data/doctorProfile";

const KEY = "sabi-doctor-administrative-settings";
const DEFAULTS = {
  email: DOCTOR_PROFILE.email,
  twoFactor: true,
  payout: { bank: "Chase Bank", accountMask: "••••  ••••  ••••  4829", primary: true },
  clinical: { duration: "30m", mode: "virtual" },
  sessions: [
    { id: "current", name: "MacBook Pro - Safari", detail: "Current Session", location: "New York, USA", current: true },
    { id: "phone", name: "iPhone 14 Pro - App", detail: "Last active: 2 hours ago", current: false },
  ],
  affiliations: [{ id: "mercy", initials: "MG", name: "Mercy General Hospital", detail: "Connected since Jan 2022", pendingAppointments: 14, status: "Active" }],
};
function load() { const defaults = { ...DEFAULTS, email: DOCTOR_PROFILE.email, ...(DOCTOR_PROFILE.id === PRIMARY_DOCTOR_ID ? {} : { payout: { bank: "No payout account linked", accountMask: "", primary: false }, sessions: [{ id: "current", name: "This browser", detail: "Current preview session", current: true }], affiliations: [] }) }; try { const saved = JSON.parse(readDoctorStorage(KEY)); return saved && typeof saved === "object" && !Array.isArray(saved) ? { ...defaults, ...saved, payout: { ...defaults.payout, ...saved.payout }, clinical: { ...DEFAULTS.clinical, ...saved.clinical }, sessions: Array.isArray(saved.sessions) ? saved.sessions : defaults.sessions, affiliations: Array.isArray(saved.affiliations) ? saved.affiliations : defaults.affiliations } : defaults; } catch { return defaults; } }
function Modal({ title, children, onClose, onConfirm, confirm = "Confirm", danger = false }) { return <div className="dps-modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><div className="dps-modal" role="dialog" aria-modal="true" aria-label={title}><h2>{title}</h2><div>{children}</div><footer><button className="dps-button dps-outline" onClick={onClose}>Cancel</button><button className={`dps-button ${danger ? "dps-danger" : "dps-primary"}`} onClick={onConfirm}>{confirm}</button></footer></div></div>; }
function CardTitle({ icon: Icon, title, description, action }) { return <header className="dps-card-title"><span className="dps-title-icon"><Icon /></span><div><h2>{title}</h2><p>{description}</p></div>{action}</header>; }
function Toggle({ on, onClick, label }) { return <button className={`dps-toggle ${on ? "is-on" : ""}`} onClick={onClick} aria-pressed={on} aria-label={label}><i>{on && <BadgeCheck size={29} />}</i></button>; }

export default function SettingsPage() {
  const [settings, setSettings] = useState(load); const [modal, setModal] = useState(null); const [notice, setNotice] = useState("");
  useEffect(() => { try { writeDoctorStorage(KEY, JSON.stringify(settings)); } catch { setNotice("Settings could not be saved. Please retry before leaving."); } }, [settings]);
  const notify = (message) => { setNotice(message); window.setTimeout(() => setNotice(""), 2800); };
  const updateClinical = (key, value) => setSettings((state) => ({ ...state, clinical: { ...state.clinical, [key]: value } }));
  const revoke = (id) => { setSettings((state) => ({ ...state, sessions: state.sessions.filter((session) => session.id !== id) })); setModal(null); notify("Session revoked locally."); };
  const requestRemoval = (id) => { setSettings((state) => ({ ...state, affiliations: state.affiliations.map((item) => item.id === id ? { ...item, status: "Removal requested" } : item) })); setModal(null); notify("Removal request recorded for hospital approval."); };
  const linkHospital = () => { setSettings((state) => ({ ...state, affiliations: [...state.affiliations, { id: String(Date.now()), initials: "NH", name: "New hospital connection", detail: "Awaiting hospital confirmation", pendingAppointments: 0, status: "Pending" }] })); setModal(null); notify("Hospital link request created."); };
  return <PortalLayout topbarProps={{ title: "Administrative Settings", profileMode: true }}><PageTransition className="dps-page">
    {notice && <div className="dps-notice"><BadgeCheck size={17} /> {notice}</div>}
    <section className="dps-card"><CardTitle icon={ShieldCheck} title="Account & Security" description="Manage your credentials and authentication methods." /><div className="dps-account-grid"><div><label>Registered Email</label><div className="dps-readonly">{settings.email}</div><p>Contact support to change your primary email.</p></div><div><label>Password</label><button className="dps-password" onClick={() => setModal("password")}><KeyRound size={20} /> Change Password</button></div></div><div className="dps-divider" /><div className="dps-toggle-row"><div><h3>Two-Factor Authentication (2FA)</h3><p>Require an extra security code when logging in.</p></div><Toggle on={settings.twoFactor} onClick={() => setSettings((state) => ({ ...state, twoFactor: !state.twoFactor }))} label="Two-factor authentication" /></div></section>
    <section className="dps-card"><CardTitle icon={Landmark} title="Payout Details" description="Manage where your consultation earnings are deposited." /><div className="dps-divider" /><div className="dps-payout"><span><Landmark /></span><div><h3>{settings.payout.bank}</h3><p>{settings.payout.accountMask}</p></div>{settings.payout.primary && <em>Primary</em>}</div><div className="dps-card-actions"><button className="dps-button dps-outline" onClick={() => setModal("payout")}>Change Account</button></div></section>
    <section className="dps-card"><CardTitle icon={SlidersHorizontal} title="Clinical Defaults" description="Set your standard operational preferences for new bookings." /><div className="dps-divider" /><div className="dps-defaults"><ChoiceGroup label="Default Slot Duration" values={["15m", "30m", "45m", "60m"]} selected={settings.clinical.duration} onSelect={(value) => updateClinical("duration", value)} /><ChoiceGroup label="Primary Consultation Mode" values={[{ value: "physical", label: "Physical", icon: Hospital }, { value: "virtual", label: "Virtual", icon: Video }]} selected={settings.clinical.mode} onSelect={(value) => updateClinical("mode", value)} /></div></section>
    <section className="dps-card"><CardTitle icon={MonitorSmartphone} title="Active Sessions" description="Devices currently logged into your portal." action={<button className="dps-button dps-danger" onClick={() => setModal("logout")}>Log Out Everywhere</button>} /><div className="dps-divider" /><div className="dps-sessions">{settings.sessions.map((session) => <div className="dps-session" key={session.id}>{session.current ? <Laptop /> : <Smartphone />}<div><h3>{session.name}</h3><p className={session.current ? "current" : ""}>{session.current && <i />} {session.detail}</p></div>{session.current ? <span>{session.location}</span> : <button className="dps-button dps-outline dps-small" onClick={() => setModal({ type: "revoke", id: session.id })}>Revoke</button>}</div>)}</div></section>
    <section className="dps-card"><CardTitle icon={Building2} title="Hospital Affiliations" description="Manage organizations connected to your profile." /><div className="dps-divider" /><div className="dps-affiliations">{settings.affiliations.map((hospital) => <article className="dps-affiliation" key={hospital.id}><div className="dps-hospital-main"><b>{hospital.initials}</b><div><h3>{hospital.name}</h3><p>{hospital.detail}</p></div><em className={hospital.status === "Active" ? "" : "pending"}>{hospital.status}</em></div>{hospital.pendingAppointments > 0 && <div className="dps-warning"><TriangleAlert size={19} /> You have <strong>{hospital.pendingAppointments} pending appointments</strong> scheduled here. Removing this affiliation requires hospital admin approval.</div>}<div className="dps-card-actions"><button className="dps-text-button" onClick={() => setModal({ type: "remove", id: hospital.id })}>Request Removal <ChevronRight size={18} /></button></div></article>)}</div><button className="dps-link-hospital" onClick={() => setModal("link")}><Plus size={28} /> Link New Hospital</button></section>
    {modal === "password" && <Modal title="Change password" onClose={() => setModal(null)} onConfirm={() => { setModal(null); notify("Password update must be completed through the secure account flow."); }} confirm="Continue securely"><p>This portal does not store passwords. Continue to the secure password update flow.</p></Modal>}
    {modal === "payout" && <Modal title="Change payout account" onClose={() => setModal(null)} onConfirm={() => { setModal(null); notify("Payout account setup is handled by the payment provider."); }} confirm="Continue securely"><p>To protect your financial information, bank details are collected by the connected payment provider.</p></Modal>}
    {modal === "logout" && <Modal title="Log out everywhere?" onClose={() => setModal(null)} onConfirm={() => { setSettings((state) => ({ ...state, sessions: state.sessions.filter((session) => session.current) })); setModal(null); notify("Other local sessions have been signed out."); }} confirm="Log out everywhere" danger><p>This will end all other active sessions. Your current session will remain open.</p></Modal>}
    {modal?.type === "revoke" && <Modal title="Revoke this session?" onClose={() => setModal(null)} onConfirm={() => revoke(modal.id)} confirm="Revoke session" danger><p>This device will need to sign in again to access the portal.</p></Modal>}
    {modal?.type === "remove" && <Modal title="Request hospital removal?" onClose={() => setModal(null)} onConfirm={() => requestRemoval(modal.id)} confirm="Request removal"><p>This request will require hospital administrator approval. Upcoming appointments will remain protected.</p></Modal>}
    {modal === "link" && <Modal title="Link a new hospital" onClose={() => setModal(null)} onConfirm={linkHospital} confirm="Send link request"><p>A hospital administrator will need to confirm the new affiliation.</p></Modal>}
  </PageTransition></PortalLayout>;
}
function ChoiceGroup({ label, values, selected, onSelect }) { return <div className="dps-choice-group"><label>{label}</label><div>{values.map((item) => { const option = typeof item === "string" ? { value: item, label: item } : item; const Icon = option.icon; return <button key={option.value} className={selected === option.value ? "selected" : ""} onClick={() => onSelect(option.value)}>{Icon && <Icon size={20} />}{option.label}</button>; })}</div></div>; }
