import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, FileText, ReceiptText, Search, ShieldCheck, WalletCards } from "lucide-react";
import { hasPermission } from "../access";
import { CommandButton, CommandInput, CommandPageHeader, CommandSelect, Panel, PanelHeader, StatusPill } from "../components/ui";
import { formatDate, formatMoney } from "../format";
import { useCommandCenter } from "../useCommandCenter";
import { useRegistration } from "@/registration/useRegistration";
import { useCommercialOnboarding } from "@/commercial/useCommercialOnboarding";
import type { CommercialOpportunity, PaymentPath } from "@/commercial/domain";
import type { OrganizationApplication } from "@/registration/domain";
import { useAuth } from "@/store/useAuth";

export default function CommercialOnboarding() {
  const { applicationId } = useParams();
  const navigate = useNavigate();
  const applications = useRegistration((state) => state.applications);
  const opportunities = useCommercialOnboarding((state) => state.opportunities);
  const syncApprovedApplications = useCommercialOnboarding((state) => state.syncApprovedApplications);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("ALL");
  useEffect(() => { syncApprovedApplications(); }, [applications, syncApprovedApplications]);
  const records = useMemo(() => opportunities.map((item) => ({ item, application: applications.find((entry) => entry.id === item.applicationId) })).filter((entry) => entry.application), [applications, opportunities]);
  const selected = applicationId ? records.find((entry) => entry.item.applicationId === applicationId) : undefined;
  if (applicationId && !selected) return <div><CommandPageHeader eyebrow="Commercial" title="Commercial agreement unavailable" description="Only approved organization applications can enter this pipeline."/><Link className="text-sm font-bold text-emerald-700" to="/command-center/opportunities">Back to opportunities</Link></div>;
  if (selected) return <OpportunityDetail item={selected.item} application={selected.application!}/>;
  const rows = records.filter(({ item, application }) => `${application!.reference} ${application!.organization.legalName} ${application!.organization.tradingName}`.toLowerCase().includes(query.toLowerCase()) && (status === "ALL" || item.status === status));
  return <div><CommandPageHeader eyebrow="Commercial" title="Deals & activation" description="Approved applications become versioned offers here. Active agreements are eligible for provisioning, but do not create tenants." actions={<span className="rounded-lg bg-slate-950 px-3 py-2 text-xs font-bold text-white">{rows.length} opportunities</span>}/><Panel className="mb-4"><div className="flex flex-wrap gap-2 p-3"><label className="relative min-w-[260px] flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><CommandInput className="w-full pl-9" placeholder="Organization or application reference" value={query} onChange={(event) => setQuery(event.target.value)}/></label><CommandSelect value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">All statuses</option>{["DRAFT", "QUOTED", "ACCEPTED", "PAYMENT_PENDING", "ACTIVE"].map((entry) => <option key={entry}>{entry}</option>)}</CommandSelect></div></Panel><Panel><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-slate-50"><th className="cc-th">Organization</th><th className="cc-th">Application</th><th className="cc-th">Package</th><th className="cc-th">Cycle</th><th className="cc-th">Latest quote</th><th className="cc-th">Payment</th><th className="cc-th">Status</th><th className="cc-th"></th></tr></thead><tbody>{rows.map(({ item, application }) => { const pkg = useCommandCenter.getState().packages.find((entry) => entry.id === item.packageId); const quote = [...item.quotes].sort((a, b) => b.version - a.version)[0]; return <tr className="border-t border-slate-100" key={item.id}><td className="cc-td font-semibold text-slate-900">{application!.organization.tradingName || application!.organization.legalName}</td><td className="cc-td font-mono text-xs">{application!.reference}</td><td className="cc-td">{pkg?.name}</td><td className="cc-td">{item.billingCycle}</td><td className="cc-td">{quote ? formatMoney(quote.total, quote.currency) : "Not issued"}</td><td className="cc-td"><StatusPill status={item.paymentStatus.replaceAll("_", " ")}/></td><td className="cc-td"><StatusPill status={item.status.replaceAll("_", " ")}/></td><td className="cc-td"><CommandButton variant="quiet" onClick={() => navigate(`/command-center/opportunities/${application!.id}`)}>Open</CommandButton></td></tr>; })}{rows.length === 0 && <tr><td className="p-10 text-center text-sm text-slate-500" colSpan={8}>No approved applications are waiting in the commercial pipeline.</td></tr>}</tbody></table></div></Panel></div>;
}

function OpportunityDetail({ item, application }: { item: CommercialOpportunity; application: OrganizationApplication }) {
  const commercial = useCommercialOnboarding();
  const command = useCommandCenter();
  const identity = useAuth((state) => state.identity);
  const actor = command.platformUsers.find((entry) => entry.id === identity?.platformUserId);
  const canSubscribe = hasPermission(actor, "subscriptions.manage");
  const canBill = hasPermission(actor, "billing.manage");
  const canPrice = hasPermission(actor, "pricing.manage");
  const [configuration, setConfiguration] = useState({ packageId: item.packageId, billingCycle: item.billingCycle, branchCount: item.branchCount, userCount: item.userCount, storageGb: item.storageGb, implementationAmount: item.implementationAmount });
  const [discount, setDiscount] = useState(0);
  const [validDays, setValidDays] = useState(14);
  const [paymentReference, setPaymentReference] = useState("");
  const [activationReason, setActivationReason] = useState("");
  const [message, setMessage] = useState("");
  const pkg = command.packages.find((entry) => entry.id === item.packageId);
  const version = command.packageVersions.find((entry) => entry.id === item.packageVersionId);
  const latestQuote = [...item.quotes].sort((a, b) => b.version - a.version)[0];
  const run = (action: () => { ok: true } | { ok: false; error: string }, success: string) => { const result = action(); setMessage(result.ok ? success : result.error); return result.ok; };
  return <div><Link to="/command-center/opportunities" className="mb-4 inline-flex items-center gap-2 text-xs font-bold text-slate-500 hover:text-emerald-700"><ArrowLeft size={14}/>Commercial opportunities</Link><CommandPageHeader eyebrow={application.reference} title={application.organization.tradingName || application.organization.legalName} description="Approved application · pre-provisioning commercial agreement" actions={<StatusPill status={item.status.replaceAll("_", " ")}/>}/>{message && <p role="status" className={`mb-4 rounded-xl px-4 py-3 text-sm font-semibold ${message.toLowerCase().includes("permission") || message.toLowerCase().includes("must") || message.toLowerCase().includes("cannot") || message.toLowerCase().includes("required") || message.toLowerCase().includes("unavailable") ? "bg-red-50 text-red-700" : "bg-emerald-50 text-emerald-700"}`}>{message}</p>}<div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="space-y-4">
    <Panel><PanelHeader title="Commercial configuration" description="Package versions are snapshotted into every quote."/><div className="grid gap-4 p-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Package"><CommandSelect className="w-full" disabled={!canSubscribe || !["DRAFT", "QUOTED"].includes(item.status)} value={configuration.packageId} onChange={(event) => setConfiguration((current) => ({ ...current, packageId: event.target.value }))}>{command.packages.filter((entry) => entry.active).map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</CommandSelect></Field><Field label="Billing cycle"><CommandSelect className="w-full" disabled={!canSubscribe || !["DRAFT", "QUOTED"].includes(item.status)} value={configuration.billingCycle} onChange={(event) => setConfiguration((current) => ({ ...current, billingCycle: event.target.value as "Monthly" | "Annual" }))}><option>Monthly</option><option>Annual</option></CommandSelect></Field><NumberField label="Branches" value={configuration.branchCount} disabled={!canSubscribe} onChange={(value) => setConfiguration((current) => ({ ...current, branchCount: value }))}/><NumberField label="Licensed users" value={configuration.userCount} disabled={!canSubscribe} onChange={(value) => setConfiguration((current) => ({ ...current, userCount: value }))}/><NumberField label="Storage (GB)" value={configuration.storageGb} disabled={!canSubscribe} onChange={(value) => setConfiguration((current) => ({ ...current, storageGb: value }))}/><NumberField label="Implementation fee" value={configuration.implementationAmount} disabled={!canSubscribe} onChange={(value) => setConfiguration((current) => ({ ...current, implementationAmount: value }))}/></div>{["DRAFT", "QUOTED"].includes(item.status) && <div className="border-t border-slate-100 p-4"><CommandButton disabled={!canSubscribe} onClick={() => run(() => commercial.updateConfiguration(application.id, configuration), "Commercial configuration saved. Any open quote was superseded.")}>Save configuration</CommandButton></div>}</Panel>
    <Panel><PanelHeader title="Versioned quotation" description="Published package price, capacity add-ons, authorized discount and tax."/>{latestQuote ? <div className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-sm font-bold text-slate-900">{latestQuote.number}</p><p className="mt-1 text-xs text-slate-400">Issued {formatDate(latestQuote.issuedAt)} · expires {formatDate(latestQuote.expiresAt)}</p></div><StatusPill status={latestQuote.status}/></div><div className="mt-4 divide-y divide-slate-100 rounded-lg border border-slate-200">{latestQuote.lineItems.map((line) => <div key={line.id} className="flex items-start justify-between gap-4 p-3"><div><p className="text-sm font-semibold text-slate-800">{line.label}</p><p className="text-xs text-slate-400">{line.description}</p></div><b className="text-sm">{formatMoney(line.amount, latestQuote.currency)}</b></div>)}</div><div className="ml-auto mt-4 max-w-xs space-y-2 text-sm"><MoneyRow label="Subtotal" value={latestQuote.subtotal} currency={latestQuote.currency}/><MoneyRow label={`Discount (${latestQuote.discountPercent}%)`} value={-latestQuote.discountAmount} currency={latestQuote.currency}/><MoneyRow label={`Tax (${latestQuote.taxPercent}%)`} value={latestQuote.taxAmount} currency={latestQuote.currency}/><div className="flex justify-between border-t border-slate-200 pt-2 font-bold"><span>Total</span><span>{formatMoney(latestQuote.total, latestQuote.currency)}</span></div></div></div> : <p className="p-5 text-sm text-slate-500">No quote has been issued.</p>}{["DRAFT", "QUOTED"].includes(item.status) && <div className="grid gap-3 border-t border-slate-100 p-4 sm:grid-cols-[1fr_1fr_auto]"><NumberField label="Discount %" value={discount} max={30} disabled={!canSubscribe || (!canPrice && discount > 0)} onChange={setDiscount}/><NumberField label="Valid days" value={validDays} max={90} disabled={!canSubscribe} onChange={setValidDays}/><CommandButton className="self-end" disabled={!canSubscribe || (discount > 0 && !canPrice)} onClick={() => run(() => commercial.issueQuote(application.id, discount, validDays), "A new quote version was issued to the applicant.")}><FileText size={14}/>Issue quote</CommandButton></div>}</Panel>
    <Panel><PanelHeader title="Commercial audit history"/><div className="space-y-4 p-4">{[...item.events].reverse().map((event) => <div key={event.id} className="border-l border-slate-200 pl-4"><p className="text-xs font-bold text-slate-800">{event.action}</p><p className="mt-1 text-[10px] text-slate-400">{event.actorName} · {formatDate(event.timestamp)}</p>{event.reason && <p className="mt-1 text-xs text-slate-600">{event.reason}</p>}</div>)}</div></Panel>
  </div><aside className="space-y-4"><Panel><PanelHeader title="Agreement snapshot"/><div className="space-y-3 p-4"><Snapshot label="Package" value={`${pkg?.name ?? "—"} v${version?.version ?? "—"}`}/><Snapshot label="Products" value={item.selectedProducts.join(", ")}/><Snapshot label="Capacity" value={`${item.userCount} users · ${item.branchCount} branches`}/><Snapshot label="Storage" value={`${item.storageGb} GB`}/><Snapshot label="Billing" value={item.billingCycle}/></div></Panel><Panel><PanelHeader title="Acceptance & payment"/><div className="space-y-3 p-4"><Snapshot label="Quote" value={latestQuote?.status ?? "Not issued"}/><Snapshot label="Payment path" value={item.paymentPath?.replace("_", " ") ?? "Not selected"}/><Snapshot label="Payment" value={item.paymentStatus.replace("_", " ")}/>{item.status === "ACCEPTED" && <div><span className="cc-label">Activation path</span><div className="grid gap-2">{(["TRIAL", "INVOICE", "MANUAL_TRANSFER"] as PaymentPath[]).map((path) => <CommandButton key={path} variant="secondary" disabled={!canBill} onClick={() => run(() => commercial.selectPaymentPath(application.id, path), `${path.replace("_", " ")} activation path selected.`)}>{path.replace("_", " ")}</CommandButton>)}</div></div>}{item.status === "PAYMENT_PENDING" && item.paymentStatus === "PENDING" && <div className="space-y-2"><CommandInput className="w-full" placeholder="Invoice or payment reference" value={paymentReference} onChange={(event) => setPaymentReference(event.target.value)}/><CommandButton className="w-full" disabled={!canBill} onClick={() => run(() => commercial.confirmPayment(application.id, paymentReference), "Payment authorization confirmed.")}><ReceiptText size={14}/>Confirm payment</CommandButton></div>}<textarea className="min-h-20 w-full rounded-lg border border-slate-200 p-3 text-sm outline-none focus:border-emerald-500" disabled={item.status !== "PAYMENT_PENDING"} placeholder="Mandatory activation rationale" value={activationReason} onChange={(event) => setActivationReason(event.target.value)}/><CommandButton className="w-full" disabled={!canSubscribe || !canBill || item.status !== "PAYMENT_PENDING" || !["CONFIRMED", "WAIVED"].includes(item.paymentStatus)} onClick={() => run(() => commercial.activateCommercialAgreement(application.id, activationReason), "Commercial agreement activated for the provisioning queue. No tenant was created.")}><ShieldCheck size={14}/>Activate agreement</CommandButton></div></Panel><div className="rounded-xl bg-slate-950 p-4 text-xs leading-5 text-white/60"><WalletCards className="mb-3 text-emerald-300" size={18}/><b className="block text-white">Provisioning boundary</b>An ACTIVE agreement is only an authorized input for Phase 8. This screen cannot create an organization, membership, license, entitlement or tenant.</div></aside></div></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="cc-label">{label}</span>{children}</label>; }
function NumberField({ label, value, onChange, disabled, max }: { label: string; value: number; onChange: (value: number) => void; disabled?: boolean; max?: number }) { return <Field label={label}><CommandInput className="w-full" type="number" min={0} max={max} disabled={disabled} value={value} onChange={(event) => onChange(Number(event.target.value))}/></Field>; }
function Snapshot({ label, value }: { label: string; value: string }) { return <div className="flex items-start justify-between gap-4 text-xs"><span className="text-slate-400">{label}</span><b className="text-right text-slate-700">{value}</b></div>; }
function MoneyRow({ label, value, currency }: { label: string; value: number; currency: string }) { return <div className="flex justify-between"><span className="text-slate-500">{label}</span><span>{formatMoney(value, currency)}</span></div>; }
