import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Activity, AlertTriangle, Check, Flag, Globe2, LockKeyhole, Paintbrush, Play, Plus, RefreshCw, Search, ServerCog, ShieldCheck, SlidersHorizontal, X } from "lucide-react";
import { Bars, Lines } from "@/components/ui/Chart";
import { useAuth } from "@/store/useAuth";
import { MODULES, PRODUCTS, type ProductKey } from "@/platform/entitlements";
import { resolveEntitlements } from "../resolver";
import { useCommandCenter } from "../useCommandCenter";
import { CommandButton, CommandInput, CommandPageHeader, CommandSelect, Panel, PanelHeader, StatusPill } from "../components/ui";
import { formatDate } from "../format";

export type PlatformOpsKind = "entitlements" | "feature-flags" | "integrations" | "notifications" | "analytics" | "health" | "incidents" | "jobs" | "audit" | "branding" | "themes" | "terminology" | "security" | "settings";

function downloadCsv(filename: string, rows: (string | number | undefined)[][]) {
  const csv = rows.map((row) => row.map((value) => `"${String(value ?? "").replace(/"/g, '""')}"`).join(",")).join("\n");
  const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
  const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url);
}

export default function PlatformOpsPage({ kind }: { kind: PlatformOpsKind }) {
  if (kind === "entitlements") return <Entitlements />;
  if (kind === "feature-flags") return <FeatureFlags />;
  if (kind === "integrations") return <Integrations />;
  if (kind === "notifications") return <Notifications />;
  if (kind === "analytics") return <Analytics />;
  if (kind === "health") return <Health />;
  if (kind === "incidents") return <Incidents />;
  if (kind === "jobs") return <Jobs />;
  if (kind === "audit") return <Audit />;
  if (kind === "branding" || kind === "themes") return <Branding title={kind === "themes" ? "Theme management" : "Branding & appearance"} />;
  if (kind === "terminology") return <Terminology />;
  if (kind === "security") return <Security />;
  return <GlobalSettings />;
}

function Entitlements() {
  const state = useCommandCenter(); const navigate = useNavigate(); const [selected, setSelected] = useState(state.organizations[0].id);
  const sub = state.subscriptions.find((s) => s.organizationId === selected); const license = state.licenses.find((l) => l.organizationId === selected);
  const resolved = sub && license ? resolveEntitlements(selected, sub, license, state.entitlements) : undefined;
  return <div><CommandPageHeader eyebrow="Platform" title="Entitlements" description="One resolved view across package snapshots, add-ons, overrides, temporary grants and revocations." actions={<CommandButton onClick={() => navigate(`/command-center/organizations/${selected}?tab=Products+%26+Modules`)}>Manage tenant <span aria-hidden>→</span></CommandButton>} /><div className="mb-3 flex flex-wrap items-center gap-2"><CommandSelect className="min-w-72" value={selected} onChange={(e) => setSelected(e.target.value)}>{state.organizations.map((o) => <option key={o.id} value={o.id}>{o.name} · {o.tenantId}</option>)}</CommandSelect>{resolved && <><StatusPill status={resolved.subscriptionStatus} /><StatusPill status={resolved.licenseStatus} /></>}</div>{resolved ? <div className="grid gap-4 lg:grid-cols-3">{(Object.keys(PRODUCTS) as ProductKey[]).map((key) => <Panel key={key}><PanelHeader title={PRODUCTS[key].label} action={<StatusPill status={resolved.products[key] ? "Licensed" : "Unavailable"} />} /><div className="divide-y divide-slate-100">{MODULES.filter((m) => m.product === key).map((module) => <div key={module.key} className="flex items-center gap-2 px-4 py-2.5"><span className={`grid h-6 w-6 place-items-center rounded-md ${resolved.modules[module.key] ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-400"}`}>{resolved.modules[module.key] ? <Check size={13} /> : <X size={13} />}</span><div className="min-w-0"><p className="truncate text-xs font-semibold text-slate-800">{module.label}</p><p className="truncate font-mono text-[9px] text-slate-400">{module.key}</p></div></div>)}</div></Panel>)}</div> : <Panel className="p-10 text-center text-sm text-slate-500">This organization has no resolvable subscription.</Panel>}</div>;
}

function FeatureFlags() {
  const state = useCommandCenter();
  const actorId = useAuth((s) => s.identity?.platformUserId) ?? state.platformUsers[0].id;
  const create = () => { const name = window.prompt("Feature flag name"); if (!name) return; const key = window.prompt("Unique flag key", name.toLowerCase().replace(/\s+/g, ".")); if (!key) return; const description = window.prompt("Description"); if (!description) return; const result = state.createFeatureFlag(name, key, description, actorId); window.alert(result.ok ? "Feature flag created as Draft." : result.error); };
  return <div><CommandPageHeader eyebrow="Platform" title="Feature flags" description="Safely target experiences without tenant-specific redeployments." actions={<CommandButton onClick={create}><Plus size={15} /> Create flag</CommandButton>} /><div className="grid gap-3 lg:grid-cols-2">{state.featureFlags.map((flag) => <Panel key={flag.id}><div className="p-4"><div className="flex items-start gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-slate-100 text-slate-600"><Flag size={17} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-bold text-slate-900">{flag.name}</h2><StatusPill status={flag.status} /></div><code className="text-[10px] text-slate-400">{flag.key}</code><p className="mt-2 text-xs leading-5 text-slate-500">{flag.description}</p></div><button onClick={() => state.toggleFeatureFlag(flag.id)} className={`relative h-6 w-11 rounded-full ${flag.status === "Enabled" ? "bg-emerald-500" : "bg-slate-300"}`} aria-label={`Toggle ${flag.name}`}><span className={`absolute top-0.5 h-5 w-5 rounded-full bg-white shadow ${flag.status === "Enabled" ? "left-[22px]" : "left-0.5"}`} /></button></div><div className="mt-4 flex flex-wrap gap-2 border-t border-slate-100 pt-3">{flag.targets.map((target, i) => <span key={i} className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold text-slate-600">{target.type}: {target.ids.length ? target.ids.join(", ") : "all"}</span>)}</div></div></Panel>)}</div></div>;
}

function Integrations() {
  const state = useCommandCenter(); const [status, setStatus] = useState("All");
  const actorId = useAuth((s) => s.identity?.platformUserId) ?? state.platformUsers[0].id;
  const add = () => { const provider = window.prompt("Provider name"); if (!provider) return; const category = window.prompt("Category", "Data exchange"); if (!category) return; const organizationId = window.prompt("Organization ID", state.organizations[0]?.id); if (!organizationId) return; const environment = window.confirm("Use Production? Choose Cancel for Sandbox.") ? "Production" : "Sandbox"; const result = state.addIntegration({ organizationId, provider, category, environment }, actorId); window.alert(result.ok ? "Integration configuration created." : result.error); };
  const rows = state.integrations.filter((i) => status === "All" || i.status === status);
  return <div><CommandPageHeader eyebrow="Platform" title="Integrations" description="Tenant-scoped provider health with masked credentials and sync history." actions={<CommandButton onClick={add}><Plus size={15} /> Add integration</CommandButton>} /><div className="mb-3 flex gap-2"><CommandSelect value={status} onChange={(e) => setStatus(e.target.value)}><option>All</option>{[...new Set(state.integrations.map((i) => i.status))].map((s) => <option key={s}>{s}</option>)}</CommandSelect><span className="self-center text-xs text-slate-400">{rows.reduce((n, i) => n + i.errorCount, 0)} recorded errors</span></div><Panel><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-slate-50"><th className="cc-th">Organization</th><th className="cc-th">Provider</th><th className="cc-th">Category</th><th className="cc-th">Environment</th><th className="cc-th">Credential</th><th className="cc-th">Last sync</th><th className="cc-th">Last success</th><th className="cc-th">Errors</th><th className="cc-th">Last error</th><th className="cc-th">Status</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t border-slate-100"><td className="cc-td font-semibold text-slate-900">{state.organizations.find((o) => o.id === row.organizationId)?.name}</td><td className="cc-td font-semibold">{row.provider}</td><td className="cc-td">{row.category}</td><td className="cc-td">{row.environment}</td><td className="cc-td font-mono text-xs">{row.maskedCredential}</td><td className="cc-td">{formatDate(row.lastSyncAt)}</td><td className="cc-td">{formatDate(row.lastSuccessfulSyncAt)}</td><td className="cc-td">{row.errorCount}</td><td className="cc-td max-w-xs truncate text-red-600">{row.lastError}</td><td className="cc-td"><StatusPill status={row.status} /></td></tr>)}</tbody></table></div></Panel></div>;
}

function Notifications() {
  const state = useCommandCenter(); const [selected, setSelected] = useState(state.notificationTemplates[0]?.id); const template = state.notificationTemplates.find((t) => t.id === selected)!;
  const actorId = useAuth((s) => s.identity?.platformUserId) ?? state.platformUsers[0].id;
  const create = () => { const name = window.prompt("Template name"); if (!name) return; const key = window.prompt("Unique template key", name.toLowerCase().replace(/\s+/g, ".")); if (!key) return; const result = state.createNotificationTemplate(name, key, actorId); if (result.ok) setSelected(result.id); window.alert(result.ok ? "Notification template created." : result.error); };
  const save = () => { const subject = window.prompt("Subject", template.subject); if (subject === null) return; const body = window.prompt("Message", template.body); if (body === null) return; const result = state.updateNotificationTemplate(template.id, { subject, body, channels: template.channels }, actorId); window.alert(result.ok ? "Notification template saved and activated." : result.error); };
  return <div><CommandPageHeader eyebrow="Platform" title="Notification templates" description="Multi-channel operational messages with governed variables." actions={<CommandButton onClick={create}><Plus size={15} /> New template</CommandButton>} /><div className="grid gap-4 lg:grid-cols-[340px_1fr]"><Panel><PanelHeader title="Templates" /><div className="divide-y divide-slate-100">{state.notificationTemplates.map((item) => <button key={item.id} onClick={() => setSelected(item.id)} className={`w-full p-4 text-left ${item.id === selected ? "bg-emerald-50" : "hover:bg-slate-50"}`}><div className="flex items-center justify-between"><p className="text-sm font-bold">{item.name}</p><StatusPill status={item.status} /></div><p className="mt-1 text-xs text-slate-400">{item.channels.join(" · ")}</p></button>)}</div></Panel><Panel><PanelHeader title={template.name} action={<CommandButton onClick={save}>Save template</CommandButton>} /><div className="space-y-4 p-4"><label className="block"><span className="cc-label">Subject</span><CommandInput className="w-full" defaultValue={template.subject} /></label><label className="block"><span className="cc-label">Message</span><textarea className="min-h-40 w-full rounded-lg border border-slate-200 p-3 text-sm outline-none focus:border-emerald-500" defaultValue={template.body} /></label><div><span className="cc-label">Channels</span><div className="flex flex-wrap gap-2">{["Email", "SMS", "In-app", "Push", "WhatsApp"].map((channel) => <label key={channel} className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold"><input type="checkbox" defaultChecked={template.channels.includes(channel as never)} />{channel}</label>)}</div></div><div><span className="cc-label">Available variables</span><div className="flex flex-wrap gap-2">{template.variables.map((v) => <code key={v} className="rounded bg-slate-100 px-2 py-1 text-xs">{`{{${v}}}`}</code>)}</div></div></div></Panel></div></div>;
}

function Analytics() {
  const state = useCommandCenter(); const [tenant, setTenant] = useState("All");
  const orgs = tenant === "All" ? state.organizations.filter((o) => o.activeUsers) : state.organizations.filter((o) => o.id === tenant);
  const rows = orgs.map((o) => { const find = (metric: string) => state.usage.find((u) => u.organizationId === o.id && u.metric === metric)?.value ?? 0; return { name: o.name.split(" ").slice(0, 2).join(" "), dau: find("DAU"), wau: find("WAU"), mau: find("MAU"), sessions: find("Sessions"), encounters: find("Encounters"), storage: find("Storage GB") }; });
  return <div><CommandPageHeader eyebrow="Operations" title="Usage & adoption analytics" description="Operational aggregates only—no patient records or unnecessary clinical PHI." actions={<CommandSelect value={tenant} onChange={(e) => setTenant(e.target.value)}><option>All</option>{state.organizations.map((o) => <option key={o.id} value={o.id}>{o.name}</option>)}</CommandSelect>} /><div className="grid gap-4 lg:grid-cols-2"><Panel><PanelHeader title="Active users by tenant" /><div className="p-3"><Bars data={rows} x="name" series={[{ key: "dau", label: "DAU", color: "#10b981" }, { key: "mau", label: "MAU", color: "#0f172a" }]} height={270} /></div></Panel><Panel><PanelHeader title="Sessions & encounters" /><div className="p-3"><Lines data={rows} x="name" series={[{ key: "sessions", label: "Sessions", color: "#0ea5e9" }, { key: "encounters", label: "Encounters", color: "#8b5cf6" }]} height={270} /></div></Panel></div><Panel className="mt-4"><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-slate-50"><th className="cc-th">Tenant</th><th className="cc-th">DAU</th><th className="cc-th">WAU</th><th className="cc-th">MAU</th><th className="cc-th">Sessions</th><th className="cc-th">Encounters</th><th className="cc-th">Storage</th><th className="cc-th">DAU / MAU</th></tr></thead><tbody>{rows.map((row) => <tr key={row.name} className="border-t border-slate-100"><td className="cc-td font-semibold text-slate-900">{row.name}</td><td className="cc-td">{row.dau}</td><td className="cc-td">{row.wau}</td><td className="cc-td">{row.mau}</td><td className="cc-td">{row.sessions}</td><td className="cc-td">{row.encounters}</td><td className="cc-td">{row.storage} GB</td><td className="cc-td font-semibold">{row.mau ? Math.round(row.dau / row.mau * 100) : 0}%</td></tr>)}</tbody></table></div></Panel></div>;
}

function Health() {
  const state = useCommandCenter(); const counts = state.serviceHealth.reduce<Record<string, number>>((a, s) => ({ ...a, [s.status]: (a[s.status] ?? 0) + 1 }), {});
  const actorId = useAuth((s) => s.identity?.platformUserId) ?? state.platformUsers[0].id;
  return <div><CommandPageHeader eyebrow="Operations" title="Platform operations" description="Service availability, latency and incident posture across the Sabi ecosystem." actions={<CommandButton variant="secondary" onClick={() => state.refreshServiceHealth(actorId)}><RefreshCw size={15} /> Refresh health</CommandButton>} /><div className="mb-4 rounded-xl bg-slate-950 p-5 text-white"><div className="flex flex-wrap items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-xl bg-amber-400/15 text-amber-300"><Activity size={22} /></span><div><p className="font-display text-xl font-bold">Minor service degradation</p><p className="mt-1 text-sm text-slate-400">Core clinical services are operational. SMS delivery latency is elevated.</p></div><div className="ml-auto text-right"><p className="text-xs text-slate-500">Last checked</p><p className="text-sm font-semibold">{formatDate(state.serviceHealth[0]?.lastCheckedAt)}</p></div></div></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{state.serviceHealth.map((service) => <Panel key={service.id}><div className="p-4"><div className="flex items-center justify-between"><span className={`h-2.5 w-2.5 rounded-full ${service.status === "Operational" ? "bg-emerald-500" : service.status === "Maintenance" ? "bg-blue-500" : "bg-amber-500"}`} /><StatusPill status={service.status} /></div><p className="mt-4 text-sm font-bold text-slate-900">{service.name}</p><div className="mt-3 flex items-end justify-between"><span><span className="block font-display text-lg font-bold">{service.availability}%</span><span className="text-[10px] text-slate-400">30-day availability</span></span><span className="text-right"><span className="block text-sm font-semibold">{service.latencyMs || "—"}{service.latencyMs ? " ms" : ""}</span><span className="text-[10px] text-slate-400">latency</span></span></div></div></Panel>)}</div><p className="mt-3 text-xs text-slate-400">{counts.Operational ?? 0} operational · {counts.Degraded ?? 0} degraded · {counts.Maintenance ?? 0} in maintenance</p></div>;
}

function Incidents() {
  const state = useCommandCenter();
  const actorId = useAuth((s) => s.identity?.platformUserId) ?? state.platformUsers[0].id;
  const declare = () => { const title = window.prompt("Incident title"); if (!title) return; const service = window.prompt("Affected service", "Sabi OS API"); if (!service) return; const severity = (window.prompt("Severity: Minor, Major, or Critical", "Minor") ?? "Minor") as "Minor" | "Major" | "Critical"; const result = state.declareIncident(title, service, severity, actorId); window.alert(result.ok ? "Incident declared and audit event created." : result.error); };
  return <div><CommandPageHeader eyebrow="Operations" title="Incidents" description="Incident response history and active communications." actions={<CommandButton onClick={declare}><Plus size={15} /> Declare incident</CommandButton>} /><Panel><div className="divide-y divide-slate-100">{state.incidents.map((incident) => <div key={incident.id} className="grid gap-3 p-4 md:grid-cols-[42px_1fr_160px_120px_130px]"><span className={`grid h-9 w-9 place-items-center rounded-lg ${incident.severity === "Major" || incident.severity === "Critical" ? "bg-red-50 text-red-600" : "bg-amber-50 text-amber-600"}`}><AlertTriangle size={17} /></span><div><p className="text-sm font-bold text-slate-900">{incident.title}</p><p className="text-xs text-slate-400">{incident.id} · {incident.service}</p></div><span className="text-xs text-slate-500">Started {formatDate(incident.startedAt)}</span><StatusPill status={incident.severity} /><StatusPill status={incident.status} /></div>)}</div></Panel></div>;
}

function Jobs() {
  const state = useCommandCenter(); const actorId = useAuth((s) => s.identity?.platformUserId) ?? state.platformUsers[0].id; const [refreshedAt, setRefreshedAt] = useState(""); const jobs = state.integrations.slice(0, 9).map((integration, i) => ({ id: `job-${i + 1}`, integrationId: integration.id, name: `${integration.provider} ${integration.category} sync`, tenant: state.organizations.find((o) => o.id === integration.organizationId)?.name, schedule: i % 2 ? "Every 15 min" : "Hourly", lastRun: integration.lastSyncAt, duration: `${18 + i * 3}s`, retries: integration.errorCount, status: integration.status === "Error" ? "Failed" : "Succeeded" }));
  return <div><CommandPageHeader eyebrow="Operations" title="Jobs & sync" description={`Scheduled workers, integration syncs and retry posture.${refreshedAt ? ` Refreshed ${formatDate(refreshedAt)}.` : ""}`} actions={<CommandButton variant="secondary" onClick={() => setRefreshedAt(new Date().toISOString())}><RefreshCw size={15} /> Refresh</CommandButton>} /><Panel><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-slate-50"><th className="cc-th">Job</th><th className="cc-th">Tenant</th><th className="cc-th">Schedule</th><th className="cc-th">Last run</th><th className="cc-th">Duration</th><th className="cc-th">Retries</th><th className="cc-th">Status</th><th className="cc-th"></th></tr></thead><tbody>{jobs.map((job) => <tr key={job.id} className="border-t border-slate-100"><td className="cc-td"><span className="block font-semibold text-slate-900">{job.name}</span><span className="font-mono text-[10px] text-slate-400">{job.id}</span></td><td className="cc-td">{job.tenant}</td><td className="cc-td">{job.schedule}</td><td className="cc-td">{formatDate(job.lastRun)}</td><td className="cc-td">{job.duration}</td><td className="cc-td">{job.retries}</td><td className="cc-td"><StatusPill status={job.status} /></td><td className="cc-td"><CommandButton variant="quiet" onClick={() => { const result = state.runIntegrationJob(job.integrationId, actorId); window.alert(result.ok ? "Job completed successfully." : result.error); }}><Play size={14} /> Run now</CommandButton></td></tr>)}</tbody></table></div></Panel></div>;
}

function Audit() {
  const state = useCommandCenter(); const [query, setQuery] = useState("");
  const events = state.auditEvents.filter((event) => `${event.actorName} ${event.action} ${event.resourceType} ${event.reason ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  const exportEvidence = () => downloadCsv(`sabi-command-center-audit-${new Date().toISOString().slice(0, 10)}.csv`, [["Timestamp", "Actor", "Role", "Organization", "Action", "Resource type", "Resource ID", "Reason", "Correlation ID"], ...events.map((event) => [event.timestamp, event.actorName, event.actorRole, state.organizations.find((item) => item.id === event.organizationId)?.name, event.action, event.resourceType, event.resourceId, event.reason, event.correlationId])]);
  return <div><CommandPageHeader eyebrow="Operations" title="Platform audit log" description="Immutable administration events with actors, before/after context and correlation IDs." actions={<CommandButton variant="secondary" onClick={exportEvidence}>Export audit evidence</CommandButton>} /><Panel><div className="border-b border-slate-100 p-3"><div className="relative max-w-md"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><CommandInput className="w-full pl-9" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Actor, action, resource or reason" /></div></div><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-slate-50"><th className="cc-th">Timestamp</th><th className="cc-th">Actor</th><th className="cc-th">Role</th><th className="cc-th">Organization</th><th className="cc-th">Action</th><th className="cc-th">Resource</th><th className="cc-th">Reason</th><th className="cc-th">Correlation ID</th><th className="cc-th">IP / device</th></tr></thead><tbody>{events.map((event) => <tr key={event.id} className="border-t border-slate-100"><td className="cc-td">{formatDate(event.timestamp)}</td><td className="cc-td font-semibold text-slate-900">{event.actorName}</td><td className="cc-td">{event.actorRole}</td><td className="cc-td">{state.organizations.find((o) => o.id === event.organizationId)?.name ?? "Platform"}</td><td className="cc-td font-semibold">{event.action}</td><td className="cc-td font-mono text-xs">{event.resourceType}/{event.resourceId}</td><td className="cc-td max-w-xs whitespace-normal">{event.reason}</td><td className="cc-td font-mono text-xs">{event.correlationId}</td><td className="cc-td"><span className="block">{event.ipAddress ?? "Backend field"}</span><span className="text-xs text-slate-400">{event.userAgent ?? "User agent placeholder"}</span></td></tr>)}</tbody></table></div></Panel></div>;
}

function Branding({ title }: { title: string }) {
  const state = useCommandCenter(); const navigate = useNavigate(); const [selected, setSelected] = useState(state.organizations[0].id); const theme = state.themes.find((t) => t.organizationId === selected)!;
  return <div><CommandPageHeader eyebrow="Customization" title={title} description="Global defaults with tenant overrides and user preferences layered at runtime." actions={<CommandButton onClick={() => navigate(`/command-center/organizations/${selected}?tab=Branding+%26+Security`)}>Open live editor</CommandButton>} /><div className="mb-3"><CommandSelect className="min-w-80" value={selected} onChange={(e) => setSelected(e.target.value)}>{state.organizations.map((o) => <option value={o.id} key={o.id}>{o.name}</option>)}</CommandSelect></div><div className="grid gap-4 lg:grid-cols-[.7fr_1.3fr]"><Panel><PanelHeader title="Theme tokens" /><div className="grid grid-cols-2 gap-3 p-4">{Object.entries(theme.colors).map(([key, value]) => <div key={key} className="rounded-lg border border-slate-200 p-3"><div className="h-12 rounded-md" style={{ backgroundColor: value }} /><p className="mt-2 text-xs font-bold capitalize">{key}</p><code className="text-[10px] text-slate-400">{value}</code></div>)}</div></Panel><Panel><PanelHeader title="Tenant preview" /><div className="m-5 overflow-hidden rounded-xl border border-slate-200 shadow-xl"><div className="flex h-[430px]"><div className="w-44 p-4 text-white" style={{ background: theme.colors.sidebar }}><div className="mb-8 flex items-center gap-2 font-bold"><span className="grid h-8 w-8 place-items-center rounded-lg" style={{ background: theme.colors.primary }}><Paintbrush size={15} /></span><span className="truncate text-xs">{theme.productDisplayName}</span></div>{["Dashboard", "Clinical", "Laboratory", "Pharmacy", "Billing", "Reports"].map((item, i) => <div key={item} className="mb-1 rounded-lg px-3 py-2 text-xs" style={i === 0 ? { background: theme.colors.primary } : { opacity: .65 }}>{item}</div>)}</div><div className="flex-1" style={{ background: theme.colors.background }}><div className="h-14 border-b bg-white px-5 py-4 text-sm font-bold">{theme.organizationDisplayName}</div><div className="p-5"><h3 className="font-display text-lg font-bold">Facility dashboard</h3><div className="mt-4 grid grid-cols-3 gap-3">{[23, 48, 12].map((x, i) => <div key={i} className="rounded-xl bg-white p-4 shadow-sm"><p className="text-xs text-slate-400">{["Queue", "Appointments", "Admissions"][i]}</p><p className="mt-2 text-2xl font-bold" style={{ color: i === 0 ? theme.colors.primary : "#0f172a" }}>{x}</p></div>)}</div><div className="mt-4 h-36 rounded-xl bg-white p-4"><div className="h-2 w-28 rounded" style={{ background: theme.colors.primary }} /><div className="mt-5 space-y-3">{[90, 70, 82].map((w) => <div className="h-2 rounded bg-slate-100" style={{ width: `${w}%` }} key={w} />)}</div></div></div></div></div></div></Panel></div></div>;
}

function Terminology() { const state = useCommandCenter(); const actorId = useAuth((s) => s.identity?.platformUserId) ?? state.platformUsers[0].id; const defaults = { Organization: "Hospital", Branch: "Facility", Department: "Unit", Patient: "Client", Employee: "Staff member", Product: "Sabi application" }; const [terms, setTerms] = useState({ ...defaults, ...(state.platformSettings.terminology ?? {}) }); const save = () => { const result = state.savePlatformSettings("terminology", terms, actorId); window.alert(result.ok ? "Terminology saved." : result.error); }; return <div><CommandPageHeader eyebrow="Customization" title="Terminology" description="Platform defaults that tenants may override without changing domain identifiers." actions={<CommandButton onClick={save}>Save terminology</CommandButton>} /><Panel><PanelHeader title="Global terminology defaults" /><div className="grid gap-4 p-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(terms).map(([key, value]) => <label key={key}><span className="cc-label">{key}</span><CommandInput className="w-full" value={value} onChange={(event) => setTerms((current) => ({ ...current, [key]: event.target.value }))} /></label>)}</div></Panel></div>; }

function Security() { const state = useCommandCenter(); const actorId = useAuth((s) => s.identity?.platformUserId) ?? state.platformUsers[0].id; const save = () => { const result = state.savePlatformSettings("security", { platformMfa: "Required", supportApproval: "Required", sessionLifetime: "8 hours", tenantIsolation: "Enforced", auditRetention: "7 years" }, actorId); window.alert(result.ok ? "Security policy saved." : result.error); }; return <div><CommandPageHeader eyebrow="Administration" title="Security" description="Central policy posture for Sabi internal identities and tenant enforcement." actions={<CommandButton onClick={save}>Save security policy</CommandButton>} /><div className="grid gap-4 lg:grid-cols-3">{[["Platform MFA", "Required", "All Sabi internal users must enroll in a phishing-resistant second factor."], ["Support access approval", "Required", "Security approval is required for sessions over one hour."], ["Session lifetime", "8 hours", "Refresh and device policy are enforced by the identity backend."], ["Tenant isolation", "Enforced", "Every backend resource query is scoped to organization membership."], ["Audit retention", "7 years", "Sensitive platform administration events are immutable."], ["Emergency access", "Policy-ready", "Clinical read-only exception policy remains separately configurable."]].map(([title, status, detail]) => <Panel key={title}><div className="p-4"><div className="flex items-center justify-between"><span className="grid h-8 w-8 place-items-center rounded-lg bg-slate-100 text-emerald-700"><ShieldCheck size={16} /></span><StatusPill status={status} /></div><h2 className="mt-4 text-sm font-bold">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></div></Panel>)}</div></div>; }

function GlobalSettings() { const state = useCommandCenter(); const actorId = useAuth((s) => s.identity?.platformUserId) ?? state.platformUsers[0].id; const values = { timezone: "Africa/Lagos", locale: "en-NG", currency: "NGN", dateFormat: "DD MMM YYYY", sessionTimeout: "30 minutes", retention: "7 years", gracePeriod: "14 days", theme: "Light" }; const save = () => { const result = state.savePlatformSettings("global", values, actorId); window.alert(result.ok ? "Global settings saved." : result.error); }; return <div><CommandPageHeader eyebrow="Administration" title="Global settings" description="Platform defaults; organization-specific overrides are managed from Tenant 360." actions={<CommandButton onClick={save}>Save settings</CommandButton>} /><div className="grid gap-4 lg:grid-cols-2"><SettingsPanel title="Regional defaults" icon={<Globe2 size={17} />} fields={[["Default timezone", values.timezone], ["Locale", values.locale], ["Currency", values.currency], ["Date format", values.dateFormat]]} /><SettingsPanel title="Tenant policy defaults" icon={<SlidersHorizontal size={17} />} fields={[["Session timeout", values.sessionTimeout], ["Data retention", values.retention], ["Grace period", values.gracePeriod], ["Default theme", values.theme]]} /><SettingsPanel title="Platform endpoints" icon={<ServerCog size={17} />} fields={[["Identity issuer", "https://identity.sabios.com"], ["Command Center", "https://command.sabios.com"], ["Tenant pattern", "https://{tenant}.sabios.com"], ["API version", "v1"]]} /><SettingsPanel title="Security contacts" icon={<LockKeyhole size={17} />} fields={[["Support", "support@sabios.com"], ["Security", "security@sabios.com"], ["Privacy", "privacy@sabios.com"], ["Incident response", "oncall@sabios.com"]]} /></div></div>; }
function SettingsPanel({ title, icon, fields }: { title: string; icon: React.ReactNode; fields: string[][] }) { return <Panel><PanelHeader title={title} action={<span className="text-emerald-600">{icon}</span>} /><div className="grid gap-4 p-4 sm:grid-cols-2">{fields.map(([label, value]) => <label key={label}><span className="cc-label">{label}</span><CommandInput className="w-full" defaultValue={value} /></label>)}</div></Panel>; }
