import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, Building2, CheckCircle2, CircleAlert, Clock3, Play, RefreshCw, Search, ServerCog } from "lucide-react";
import { hasPermission } from "../access";
import { CommandButton, CommandInput, CommandPageHeader, CommandSelect, Panel, PanelHeader, StatusPill } from "../components/ui";
import { formatDate } from "../format";
import { useCommandCenter } from "../useCommandCenter";
import { useCommercialOnboarding } from "@/commercial/useCommercialOnboarding";
import { useTenantProvisioning } from "@/provisioning/useTenantProvisioning";
import type { TenantProvisioningJob } from "@/provisioning/domain";
import { useRegistration } from "@/registration/useRegistration";
import type { OrganizationApplication } from "@/registration/domain";
import { useAuth } from "@/store/useAuth";

export default function TenantProvisioning() {
  const { applicationId } = useParams();
  const navigate = useNavigate();
  const applications = useRegistration((state) => state.applications);
  const agreements = useCommercialOnboarding((state) => state.opportunities);
  const jobs = useTenantProvisioning((state) => state.jobs);
  const syncActiveAgreements = useTenantProvisioning((state) => state.syncActiveAgreements);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("ALL");
  useEffect(() => { syncActiveAgreements(); }, [agreements, applications, syncActiveAgreements]);
  const records = useMemo(() => jobs.map((job) => ({ job, application: applications.find((item) => item.id === job.applicationId) })).filter((entry) => entry.application), [applications, jobs]);
  const selected = applicationId ? records.find((entry) => entry.job.applicationId === applicationId) : undefined;
  if (applicationId && !selected) return <div><CommandPageHeader eyebrow="Customers" title="Provisioning job unavailable" description="Only active commercial agreements can enter tenant provisioning."/><Link className="text-sm font-bold text-emerald-700" to="/command-center/provisioning">Back to provisioning queue</Link></div>;
  if (selected) return <ProvisioningDetail job={selected.job} application={selected.application!}/>;
  const rows = records.filter(({ job, application }) => `${application!.reference} ${application!.organization.legalName} ${application!.organization.tradingName}`.toLowerCase().includes(query.toLowerCase()) && (status === "ALL" || job.status === status));
  return <div><CommandPageHeader eyebrow="Customers" title="Tenant provisioning" description="Idempotent creation of isolated onboarding tenants from active commercial agreements." actions={<span className="rounded-lg bg-slate-950 px-3 py-2 text-xs font-bold text-white">{rows.length} jobs</span>}/><Panel className="mb-4"><div className="flex flex-wrap gap-2 p-3"><label className="relative min-w-[260px] flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><CommandInput className="w-full pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Organization or application reference"/></label><CommandSelect value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">All statuses</option>{["NOT_STARTED", "QUEUED", "PROVISIONING", "CONFIGURING", "READY", "FAILED"].map((entry) => <option key={entry}>{entry}</option>)}</CommandSelect></div></Panel><Panel><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-slate-50"><th className="cc-th">Organization</th><th className="cc-th">Application</th><th className="cc-th">Idempotency key</th><th className="cc-th">Attempts</th><th className="cc-th">Tenant</th><th className="cc-th">Updated</th><th className="cc-th">Status</th><th className="cc-th"></th></tr></thead><tbody>{rows.map(({ job, application }) => <tr key={job.id} className="border-t border-slate-100"><td className="cc-td font-semibold text-slate-900">{application!.organization.tradingName || application!.organization.legalName}</td><td className="cc-td font-mono text-xs">{application!.reference}</td><td className="cc-td max-w-56 truncate font-mono text-[10px]">{job.idempotencyKey}</td><td className="cc-td">{job.attempts}</td><td className="cc-td">{job.tenantId ?? "Not allocated"}</td><td className="cc-td">{formatDate(job.updatedAt)}</td><td className="cc-td"><StatusPill status={job.status.replaceAll("_", " ")}/></td><td className="cc-td"><CommandButton variant="quiet" onClick={() => navigate(`/command-center/provisioning/${application!.id}`)}>Open</CommandButton></td></tr>)}{rows.length === 0 && <tr><td colSpan={8} className="p-10 text-center text-sm text-slate-500">No active commercial agreements are waiting for provisioning.</td></tr>}</tbody></table></div></Panel></div>;
}

function ProvisioningDetail({ job, application }: { job: TenantProvisioningJob; application: OrganizationApplication }) {
  const provisioning = useTenantProvisioning();
  const command = useCommandCenter();
  const agreement = useCommercialOnboarding((state) => state.opportunities.find((item) => item.id === job.commercialOpportunityId));
  const identity = useAuth((state) => state.identity);
  const actor = command.platformUsers.find((item) => item.id === identity?.platformUserId);
  const canProvision = hasPermission(actor, "organizations.manage") && hasPermission(actor, "subscriptions.manage");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const organization = command.organizations.find((item) => item.id === job.organizationId);
  const subscription = command.subscriptions.find((item) => item.organizationId === job.organizationId);
  const license = command.licenses.find((item) => item.organizationId === job.organizationId);
  const owner = command.tenantUsers.find((item) => item.organizationId === job.organizationId && item.role === "Organization Administrator");
  const runJob = async () => { setBusy(true); setMessage(""); const result = await provisioning.runProvisioning(application.id); setMessage(result.ok ? "Provisioning completed and handed off to first-run setup." : result.error); setBusy(false); };
  const retry = async () => { const queued = provisioning.queueProvisioning(application.id); if (!queued.ok) return setMessage(queued.error); await runJob(); };
  return <div><Link to="/command-center/provisioning" className="mb-4 inline-flex items-center gap-2 text-xs font-bold text-slate-500 hover:text-emerald-700"><ArrowLeft size={14}/>Provisioning queue</Link><CommandPageHeader eyebrow={application.reference} title={application.organization.tradingName || application.organization.legalName} description="Tenant provisioning control and integrity verification" actions={<StatusPill status={job.status.replaceAll("_", " ")}/>}/>{message && <p role="status" className={`mb-4 rounded-xl px-4 py-3 text-sm font-semibold ${message.toLowerCase().includes("completed") ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{message}</p>}<div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="space-y-4"><Panel><PanelHeader title="Provisioning workflow" description={`Attempt ${job.attempts} · every step is retry-safe and audited`}/><div className="divide-y divide-slate-100">{job.steps.map((step, index) => <div key={step.key} className="flex items-start gap-4 p-4"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full text-xs font-bold ${step.status === "COMPLETED" ? "bg-emerald-100 text-emerald-700" : step.status === "FAILED" ? "bg-red-100 text-red-700" : step.status === "RUNNING" ? "bg-amber-100 text-amber-700" : "bg-slate-100 text-slate-500"}`}>{step.status === "COMPLETED" ? <CheckCircle2 size={17}/> : step.status === "FAILED" ? <CircleAlert size={17}/> : step.status === "RUNNING" ? <RefreshCw className="animate-spin" size={16}/> : index + 1}</span><div className="min-w-0 flex-1"><p className="text-sm font-bold text-slate-800">{step.label}</p><p className="mt-1 text-xs text-slate-400">{step.status.replaceAll("_", " ")}{step.completedAt ? ` · ${formatDate(step.completedAt)}` : ""}</p>{step.error && <p className="mt-2 text-xs text-red-700">{step.error}</p>}</div></div>)}</div><div className="flex flex-wrap gap-2 border-t border-slate-100 p-4">{job.status === "NOT_STARTED" && <CommandButton disabled={!canProvision || busy} onClick={() => { const result = provisioning.queueProvisioning(application.id); setMessage(result.ok ? "Provisioning queued with a stable idempotency key." : result.error); }}><Clock3 size={14}/>Queue provisioning</CommandButton>}{job.status === "QUEUED" && <CommandButton disabled={!canProvision || busy} onClick={runJob}><Play size={14}/>{busy ? "Provisioning…" : "Run provisioning"}</CommandButton>}{job.status === "FAILED" && <><CommandButton disabled={!canProvision || busy} onClick={retry}><RefreshCw size={14}/>Retry safely</CommandButton><CommandButton disabled={!canProvision || busy} variant="secondary" onClick={() => { const result = provisioning.resetFailedJob(application.id); setMessage(result.ok ? "Failed pre-commit job reset." : result.error); }}>Reset pre-commit job</CommandButton></>}</div></Panel>
    <Panel><PanelHeader title="Immutable provisioning history"/><div className="space-y-4 p-4">{[...job.events].reverse().map((entry) => <div key={entry.id} className="border-l border-slate-200 pl-4"><p className="text-xs font-bold text-slate-800">{entry.action}</p><p className="mt-1 text-[10px] text-slate-400">{entry.actorName} · {formatDate(entry.timestamp)}</p>{entry.reason && <p className="mt-1 break-all text-xs text-slate-600">{entry.reason}</p>}</div>)}</div></Panel></div><aside className="space-y-4"><Panel><PanelHeader title="Source authorization"/><div className="space-y-3 p-4"><Snapshot label="Application" value={application.status}/><Snapshot label="Agreement" value={agreement?.status ?? "Unavailable"}/><Snapshot label="Payment" value={agreement?.paymentStatus ?? "Unavailable"}/><Snapshot label="Package version" value={agreement?.packageVersionId ?? "Unavailable"}/><Snapshot label="Idempotency" value={job.idempotencyKey}/></div></Panel>{organization && <Panel><PanelHeader title="Provisioned boundary"/><div className="space-y-3 p-4"><Snapshot label="Tenant ID" value={organization.tenantId}/><Snapshot label="Namespace" value={organization.slug}/><Snapshot label="Organization" value={organization.status}/><Snapshot label="Subscription" value={subscription?.status ?? "Missing"}/><Snapshot label="License" value={license?.status ?? "Missing"}/><Snapshot label="Owner" value={owner?.status ?? "Missing"}/>{job.status === "READY" && <Link to={`/command-center/organizations/${organization.id}`} className="mt-2 inline-flex h-9 w-full items-center justify-center gap-2 rounded-lg bg-slate-950 px-3 text-sm font-semibold text-white"><Building2 size={14}/>Open organization</Link>}</div></Panel>}<div className="rounded-xl bg-slate-950 p-4 text-xs leading-5 text-white/60"><ServerCog className="mb-3 text-emerald-300" size={18}/><b className="block text-white">Access remains closed</b>The organization is created in Onboarding, the branch is Opening, and the owner is Invited. No clinical access is activated until first-run setup and go-live controls pass.</div></aside></div></div>;
}

function Snapshot({ label, value }: { label: string; value: string }) { return <div className="flex items-start justify-between gap-4 text-xs"><span className="shrink-0 text-slate-400">{label}</span><b className="break-all text-right text-slate-700">{value}</b></div>; }
