import { useState } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { AlertTriangle, ArrowLeft, Building2, Check, Clock3, Database, KeyRound, Lock, MapPin, Paintbrush, Phone, ShieldCheck, UserRound, X } from "lucide-react";
import { Modal } from "@/components/ui/Modal";
import { PRODUCTS, modulesByProduct, type ProductKey } from "@/platform/entitlements";
import { resolveEntitlements } from "../resolver";
import { useCommandCenter } from "../useCommandCenter";
import type { OrganizationStatus } from "../domain";
import { CommandButton, CommandInput, CommandPageHeader, CommandSelect, Panel, PanelHeader, StatusPill } from "../components/ui";
import { formatDate, formatMoney } from "../format";
import { cn } from "@/lib/cn";

const TABS = ["Overview", "Subscription", "Products & Modules", "Users", "Branches", "Documents", "Billing", "Activity", "Audit Log", "Integrations", "Support", "Branding & Security"];

type PendingAction = { title: string; description: string; confirm: string; danger?: boolean; onConfirm: (reason: string) => void };

export default function Tenant360() {
  const { organizationId = "" } = useParams();
  const navigate = useNavigate();
  const [searchParams, setSearchParams] = useSearchParams();
  const activeTab = TABS.includes(searchParams.get("tab") ?? "") ? searchParams.get("tab")! : "Overview";
  const state = useCommandCenter();
  const organization = state.organizations.find((item) => item.id === organizationId);
  const subscription = state.subscriptions.find((item) => item.organizationId === organizationId);
  const license = state.licenses.find((item) => item.organizationId === organizationId);
  const [pending, setPending] = useState<PendingAction | null>(null);

  if (!organization) return <Panel className="p-10 text-center"><h1 className="font-display text-xl font-bold">Organization not found</h1><CommandButton className="mt-4" onClick={() => navigate("/command-center/organizations")}>Back to organizations</CommandButton></Panel>;

  const packageItem = state.packages.find((item) => item.id === subscription?.packageId);
  const resolved = subscription && license ? resolveEntitlements(organizationId, subscription, license, state.entitlements) : undefined;
  const selectTab = (tab: string) => setSearchParams(tab === "Overview" ? {} : { tab });

  const changeStatus = (status: OrganizationStatus) => setPending({
    title: `${status} ${organization.name}`,
    description: "This changes the tenant lifecycle, subscription and license projection. Hospital access can be affected immediately.",
    confirm: status,
    danger: ["Suspended", "Expired", "Terminated"].includes(status),
    onConfirm: (reason) => state.setOrganizationStatus(organizationId, status, reason),
  });

  return <div>
    <button onClick={() => navigate("/command-center/organizations")} className="mb-3 flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-slate-900"><ArrowLeft size={14} /> Organizations</button>
    <CommandPageHeader eyebrow={organization.tenantId} title={organization.name} description={`${organization.type} · ${organization.state}, ${organization.country} · ${organization.domain}`} actions={<><StatusPill status={organization.status} /><CommandButton variant="secondary" onClick={() => selectTab("Support")} title="Tenant access requires a reasoned, time-bound support session"><KeyRound size={15} /> Request tenant access</CommandButton><CommandSelect value="Actions" onChange={(event) => { if (event.target.value !== "Actions") changeStatus(event.target.value as OrganizationStatus); event.target.value = "Actions"; }} aria-label="Organization actions"><option>Actions</option><option>Active</option><option>Grace Period</option><option>Suspended</option><option>Expired</option><option>Terminated</option></CommandSelect></>} />

    <div className="mb-4 grid grid-cols-2 gap-2 lg:grid-cols-6">
      <Summary label="Plan" value={packageItem?.name ?? "No plan"} />
      <Summary label="Subscription" value={subscription?.status ?? "Prospect"} status />
      <Summary label="License" value={license?.status ?? "Not issued"} status />
      <Summary label="Users" value={`${organization.activeUsers} / ${organization.licensedUsers}`} />
      <Summary label="Branches" value={organization.branchCount} />
      <Summary label="Renewal" value={formatDate(subscription?.renewalDate)} />
    </div>

    <div className="mb-4 overflow-x-auto border-b border-slate-200 [scrollbar-width:none]"><div role="tablist" aria-label="Organization sections" className="flex min-w-max gap-1">{TABS.map((tab) => <button key={tab} role="tab" aria-selected={activeTab === tab} onClick={() => selectTab(tab)} className={cn("border-b-2 px-3 py-2.5 text-xs font-semibold transition", activeTab === tab ? "border-emerald-500 text-emerald-700" : "border-transparent text-slate-500 hover:text-slate-800")}>{tab}</button>)}</div></div>

    {activeTab === "Overview" && <Overview organization={organization} state={state} packageName={packageItem?.name} />}
    {activeTab === "Subscription" && <SubscriptionTab organization={organization} state={state} onAction={changeStatus} />}
    {activeTab === "Products & Modules" && <EntitlementsTab organizationId={organizationId} state={state} resolved={resolved} setPending={setPending} />}
    {activeTab === "Users" && <UsersTab organizationId={organizationId} state={state} setPending={setPending} />}
    {activeTab === "Branches" && <BranchesTab organizationId={organizationId} state={state} />}
    {activeTab === "Documents" && <DocumentsTab organizationId={organizationId} state={state} setPending={setPending} />}
    {activeTab === "Billing" && <BillingTab organizationId={organizationId} state={state} />}
    {activeTab === "Activity" && <ActivityTab organizationId={organizationId} state={state} />}
    {activeTab === "Audit Log" && <AuditTab organizationId={organizationId} state={state} />}
    {activeTab === "Integrations" && <IntegrationsTab organizationId={organizationId} state={state} />}
    {activeTab === "Support" && <SupportTab organization={organization} />}
    {activeTab === "Branding & Security" && <BrandingTab organizationId={organizationId} state={state} />}

    <ReasonDialog pending={pending} onClose={() => setPending(null)} />
  </div>;
}

function Summary({ label, value, status }: { label: string; value: React.ReactNode; status?: boolean }) {
  return <div className="rounded-lg border border-slate-200 bg-white px-3 py-2.5"><p className="text-[9px] font-bold uppercase tracking-[.12em] text-slate-400">{label}</p><div className="mt-1 truncate text-sm font-bold text-slate-900">{status && typeof value === "string" ? <StatusPill status={value} /> : value}</div></div>;
}

function Overview({ organization, state, packageName }: { organization: ReturnType<typeof useCommandCenter.getState>["organizations"][number]; state: ReturnType<typeof useCommandCenter.getState>; packageName?: string }) {
  const modules = state.subscriptions.find((s) => s.organizationId === organization.id)?.snapshotModuleIds ?? [];
  const recent = state.auditEvents.filter((e) => e.organizationId === organization.id).slice(0, 5);
  return <div className="grid gap-4 xl:grid-cols-[1.35fr_.85fr]">
    <div className="space-y-4">
      <Panel><PanelHeader title="Organization profile" /><div className="grid gap-x-8 gap-y-4 p-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Legal company" value={organization.legalName} icon={<Building2 size={14} />} /><Field label="Registration number" value={organization.registrationNumber} /><Field label="Facility type" value={organization.type} /><Field label="Address" value={organization.address} icon={<MapPin size={14} />} /><Field label="Primary contact" value={organization.primaryContact} icon={<UserRound size={14} />} /><Field label="Contact" value={`${organization.email} · ${organization.phone}`} icon={<Phone size={14} />} /><Field label="Account manager" value={organization.accountManager} /><Field label="Implementation manager" value={organization.implementationManager} /><Field label="Tenant ID" value={organization.tenantId} /></div></Panel>
      <Panel><PanelHeader title="Capacity & adoption" /><div className="grid grid-cols-2 divide-x divide-y divide-slate-100 sm:grid-cols-4 sm:divide-y-0"><Mini label="Active users" value={organization.activeUsers} /><Mini label="Licensed seats" value={organization.licensedUsers} /><Mini label="Storage" value={`${organization.storageUsedGb} / ${organization.storageLimitGb} GB`} /><Mini label="Activated modules" value={modules.length} /></div></Panel>
      <Panel><PanelHeader title="Products" /><div className="grid gap-2 p-4 sm:grid-cols-3">{(Object.keys(PRODUCTS) as ProductKey[]).map((product) => { const on = modules.some((m) => m.startsWith(product + ".")); return <div key={product} className={cn("rounded-lg border px-3 py-3", on ? "border-emerald-200 bg-emerald-50/50" : "border-slate-200 bg-slate-50 opacity-60")}><div className="flex items-center justify-between"><p className="text-sm font-bold">{PRODUCTS[product].label}</p><StatusPill status={on ? "Active" : "Not licensed"} /></div><p className="mt-1 text-xs leading-5 text-slate-500">{PRODUCTS[product].tagline}</p></div>; })}</div></Panel>
    </div>
    <div className="space-y-4">
      <Panel><PanelHeader title="Account health" /><div className="space-y-3 p-4"><HealthRow label="Subscription" value={packageName ?? "Prospect"} status={organization.status} /><HealthRow label="Billing" value={organization.billingStatus} status={organization.billingStatus} /><HealthRow label="Onboarding" value={organization.onboardingStatus} status={organization.onboardingStatus} /><HealthRow label="License expiry" value={formatDate(organization.expirationDate)} status={organization.status === "Payment Due" ? "Expiring Soon" : "Active"} /></div></Panel>
      <Panel><PanelHeader title="Recent activity" /><div className="divide-y divide-slate-100">{recent.length ? recent.map((event) => <div key={event.id} className="px-4 py-3"><p className="text-sm font-semibold text-slate-800">{event.action}</p><p className="mt-0.5 text-xs text-slate-400">{event.actorName} · {formatDate(event.timestamp)}</p></div>) : <p className="p-4 text-sm text-slate-500">No recent platform activity.</p>}</div></Panel>
    </div>
  </div>;
}

function Field({ label, value, icon }: { label: string; value: React.ReactNode; icon?: React.ReactNode }) { return <div><p className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider text-slate-400">{icon}{label}</p><p className="mt-1 text-sm font-medium leading-5 text-slate-800">{value}</p></div>; }
function Mini({ label, value }: { label: string; value: React.ReactNode }) { return <div className="px-4 py-4"><p className="font-display text-xl font-bold text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>; }
function HealthRow({ label, value, status }: { label: string; value: string; status: string }) { return <div className="flex items-center justify-between gap-3"><span className="text-sm text-slate-500">{label}</span><span className="flex items-center gap-2 text-sm font-semibold text-slate-800">{value}<StatusPill status={status} /></span></div>; }

function SubscriptionTab({ organization, state, onAction }: { organization: ReturnType<typeof useCommandCenter.getState>["organizations"][number]; state: ReturnType<typeof useCommandCenter.getState>; onAction: (s: OrganizationStatus) => void }) {
  const subscription = state.subscriptions.find((s) => s.organizationId === organization.id);
  const license = state.licenses.find((l) => l.organizationId === organization.id);
  const pkg = state.packages.find((p) => p.id === subscription?.packageId);
  if (!subscription || !license) return <Panel className="p-10 text-center text-sm text-slate-500">No subscription has been created for this prospect.</Panel>;
  const actorId = state.platformUsers[0]?.id ?? "unknown";
  const changePackage = () => { const choices = state.packageVersions.filter((item) => item.status === "Published").map((item) => `${item.id}: ${state.packages.find((pkgItem) => pkgItem.id === item.packageId)?.name} v${item.version}`).join("\n"); const versionId = window.prompt(`Enter package version ID:\n${choices}`); if (!versionId) return; const reason = window.prompt("Reason for package change"); if (!reason) return; const result = state.changeSubscriptionPackage(subscription.id, versionId, actorId, reason); window.alert(result.ok ? "Package changed. Existing history remains pinned to its original version." : result.error); };
  const applyCredit = () => { const amount = Number(window.prompt(`Credit amount (${subscription.currency})`, "0")); if (!amount) return; const reason = window.prompt("Reason for credit"); if (!reason) return; const result = state.applySubscriptionCredit(subscription.id, amount, actorId, reason); window.alert(result.ok ? "Credit applied." : result.error); };
  const renew = () => { const reason = window.prompt("Reason for renewal", "Customer renewal approved"); if (!reason) return; const result = state.renewSubscription(subscription.id, actorId, reason); window.alert(result.ok ? "Subscription renewed." : result.error); };
  return <div className="space-y-4"><Panel><PanelHeader title="Subscription terms" action={<div className="flex flex-wrap gap-2"><CommandButton variant="secondary" onClick={changePackage}>Change package</CommandButton><CommandButton variant="secondary" onClick={applyCredit}>Apply credit</CommandButton><CommandButton onClick={renew}>Renew subscription</CommandButton></div>} /><div className="grid gap-x-8 gap-y-4 p-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Subscription ID" value={subscription.id} /><Field label="Plan snapshot" value={`${pkg?.name} · version ${state.packageVersions.find((v) => v.id === subscription.packageVersionId)?.version}`} /><Field label="Billing cycle" value={subscription.billingCycle} /><Field label="Status" value={<StatusPill status={subscription.status} />} /><Field label="Start date" value={formatDate(subscription.startDate)} /><Field label="Renewal date" value={formatDate(subscription.renewalDate)} /><Field label="Expiration" value={formatDate(subscription.expirationDate)} /><Field label="Grace period" value={`${subscription.gracePeriodDays} days`} /></div></Panel>
    <div className="grid gap-4 lg:grid-cols-2"><Panel><PanelHeader title="Commercial summary" /><div className="p-4"><div className="space-y-3 border-b border-slate-100 pb-4"><MoneyRow label="Base amount" value={subscription.baseAmount} /><MoneyRow label="Add-ons" value={subscription.addOnAmount} /><MoneyRow label="Discount" value={-subscription.discount} /><MoneyRow label="Tax" value={subscription.tax} /></div><div className="flex items-center justify-between pt-4"><span className="font-semibold">Final amount</span><span className="font-display text-xl font-bold">{formatMoney(subscription.finalAmount, subscription.currency)}</span></div></div></Panel><Panel><PanelHeader title="License policy" /><div className="grid grid-cols-2 gap-4 p-4"><Field label="License ID" value={license.id} /><Field label="Status" value={<StatusPill status={license.status} />} /><Field label="Seats" value={`${organization.activeUsers} / ${license.userLimit}`} /><Field label="Branches" value={`${organization.branchCount} / ${license.branchLimit}`} /><Field label="Storage" value={`${organization.storageUsedGb} / ${license.storageLimitGb} GB`} /><Field label="Last validation" value={formatDate(license.lastValidatedAt)} /></div></Panel></div>
    <Panel><PanelHeader title="Lifecycle controls" description="High-risk changes require a reason and create an immutable audit event." /><div className="flex flex-wrap gap-2 p-4"><CommandButton variant="secondary" onClick={() => onAction("Active")}>Reactivate</CommandButton><CommandButton variant="secondary" onClick={() => onAction("Grace Period")}>Start grace period</CommandButton><CommandButton variant="danger" onClick={() => onAction("Suspended")}>Suspend</CommandButton><CommandButton variant="danger" onClick={() => onAction("Terminated")}>Terminate</CommandButton></div></Panel></div>;
}
function MoneyRow({ label, value }: { label: string; value: number }) { return <div className="flex items-center justify-between text-sm"><span className="text-slate-500">{label}</span><span className="font-semibold text-slate-800">{value < 0 ? "−" : ""}{formatMoney(Math.abs(value))}</span></div>; }

function EntitlementsTab({ organizationId, state, resolved, setPending }: { organizationId: string; state: ReturnType<typeof useCommandCenter.getState>; resolved?: ReturnType<typeof resolveEntitlements>; setPending: (a: PendingAction | null) => void }) {
  if (!resolved) return <Panel className="p-10 text-center text-sm text-slate-500">Create a subscription and license before assigning entitlements.</Panel>;
  return <div className="space-y-4"><div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800"><strong>Resolved entitlement response</strong> combines the pinned package version, add-ons, tenant overrides, temporary access and revocations. The same projection drives hospital navigation and route protection.</div>{(Object.keys(PRODUCTS) as ProductKey[]).map((productKey) => <Panel key={productKey}><PanelHeader title={PRODUCTS[productKey].label} description={PRODUCTS[productKey].tagline} action={<StatusPill status={resolved.products[productKey] ? "Licensed" : "Not licensed"} />} /><div className="divide-y divide-slate-100">{modulesByProduct(productKey).map((module) => { const enabled = !!resolved.modules[module.key]; return <div key={module.key} className="flex items-center gap-4 px-4 py-3"><span className={cn("grid h-8 w-8 place-items-center rounded-lg", enabled ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-400")}>{enabled ? <Check size={16} /> : <X size={16} />}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="text-sm font-bold text-slate-900">{module.label}</p>{module.core && <StatusPill status="Core" />}</div><p className="truncate text-xs text-slate-500">{module.description}</p><p className="mt-1 font-mono text-[10px] text-slate-400">{module.key} · {module.routes.length} route grants</p></div><button disabled={module.core} onClick={() => setPending({ title: `${enabled ? "Disable" : "Enable"} ${module.label}`, description: enabled ? "Hospital navigation and protected routes will be updated immediately. The underlying data remains retained." : "This creates a tenant override and adds the module to the resolved entitlement projection.", confirm: enabled ? "Disable module" : "Enable module", danger: enabled, onConfirm: (reason) => state.setModuleEntitlement(organizationId, module.key, !enabled, reason) })} className={cn("relative h-6 w-11 rounded-full transition", enabled ? "bg-emerald-500" : "bg-slate-300", module.core && "cursor-not-allowed opacity-50")} aria-label={`${enabled ? "Disable" : "Enable"} ${module.label}`}><span className={cn("absolute top-0.5 h-5 w-5 rounded-full bg-white shadow-sm transition", enabled ? "left-[22px]" : "left-0.5")} /></button></div>; })}</div></Panel>)}</div>;
}

function UsersTab({ organizationId, state, setPending }: { organizationId: string; state: ReturnType<typeof useCommandCenter.getState>; setPending: (a: PendingAction | null) => void }) {
  const users = state.tenantUsers.filter((u) => u.organizationId === organizationId);
  const invite = () => { const name = window.prompt("Full name"); if (!name) return; const email = window.prompt("Email address"); if (!email) return; const role = window.prompt("Tenant role", "Hospital Administrator"); if (!role) return; const branchId = state.branches.find((item) => item.organizationId === organizationId)?.id; const result = state.inviteTenantUser({ organizationId, branchId, name, email, employeeId: `EMP-${Date.now().toString().slice(-5)}`, role, department: "Administration" }, state.platformUsers[0]?.id ?? "unknown"); window.alert(result.ok ? "Tenant invitation created." : result.error); };
  return <Panel><PanelHeader title="Hospital tenant users" description="Operational identity data only; passwords and authentication secrets are never exposed." action={<CommandButton onClick={invite}>Invite user</CommandButton>} /><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-slate-50"><th className="cc-th">User</th><th className="cc-th">Employee ID</th><th className="cc-th">Role</th><th className="cc-th">Department</th><th className="cc-th">Facility</th><th className="cc-th">Last login</th><th className="cc-th">MFA</th><th className="cc-th">Status</th><th className="cc-th"></th></tr></thead><tbody>{users.map((user) => { const branch = state.branches.find((b) => b.id === user.branchId); const activeSession = state.sessions.find((s) => s.userId === user.id && s.status === "Active"); return <tr key={user.id} className="border-t border-slate-100"><td className="cc-td"><span className="block font-semibold text-slate-900">{user.name}</span><span className="block text-xs text-slate-400">{user.email}</span></td><td className="cc-td font-mono text-xs">{user.employeeId}</td><td className="cc-td">{user.role}</td><td className="cc-td">{user.department}</td><td className="cc-td">{branch?.name ?? "All branches"}</td><td className="cc-td">{formatDate(user.lastLoginAt)}</td><td className="cc-td"><StatusPill status={user.mfaEnabled ? "Enforced" : "Not enrolled"} /></td><td className="cc-td"><StatusPill status={user.status} /></td><td className="cc-td"><CommandButton disabled={!activeSession} variant="quiet" onClick={() => activeSession && setPending({ title: `Revoke ${user.name}'s session`, description: "The user will be required to authenticate again. No password or token is displayed.", confirm: "Revoke session", danger: true, onConfirm: (reason) => state.revokeSession(activeSession.id, reason) })}><KeyRound size={14} /> Revoke</CommandButton></td></tr>; })}</tbody></table></div></Panel>;
}

function BranchesTab({ organizationId, state }: { organizationId: string; state: ReturnType<typeof useCommandCenter.getState> }) {
  const branches = state.branches.filter((b) => b.organizationId === organizationId);
  const add = () => { const name = window.prompt("Facility name"); if (!name) return; const facilityCode = window.prompt("Unique facility code"); if (!facilityCode) return; const address = window.prompt("Facility address"); if (!address) return; const result = state.addBranch({ organizationId, name, facilityCode, address }, state.platformUsers[0]?.id ?? "unknown"); window.alert(result.ok ? "Branch added in Opening status." : result.error); };
  return <Panel><PanelHeader title="Branches & facilities" action={<CommandButton onClick={add}>Add branch</CommandButton>} /><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-slate-50"><th className="cc-th">Branch</th><th className="cc-th">Facility code</th><th className="cc-th">Address</th><th className="cc-th">Active users</th><th className="cc-th">Departments</th><th className="cc-th">Modules</th><th className="cc-th">Status</th><th className="cc-th">Date added</th></tr></thead><tbody>{branches.map((branch) => <tr key={branch.id} className="border-t border-slate-100"><td className="cc-td font-semibold text-slate-900">{branch.name}</td><td className="cc-td font-mono text-xs">{branch.facilityCode}</td><td className="cc-td">{branch.address}</td><td className="cc-td">{branch.activeUsers}</td><td className="cc-td">{branch.departmentCount}</td><td className="cc-td">{branch.moduleIds.length}</td><td className="cc-td"><StatusPill status={branch.status} /></td><td className="cc-td">{formatDate(branch.createdAt)}</td></tr>)}</tbody></table></div></Panel>;
}

function DocumentsTab({ organizationId, state, setPending }: { organizationId: string; state: ReturnType<typeof useCommandCenter.getState>; setPending: (a: PendingAction | null) => void }) {
  const docs = state.documents.filter((d) => d.organizationId === organizationId);
  const add = () => { const type = window.prompt("Required document name"); if (!type) return; const category = window.prompt("Category: Legal, Contract, Compliance, Billing, or Implementation", "Compliance") as "Legal" | "Contract" | "Compliance" | "Billing" | "Implementation" | null; if (!category) return; const result = state.addDocumentRequest(organizationId, category, type, state.platformUsers[0]?.id ?? "unknown"); window.alert(result.ok ? "Document request created." : result.error); };
  return <Panel><PanelHeader title="Organization documents" description="Metadata references secure object storage; file contents are not held in client state." action={<CommandButton onClick={add}>Add document request</CommandButton>} /><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-slate-50"><th className="cc-th">Category</th><th className="cc-th">Document</th><th className="cc-th">Filename</th><th className="cc-th">Version</th><th className="cc-th">Uploaded</th><th className="cc-th">Expiry</th><th className="cc-th">Status</th><th className="cc-th">Actions</th></tr></thead><tbody>{docs.map((doc) => <tr key={doc.id} className="border-t border-slate-100"><td className="cc-td"><StatusPill status={doc.category} /></td><td className="cc-td font-semibold text-slate-900">{doc.type}</td><td className="cc-td">{doc.filename ?? "Not uploaded"}</td><td className="cc-td">v{doc.version}</td><td className="cc-td">{formatDate(doc.uploadedAt)}</td><td className="cc-td">{formatDate(doc.expiryDate)}</td><td className="cc-td"><StatusPill status={doc.status} /></td><td className="cc-td"><div className="flex gap-1"><CommandButton disabled={!doc.filename} variant="quiet" onClick={() => setPending({ title: `Approve ${doc.type}`, description: "Confirm that the document passed verification. This creates an auditable verification record.", confirm: "Approve document", onConfirm: (reason) => state.reviewDocument(doc.id, "Approved", reason) })}><Check size={14} /></CommandButton><CommandButton disabled={!doc.filename} variant="quiet" onClick={() => setPending({ title: `Reject ${doc.type}`, description: "The reason will be visible to the implementation team and recorded in the audit trail.", confirm: "Reject document", danger: true, onConfirm: (reason) => state.reviewDocument(doc.id, "Rejected", reason) })}><X size={14} /></CommandButton></div></td></tr>)}</tbody></table></div></Panel>;
}

function BillingTab({ organizationId, state }: { organizationId: string; state: ReturnType<typeof useCommandCenter.getState> }) {
  const invoices = state.invoices.filter((i) => i.organizationId === organizationId);
  const payments = state.payments.filter((p) => p.organizationId === organizationId);
  return <div className="grid gap-4 xl:grid-cols-[1.4fr_.8fr]"><Panel><PanelHeader title="Customer invoices" description="Sabi-to-hospital subscription billing; separate from patient billing." /><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-slate-50"><th className="cc-th">Invoice</th><th className="cc-th">Period</th><th className="cc-th">Amount</th><th className="cc-th">Due date</th><th className="cc-th">Status</th></tr></thead><tbody>{invoices.map((invoice) => <tr key={invoice.id} className="border-t border-slate-100"><td className="cc-td font-mono text-xs font-semibold">{invoice.number}</td><td className="cc-td">{invoice.billingPeriod}</td><td className="cc-td font-semibold">{formatMoney(invoice.total, invoice.currency)}</td><td className="cc-td">{formatDate(invoice.dueDate)}</td><td className="cc-td"><StatusPill status={invoice.status} /></td></tr>)}</tbody></table></div></Panel><Panel><PanelHeader title="Transactions" /><div className="divide-y divide-slate-100">{payments.map((payment) => <div key={payment.id} className="p-4"><div className="flex items-center justify-between"><p className="font-mono text-xs font-semibold">{payment.reference}</p><StatusPill status={payment.status} /></div><p className="mt-1 text-sm font-bold">{formatMoney(payment.amount, payment.currency)}</p><p className="text-xs text-slate-400">{payment.provider} · {formatDate(payment.paidAt)}</p></div>)}</div></Panel></div>;
}

function ActivityTab({ organizationId, state }: { organizationId: string; state: ReturnType<typeof useCommandCenter.getState> }) { return <Panel><PanelHeader title="Tenant activity" description="Chronological operational activity without patient clinical data." /><Timeline events={state.auditEvents.filter((e) => e.organizationId === organizationId)} /></Panel>; }
function AuditTab({ organizationId, state }: { organizationId: string; state: ReturnType<typeof useCommandCenter.getState> }) { return <Panel><PanelHeader title="Immutable audit log" description="No edit or delete controls are provided." /><Timeline events={state.auditEvents.filter((e) => e.organizationId === organizationId)} detailed /></Panel>; }
function Timeline({ events, detailed }: { events: ReturnType<typeof useCommandCenter.getState>["auditEvents"]; detailed?: boolean }) { return <div className="divide-y divide-slate-100">{events.map((event) => <div key={event.id} className="grid gap-2 px-4 py-3 sm:grid-cols-[140px_1fr_auto]"><p className="text-xs text-slate-400">{formatDate(event.timestamp)}</p><div><p className="text-sm font-semibold text-slate-800">{event.action}</p><p className="text-xs text-slate-500">{event.actorName} · {event.actorRole}{event.reason ? ` · ${event.reason}` : ""}</p>{detailed && <p className="mt-1 font-mono text-[10px] text-slate-400">{event.resourceType}/{event.resourceId} · {event.correlationId}</p>}</div><StatusPill status={event.resourceType} /></div>)}{!events.length && <p className="p-8 text-center text-sm text-slate-500">No activity recorded.</p>}</div>; }

function IntegrationsTab({ organizationId, state }: { organizationId: string; state: ReturnType<typeof useCommandCenter.getState> }) { const rows = state.integrations.filter((i) => i.organizationId === organizationId); const add = () => { const provider = window.prompt("Integration provider"); if (!provider) return; const category = window.prompt("Integration category", "Data exchange"); if (!category) return; const environment = window.confirm("Use Production environment? Choose Cancel for Sandbox.") ? "Production" : "Sandbox"; const result = state.addIntegration({ organizationId, provider, category, environment }, state.platformUsers[0]?.id ?? "unknown"); window.alert(result.ok ? "Integration configuration created." : result.error); }; return <Panel><PanelHeader title="Tenant integrations" description="Credentials are masked. Secrets belong in a backend vault, never in frontend state." action={<CommandButton onClick={add}>Configure integration</CommandButton>} /><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-slate-50"><th className="cc-th">Provider</th><th className="cc-th">Category</th><th className="cc-th">Environment</th><th className="cc-th">Credential</th><th className="cc-th">Last sync</th><th className="cc-th">Errors</th><th className="cc-th">Status</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t border-slate-100"><td className="cc-td font-semibold text-slate-900">{row.provider}</td><td className="cc-td">{row.category}</td><td className="cc-td">{row.environment}</td><td className="cc-td font-mono text-xs">{row.maskedCredential}</td><td className="cc-td">{formatDate(row.lastSyncAt)}</td><td className="cc-td">{row.errorCount}</td><td className="cc-td"><StatusPill status={row.status} /></td></tr>)}</tbody></table></div></Panel>; }

function SupportTab({ organization }: { organization: ReturnType<typeof useCommandCenter.getState>["organizations"][number] }) { const state = useCommandCenter(); const [reason, setReason] = useState(""); const [duration, setDuration] = useState(30); const requests = state.supportAccessSessions.filter((item) => item.organizationId === organization.id); const request = () => { const result = state.requestSupportAccess(organization.id, reason, duration, state.platformUsers[0]?.id ?? "unknown"); if (!result.ok) return window.alert(result.error); setReason(""); window.alert("Support access request submitted."); }; return <div className="grid gap-4 lg:grid-cols-2"><Panel><PanelHeader title="Controlled support access" description="Impersonation is never a one-click tenant login." /><div className="space-y-4 p-4"><div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800"><div className="flex gap-2"><Lock size={16} className="mt-0.5 shrink-0" /><p>Support sessions require an authorized requester, tenant, reason, duration and immutable audit event. Stronger approval policies can be enforced by the identity backend.</p></div></div><label className="block"><span className="cc-label">Tenant</span><CommandInput value={organization.name} readOnly className="w-full bg-slate-50" /></label><label className="block"><span className="cc-label">Reason</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} className="min-h-24 w-full rounded-lg border border-slate-200 p-3 text-sm outline-none focus:border-emerald-500" placeholder="Describe the specific support case…" /></label><label className="block"><span className="cc-label">Duration</span><CommandSelect className="w-full" value={duration} onChange={(event) => setDuration(Number(event.target.value))}><option value={30}>30 minutes</option><option value={60}>1 hour</option><option value={240}>4 hours</option></CommandSelect></label><CommandButton onClick={request}>Request support access</CommandButton></div></Panel><Panel><PanelHeader title="Support cases" /><div className="divide-y divide-slate-100">{requests.length ? requests.map((item) => <div key={item.id} className="p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold text-slate-800">{item.reason}</p><StatusPill status={item.status} /></div><p className="mt-1 text-xs text-slate-400">Expires {formatDate(item.expiresAt)}</p></div>) : <div className="p-8 text-center"><Clock3 className="mx-auto text-slate-300" /><p className="mt-3 text-sm font-semibold text-slate-700">No support requests</p><p className="mt-1 text-xs text-slate-500">Submitted access requests will appear here.</p></div>}</div></Panel></div>; }

function BrandingTab({ organizationId, state }: { organizationId: string; state: ReturnType<typeof useCommandCenter.getState> }) {
  const theme = state.themes.find((t) => t.organizationId === organizationId)!;
  const [name, setName] = useState(theme.organizationDisplayName ?? "");
  const [product, setProduct] = useState(theme.productDisplayName ?? "Sabi OS");
  return <div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><Panel><PanelHeader title="Branding & identity" /><div className="space-y-4 p-4"><label className="block"><span className="cc-label">Organization display name</span><CommandInput className="w-full" value={name} onChange={(e) => setName(e.target.value)} /></label><label className="block"><span className="cc-label">Product display name</span><CommandInput className="w-full" value={product} onChange={(e) => setProduct(e.target.value)} /></label><div className="grid grid-cols-2 gap-3">{(["primary", "secondary", "accent", "sidebar"] as const).map((key) => <label key={key}><span className="cc-label">{key}</span><div className="flex items-center gap-2"><input type="color" value={theme.colors[key]} onChange={(e) => state.updateThemeColor(organizationId, key, e.target.value)} className="h-9 w-12 rounded border border-slate-200" /><CommandInput value={theme.colors[key]} onChange={(e) => { if (/^#[0-9a-f]{6}$/i.test(e.target.value)) state.updateThemeColor(organizationId, key, e.target.value); }} className="min-w-0 flex-1 font-mono text-xs" /></div></label>)}</div><CommandButton onClick={() => state.updateThemeIdentity(organizationId, { organizationDisplayName: name, productDisplayName: product })}>Save identity</CommandButton></div></Panel><Panel><PanelHeader title="Live tenant preview" description="Platform theme → tenant override → user preference" /><TenantPreview theme={theme} /></Panel><Panel className="xl:col-span-2"><PanelHeader title="Security posture" /><div className="grid gap-3 p-4 sm:grid-cols-3"><SecurityItem icon={<ShieldCheck size={17} />} label="MFA policy" value="Required for administrators" /><SecurityItem icon={<Clock3 size={17} />} label="Session timeout" value="30 minutes" /><SecurityItem icon={<Database size={17} />} label="Data retention" value="7 years" /></div></Panel></div>;
}

function TenantPreview({ theme }: { theme: ReturnType<typeof useCommandCenter.getState>["themes"][number] }) { return <div className="m-4 overflow-hidden rounded-xl border border-slate-200 shadow-lg" style={{ fontFamily: theme.typography.fontFamily }}><div className="flex h-72"><div className="w-36 p-3 text-white" style={{ background: theme.colors.sidebar }}><div className="mb-5 flex items-center gap-2 font-bold"><span className="grid h-7 w-7 place-items-center rounded-lg" style={{ background: theme.colors.primary }}><Paintbrush size={14} /></span><span className="truncate text-xs">{theme.productDisplayName}</span></div>{["Dashboard", "Patients", "Laboratory", "Pharmacy", "Reports"].map((item, i) => <div key={item} className="mb-1 rounded-md px-2 py-1.5 text-[10px]" style={i === 0 ? { background: theme.colors.primary } : { opacity: .65 }}>{item}</div>)}</div><div className="flex-1" style={{ background: theme.colors.background }}><div className="h-11 border-b bg-white px-4 py-3 text-xs font-semibold">{theme.organizationDisplayName}</div><div className="p-4"><p className="text-sm font-bold">Good morning</p><p className="text-[10px] text-slate-500">Here is today&apos;s facility overview.</p><div className="mt-3 grid grid-cols-3 gap-2">{["Waiting", "Appointments", "Admissions"].map((x, i) => <div key={x} className="rounded-lg bg-white p-2 shadow-sm"><p className="text-[9px] text-slate-400">{x}</p><p className="mt-1 font-bold" style={{ color: i === 0 ? theme.colors.primary : "#0f172a" }}>{[18, 42, 11][i]}</p></div>)}</div><div className="mt-3 h-20 rounded-lg bg-white p-3"><div className="h-1.5 w-24 rounded" style={{ background: theme.colors.primary }} /><div className="mt-3 h-1.5 w-full rounded bg-slate-100" /><div className="mt-2 h-1.5 w-4/5 rounded bg-slate-100" /></div></div></div></div></div>; }
function SecurityItem({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="flex items-center gap-3 rounded-lg bg-slate-50 p-3"><span className="text-emerald-600">{icon}</span><span><span className="block text-xs text-slate-500">{label}</span><span className="block text-sm font-semibold text-slate-800">{value}</span></span></div>; }

function ReasonDialog({ pending, onClose }: { pending: PendingAction | null; onClose: () => void }) {
  const [reason, setReason] = useState("");
  const [error, setError] = useState("");
  const confirm = () => { try { pending?.onConfirm(reason); setReason(""); setError(""); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to complete this action."); } };
  return <Modal open={!!pending} onClose={() => { setReason(""); setError(""); onClose(); }} title={pending?.title ?? "Confirm action"} footer={<><CommandButton variant="secondary" onClick={onClose}>Cancel</CommandButton><CommandButton variant={pending?.danger ? "danger" : "primary"} onClick={confirm}>{pending?.confirm ?? "Confirm"}</CommandButton></>}><div className="flex gap-3 rounded-lg bg-slate-50 p-3"><AlertTriangle size={18} className={pending?.danger ? "shrink-0 text-red-600" : "shrink-0 text-amber-600"} /><p className="text-sm leading-5 text-slate-600">{pending?.description}</p></div><label className="mt-4 block"><span className="cc-label">Reason required</span><textarea autoFocus value={reason} onChange={(e) => setReason(e.target.value)} className="min-h-24 w-full rounded-lg border border-slate-200 p-3 text-sm outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/15" placeholder="Provide the operational or commercial reason…" /></label>{error && <p role="alert" className="mt-2 text-xs font-semibold text-red-600">{error}</p>}</Modal>;
}
