import { doctorRequest } from "../services/doctorAuth";
const ROOT = "/doctor-appointments/practice";
export const videoConfig = (signal) => doctorRequest('/doctor-appointments/video-config', { signal }).then((r) => r.data);
export const joinVideoSession = (id, consent) => doctorRequest(`${ROOT}/appointments/${encodeURIComponent(id)}/video-session`, { method: 'POST', body: JSON.stringify(consent) }).then((r) => r.data);
export const checkVideoSession = (id, signal) => doctorRequest(`${ROOT}/appointments/${encodeURIComponent(id)}/video-session`, { signal }).then((r) => r.data);
const json = (method, body) => ({ method, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) });
export const loadAppointments = (query = "limit=100&offset=0", signal) => doctorRequest(`${ROOT}/appointments?${query}`, { signal }).then((r) => r.data);
export const loadAppointment = (id, signal) => doctorRequest(`${ROOT}/appointments/${encodeURIComponent(id)}`, { signal }).then((r) => r.data);
export const appointmentAction = (id, action, body = {}) => doctorRequest(`${ROOT}/appointments/${encodeURIComponent(id)}/${action}`, json(action === "meeting-link" ? "PATCH" : "POST", body)).then((r) => r.data);
export const loadSlots = (signal) => doctorRequest(`${ROOT}/slots`, { signal }).then((r) => r.data);
export const publishSlots = (slots) => doctorRequest(`${ROOT}/slots`, json("POST", { slots }));
export const cancelSlot = (id) => doctorRequest(`${ROOT}/slots/${encodeURIComponent(id)}`, json("DELETE"));
export const loadSchedule = (signal) => doctorRequest('/professional-schedule', {signal}).then(r => r.data);
export const saveSchedule = (settings) => doctorRequest('/professional-schedule',json('PUT',settings)).then(r => r.data);
export const publishSchedule = (range) => doctorRequest('/professional-schedule/publish',json('POST',range)).then(r => r.data);
export const publishException = (body) => doctorRequest('/professional-schedule/exceptions',json('POST',body)).then(r=>r.data);
export const addTimeBlock = (block) => doctorRequest('/professional-schedule/blocks',json('POST',block)).then(r => r.data);
export const removeTimeBlock = (id) => doctorRequest(`/professional-schedule/blocks/${encodeURIComponent(id)}`,json('DELETE')).then(r => r.data);
export const loadPractice = (signal) => doctorRequest(`${ROOT}/profile`, { signal }).then((r) => r.data);
export const savePractice = (body) => doctorRequest(`${ROOT}/profile`, json("PATCH", body)).then((r) => r.data);
export const loadRelationships = (signal) => doctorRequest("/doctor-care/relationships/doctor", { signal }).then((r) => r.data);
export const respondToRelationship = (id, action) => doctorRequest(`/doctor-care/relationships/${encodeURIComponent(id)}/${action}`, json("POST", {}));
export const loadPrescriptions = (page, signal) => doctorRequest(`/prescriptions/issued?page=${page}&limit=20`, { signal }).then((r) => r.data);
export const savePrescription = (body, id) => doctorRequest(id ? `/prescriptions/${encodeURIComponent(id)}` : "/prescriptions", json(id ? "PUT" : "POST", body)).then((r) => r.data);
export const issuePrescription = (id) => doctorRequest(`/prescriptions/${encodeURIComponent(id)}/issue`, json("POST", {}));
export const cancelPrescription = (id) => doctorRequest(`/prescriptions/${encodeURIComponent(id)}`, json("DELETE", {}));
export const loadNotifications = (page, signal) => doctorRequest(`/notifications?page=${page}&limit=20`, { signal }).then((r) => r.data);
export const markNotificationRead = (id) => doctorRequest(`/notifications/${encodeURIComponent(id)}/read`, json("PATCH", {}));
export const loadSessions = (signal) => doctorRequest("/auth/sessions", { signal }).then((r) => r.sessions);
export const revokeSession = (id) => doctorRequest(`/auth/sessions/${encodeURIComponent(id)}/revoke`, json("POST", {}));
export const loadMfa = (signal) => doctorRequest("/auth/mfa/status", { signal });
export const logoutEverywhere = () => doctorRequest("/auth/sessions/logout-all", json("POST", {}));
