import React,{useEffect,useState} from 'react';
import * as api from './doctorApi';
const names=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const defaultDays=names.map((name,day)=>({day,name,enabled:day>0&&day<6,start:'09:00',end:'17:00',breakStart:'12:00',breakEnd:'13:00',breakEnabled:true}));
const today=()=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Lagos',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const get=k=>parts.find(p=>p.type===k).value;return `${get('year')}-${get('month')}-${get('day')}`;};
const instant=(day,time,zone)=>new Date(`${day}T${time}:00${zone==='Africa/Lagos'?'+01:00':'Z'}`).toISOString();
export default function ProfessionalAvailability(){
  const [settings,setSettings]=useState({timezone:'Africa/Lagos',durationMinutes:30,bufferMinutes:5,weeklyHours:[]});
  const [days,setDays]=useState(defaultDays);const [blocks,setBlocks]=useState([]);const [slots,setSlots]=useState([]);
  const [range,setRange]=useState({from:today(),to:today()});const [block,setBlock]=useState({day:today(),start:'12:00',end:'13:00',reason:''});
  const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  async function reload(initial=false){if(initial)setLoading(true);try{const [s,a]=await Promise.all([api.loadSchedule(),api.loadSlots()]);setSettings(s.settings);setBlocks(s.blocks);setSlots(a.items.filter(v=>v.state!=='CANCELLED'));if(initial&&s.settings.weeklyHours.length)setDays(defaultDays.map(d=>{const r=s.settings.weeklyHours.find(r=>r.day===d.day);return r?{...d,...r,enabled:true,breakEnabled:!!r.breaks?.length,breakStart:r.breaks?.[0]?.start||'12:00',breakEnd:r.breaks?.[0]?.end||'13:00'}:{...d,enabled:false};}));}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{reload(true);},[]);
  async function act(work){if(busy)return;setBusy(true);setError('');setNotice('');try{const message=await work();setNotice(message);await reload();}catch(e){setError(e.message);}finally{setBusy(false);}}
  const changeDay=(day,patch)=>setDays(v=>v.map(d=>d.day===day?{...d,...patch}:d));
  function inputSettings(){const rules=days.filter(d=>d.enabled);if(!rules.length)throw new Error('Enable at least one working day.');if(rules.some(d=>d.end<=d.start||d.breakEnabled&&(d.breakEnd<=d.breakStart||d.breakStart<d.start||d.breakEnd>d.end)))throw new Error('Working hours and breaks must have a valid start/end, with breaks inside working hours.');return {...settings,weeklyHours:rules.map(d=>({day:d.day,start:d.start,end:d.end,consultationTypes:['VIRTUAL'],breaks:d.breakEnabled?[{start:d.breakStart,end:d.breakEnd}]:[]}))};}
  const display=v=>new Date(v).toLocaleString('en-NG',{timeZone:settings.timezone,dateStyle:'medium',timeStyle:'short'});
  return <div className="dl-page"><header className="dl-heading"><div><span className="dl-eyebrow">YOUR PRACTICE, CONNECTED</span><h1>Manage availability</h1><p>Set working hours, consultation length, breaks and time blocks. Times use {settings.timezone}.</p></div><button className="dp-btn dp-btn-outline" disabled={busy||loading} onClick={()=>reload()}>Refresh</button></header>
    {error&&<div className="dl-error" role="alert">{error}</div>}{notice&&<div className="dl-notice" role="status">{notice}</div>}
    {loading?<p role="status">Loading your saved schedule…</p>:<><div className="dl-columns"><section className="dp-panel"><h2>Standing weekly hours</h2><p className="dl-muted">Save a weekly pattern, then publish dates below. Saving does not change booked appointments.</p><fieldset disabled={busy} style={{border:0,padding:0}}>{[...days.slice(1),days[0]].map(d=><div className="dl-week-row" key={d.day}><label><input type="checkbox" checked={d.enabled} onChange={e=>changeDay(d.day,{enabled:e.target.checked})}/>{d.name}</label>{d.enabled?<><input aria-label={`${d.name} starts at`} type="time" value={d.start} onChange={e=>changeDay(d.day,{start:e.target.value})}/><input aria-label={`${d.name} ends at`} type="time" value={d.end} onChange={e=>changeDay(d.day,{end:e.target.value})}/><div className="dl-break"><label><input type="checkbox" checked={d.breakEnabled} onChange={e=>changeDay(d.day,{breakEnabled:e.target.checked})}/>Break</label>{d.breakEnabled&&<><input aria-label={`${d.name} break starts`} type="time" value={d.breakStart} onChange={e=>changeDay(d.day,{breakStart:e.target.value})}/><span>–</span><input aria-label={`${d.name} break ends`} type="time" value={d.breakEnd} onChange={e=>changeDay(d.day,{breakEnd:e.target.value})}/></>}</div></>:<span className="dl-muted">Unavailable</span>}</div>)}</fieldset>
      <form className="dl-form" onSubmit={e=>{e.preventDefault();act(async()=>{await api.saveSchedule(inputSettings());return 'Weekly hours saved. Publish your dates to make them bookable.';});}}><div className="dl-form-row"><label>Consultation duration<select value={settings.durationMinutes} onChange={e=>setSettings(v=>({...v,durationMinutes:Number(e.target.value)}))}>{[15,30,45,60].map(n=><option key={n} value={n}>{n} minutes</option>)}</select></label><label>Buffer between consultations<select value={settings.bufferMinutes} onChange={e=>setSettings(v=>({...v,bufferMinutes:Number(e.target.value)}))}>{[0,5,10,15].map(n=><option key={n} value={n}>{n} minutes</option>)}</select></label></div><label>Schedule timezone<select value={settings.timezone} onChange={e=>setSettings(v=>({...v,timezone:e.target.value}))}><option>Africa/Lagos</option><option>UTC</option></select></label><button disabled={busy} className="dp-btn dp-btn-primary">Save weekly hours</button></form></section>
      <div><section className="dp-panel"><h2>Publish your schedule</h2><p className="dl-muted">We split your working hours into appointments, skipping breaks and time blocks. Existing bookings remain unchanged.</p><form className="dl-form" onSubmit={e=>{e.preventDefault();act(async()=>{await api.saveSchedule(inputSettings());const r=await api.publishSchedule(range);return `${r.created} new slots published; ${r.existing} existing slots kept. Patients can book the open slots.`;});}}><div className="dl-form-row"><label>From<input type="date" required min={today()} value={range.from} onChange={e=>setRange(v=>({...v,from:e.target.value}))}/></label><label>Through<input type="date" required min={range.from} value={range.to} onChange={e=>setRange(v=>({...v,to:e.target.value}))}/></label></div><p className="dl-muted">Publish up to 31 days at once. Consultations are virtual.</p><button disabled={busy} className="dp-btn dp-btn-primary">Publish availability</button></form></section>
      <section className="dp-panel dl-space"><h2>One-off time blocks</h2><p className="dl-muted">Leave, conferences or date-specific exceptions. Blocks overlapping booked appointments are refused.</p><form className="dl-form" onSubmit={e=>{e.preventDefault();act(async()=>{await api.addTimeBlock({startsAt:instant(block.day,block.start,settings.timezone),endsAt:instant(block.day,block.end,settings.timezone),reason:block.reason});setBlock(v=>({...v,reason:''}));return 'Time blocked. Overlapping unbooked slots are no longer offered to patients.';});}}><label>Date<input required type="date" min={today()} value={block.day} onChange={e=>setBlock(v=>({...v,day:e.target.value}))}/></label><div className="dl-form-row"><label>Block starts<input type="time" required value={block.start} onChange={e=>setBlock(v=>({...v,start:e.target.value}))}/></label><label>Block ends<input type="time" required value={block.end} onChange={e=>setBlock(v=>({...v,end:e.target.value}))}/></label></div><label>Reason (private)<input required minLength={2} maxLength={200} value={block.reason} onChange={e=>setBlock(v=>({...v,reason:e.target.value}))}/></label><button disabled={busy} className="dp-btn dp-btn-primary">Add time block</button></form>{blocks.map(b=><div className="dl-slot" key={b.id}><div><strong>{b.reason}</strong><p>{display(b.startsAt)} – {display(b.endsAt)}</p></div><button disabled={busy} className="dp-btn dp-btn-outline" onClick={()=>act(async()=>{await api.removeTimeBlock(b.id);return 'Block removed. Publish your schedule again to restore available slots.';})}>Remove block</button></div>)}</section></div></div>
      <section className="dp-panel dl-space"><h2>Published slots · next 30 days</h2>{!slots.length?<p className="dl-muted">No published availability. Save your hours and publish dates above.</p>:slots.map(s=><div className="dl-slot" key={s.id}><div><strong>{display(s.startsAt)}</strong><p>Until {new Date(s.endsAt).toLocaleTimeString('en-NG',{timeZone:settings.timezone,hour:'2-digit',minute:'2-digit'})}</p></div><span>{s.state}</span>{s.state==='OPEN'&&<button disabled={busy} className="dp-btn dp-btn-outline" onClick={()=>act(async()=>{await api.cancelSlot(s.id);return 'Slot removed.';})}>Remove slot</button>}</div>)}</section></>}
  </div>;
}
