import React,{useEffect,useRef,useState} from 'react';
import {doctorRequest} from '../services/doctorAuth';
import {MealPlanTable,blankMeal} from '../../../shared-care/MealPlanTable';
const ROOT='/professional-care';
const request=(path,method='GET',body)=>doctorRequest(`${ROOT}${path}`,{method,...(body?{body:JSON.stringify(body)}:{})}).then(r=>r.data);
const blank=()=>({title:'',startsOn:new Date().toISOString().slice(0,10),endsOn:new Date().toISOString().slice(0,10),goals:'',preferences:'',allergies:'',restrictions:'',history:'',budget:'',instructions:'',activities:'',followUpOn:null,meals:[],targets:[]});
const TITLES={PSYCHOLOGIST:'Psychology care workspace',COUNSELLOR:'Counselling workspace',CAREGIVER:'Caregiver support plans',FITNESS_COACH:'Fitness plans',HEALTH_EDUCATOR:'Health education plans',NUTRITIONIST_DIETITIAN:'Nutrition support plans'};
export default function ProfessionalCareWorkspace(){
  const [workspace,setWorkspace]=useState(null),[selected,setSelected]=useState(null),[content,setContent]=useState(null),[patientId,setPatientId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[note,setNote]=useState(''),[followUp,setFollowUp]=useState(''),[templateName,setTemplateName]=useState('');
  const nutrition=workspace?.kind==='NUTRITION';
  const actionLock=useRef(false);
  async function load(){setWorkspace(await request('/workspace'));}
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  async function action(work){if(actionLock.current)return;actionLock.current=true;setBusy(true);setError('');setNotice('');try{await work();await load();}catch(e){setError(e.message);}finally{actionLock.current=false;setBusy(false);}}
  async function open(id){const plan=await request(`/plans/${id}`);setSelected(plan);setContent(plan.draft);setPatientId(plan.patientId);setNote('');setFollowUp('');}
  const update=(key,value)=>setContent(c=>({...c,[key]:value}));
  const input=(key,label,type='textarea')=><label key={key}>{label}{type==='textarea'?<textarea value={content[key]} maxLength={key==='history'||key==='activities'||key==='instructions'?4000:key==='budget'?300:2000} onChange={e=>update(key,e.target.value)}/>:<input type={type} value={content[key]||''} required={key!=='followUpOn'} onChange={e=>update(key,e.target.value||null)}/>}</label>;
  return <div className="dl-page care-workspace"><header className="dl-heading"><div><span className="dl-eyebrow">YOUR PRACTICE, CONNECTED</span><h1>{nutrition?'Dietician Table':TITLES[workspace?.professionType]||'Care workspace'}</h1><p>{nutrition?'Nutrition assessments, meal schedules and follow-up reviews. Meal plans are separate from medication prescriptions.':'Intake, patient goals, supportive activities and private session notes within your reviewed discipline.'}</p></div><button className="dp-btn dp-btn-outline" disabled={busy} onClick={()=>action(load)}>Refresh</button></header>
    {error&&<p className="care-alert care-error" role="alert">{error}</p>}{notice&&<p className="care-alert" role="status">{notice}</p>}
    {!workspace?<p role="status">Loading your authorised care workspace…</p>:<>
      <div className="care-toolbar"><button className="dp-btn dp-btn-primary" disabled={busy||!workspace.patients.length} onClick={()=>{setSelected(null);setContent(blank());setPatientId('');setNotice('');}}>New {nutrition?'nutrition':'support'} plan</button><span>{workspace.patients.length} patients with care-plan permission</span></div>
      {!workspace.patients.length&&<p className="care-alert">A patient must first have a confirmed appointment with you, then grant care-plan permission in their Dietician Table / Care Plans screen. This does not grant access to their general medical records.</p>}
      <section className="care-card"><h2>Your plans</h2>{!workspace.plans.length?<p>No plans yet.</p>:workspace.plans.map(plan=><button className="dl-appointment-card" disabled={busy} key={plan.id} onClick={()=>action(()=>open(plan.id))}><span>{plan.title} · {workspace.patients.find(p=>p.id===plan.patientId)?.name}</span><span>{plan.archivedAt?'Archived':plan.publishedVersion?`Published v${plan.publishedVersion} · draft revision ${plan.revision}`:'Draft'}</span></button>)}</section>
      {content&&<section className="care-card"><h2>{selected?'Review and revise plan':'New plan'}</h2><p>Draft edits remain private until you publish a new version. Previously published versions are preserved.</p>
        <fieldset disabled={busy||!!selected?.archivedAt} style={{border:0,padding:0,minWidth:0}}>
          <div className="care-grid"><label>Authorised patient<select required disabled={!!selected} value={patientId} onChange={e=>setPatientId(e.target.value)}><option value="">Select patient</option>{workspace.patients.map(p=><option key={p.id} value={p.id}>{p.name} · {p.reference}</option>)}</select></label>
            <label>Reusable template<select value="" onChange={e=>{const t=workspace.templates.find(t=>t.id===e.target.value);if(t)setContent({...t.content,title:content.title||t.name,startsOn:content.startsOn,endsOn:content.endsOn,history:'',allergies:'',preferences:'',restrictions:'',budget:''});}}><option value="">Apply a template (review for this patient)</option>{workspace.templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
            {input('title','Plan name','text')}{input('startsOn','Plan starts','date')}{input('endsOn','Plan ends','date')}{input('followUpOn','Next follow-up','date')}{input('goals','Patient goals')}{input('history','Relevant intake / history (not shown to patient)')}{input('preferences',nutrition?'Food preferences':'Patient preferences')}{input('allergies','Allergies / relevant precautions')}{input('restrictions','Restrictions / safety considerations')}{input('budget','Budget considerations')}{input('instructions','Patient instructions')}{!nutrition&&input('activities','Activities / care goals and agreed next steps')}
          </div>
          {nutrition&&<><MealPlanTable meals={content.meals} onChange={meals=>update('meals',meals)}/><h3>Nutritional targets</h3><p>No automatic nutritional values are invented. Add only reviewed, individualised targets with a reliable source. Food quantities are not calculated nutrients.</p>{content.targets.map((target,i)=><div className="care-grid" key={i}><label>Target<input value={target.name} maxLength={100} onChange={e=>update('targets',content.targets.map((t,n)=>n===i?{...t,name:e.target.value}:t))}/></label><label>Value and unit<input value={target.value} maxLength={100} onChange={e=>update('targets',content.targets.map((t,n)=>n===i?{...t,value:e.target.value}:t))}/></label><label>Source (HTTPS URL)<input type="url" value={target.source} onChange={e=>update('targets',content.targets.map((t,n)=>n===i?{...t,source:e.target.value}:t))}/></label><button type="button" onClick={()=>update('targets',content.targets.filter((_,n)=>n!==i))}>Remove target</button></div>)}<button type="button" disabled={content.targets.length>=20} onClick={()=>update('targets',[...content.targets,{name:'',value:'',source:''}])}>Add sourced target</button></>}
          <div className="care-toolbar"><button className="dp-btn dp-btn-primary" onClick={()=>action(async()=>{if(!patientId)throw new Error('Select a patient.');const saved=await request(selected?`/plans/${selected.id}`:'/plans',selected?'PUT':'POST',{...(selected?{revision:selected.revision}:{patientId}),content});await open(saved.id);setNotice('Draft saved. The patient still sees only the last published version.');})}>Save draft</button>
            {selected&&<><button className="dp-btn dp-btn-outline" onClick={()=>action(async()=>{if(JSON.stringify(content)!==JSON.stringify(selected.draft))throw new Error('Save your draft changes before publishing.');await request(`/plans/${selected.id}/publish`,'POST',{revision:selected.revision});await open(selected.id);setNotice('Plan published. The patient has been notified.');})}>Publish version</button><button className="dp-btn dp-btn-danger" onClick={()=>action(async()=>{if(!window.confirm('Archive this plan? The patient will retain their published copy, marked archived.'))return;await request(`/plans/${selected.id}/archive`,'POST',{revision:selected.revision});await open(selected.id);setNotice('Plan archived.');})}>Archive</button></>}
          </div>
          <div className="care-grid"><label>Template name<input value={templateName} maxLength={160} onChange={e=>setTemplateName(e.target.value)}/></label><button className="dp-btn dp-btn-outline" onClick={()=>action(async()=>{await request('/templates','POST',{name:templateName,content:{...content,history:'',allergies:'',preferences:'',restrictions:'',budget:''}});setTemplateName('');setNotice('Template saved. Personal intake fields were excluded; review the remaining text before reusing.');})}>Save reusable template</button></div>
        </fieldset>
        {selected&&<><h3>Published version history</h3>{selected.versions?.length?selected.versions.map(v=><details key={v.id}><summary>Version {v.number} · {new Date(v.publishedAt).toLocaleString()}</summary><p>{v.content.goals}</p><p>{v.content.instructions}</p>{nutrition&&<MealPlanTable meals={v.content.meals}/>}</details>):<p>No published versions.</p>}
          <h3>Patient feedback / progress</h3>{selected.feedback?.length?selected.feedback.map(f=><p key={f.id}>v{f.version} · {f.progress.replaceAll('_',' ')} · {new Date(f.createdAt).toLocaleString()}<br/>{f.message}</p>):<p>No patient feedback yet.</p>}
          <h3>Private session notes and follow-up</h3><p>Notes are append-only and visible only in your authorised professional workspace, not to the patient. Record corrections as a new note.</p>{selected.notes?.map(n=><p key={n.id}>{new Date(n.createdAt).toLocaleString()} · {n.text}{n.followUpAt&&<><br/>Follow-up: {new Date(n.followUpAt).toLocaleString()}</>}</p>)}
          {!selected.archivedAt&&<div className="care-grid"><label>Session / follow-up review<textarea maxLength={10000} value={note} onChange={e=>setNote(e.target.value)}/></label><label>Follow-up date/time<input type="datetime-local" value={followUp} onChange={e=>setFollowUp(e.target.value)}/></label><button disabled={busy||note.trim().length<2} className="dp-btn dp-btn-primary" onClick={()=>action(async()=>{await request(`/plans/${selected.id}/notes`,'POST',{text:note,...(followUp?{followUpAt:new Date(followUp).toISOString()}:{})});await open(selected.id);setNotice('Private review note saved.');})}>Save private note</button></div>}
        </>}
      </section>}
    </>}
  </div>;
}
