import React,{useEffect,useState} from 'react';
import * as api from './doctorApi';
const names=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const period=day=>({day,start:'09:00',end:'17:00',consultationTypes:['VIRTUAL'],breaks:[{start:'12:00',end:'13:00'}]});
const defaults=()=>[1,2,3,4,5].map(period);
const today=()=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Lagos',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const get=k=>parts.find(p=>p.type===k).value;return `${get('year')}-${get('month')}-${get('day')}`;};
const instant=(day,time,zone)=>new Date(`${day}T${time}:00${zone==='Africa/Lagos'?'+01:00':'Z'}`).toISOString();
function PeriodEditor({rule,label,onChange,onRemove}){
  const types=rule.consultationTypes;
  return <div className="dl-form care-card"><div className="dl-form-row"><label>Start<input aria-label={`${label} starts at`} type="time" value={rule.start} onChange={e=>onChange({...rule,start:e.target.value})}/></label><label>End<input aria-label={`${label} ends at`} type="time" value={rule.end} onChange={e=>onChange({...rule,end:e.target.value})}/></label></div>
    <div className="dl-checks">{[['VIRTUAL','Virtual'],['IN_PERSON','In person']].map(([type,text])=><label key={type}><input type="checkbox" checked={types.includes(type)} onChange={e=>onChange({...rule,consultationTypes:e.target.checked?[...types,type]:types.filter(t=>t!==type)})}/>{text}</label>)}</div>
    {rule.breaks.map((b,i)=><div className="dl-form-row" key={i}><label>Break starts<input type="time" aria-label={`${label} break ${i+1} starts`} value={b.start} onChange={e=>onChange({...rule,breaks:rule.breaks.map((v,n)=>n===i?{...v,start:e.target.value}:v)})}/></label><label>Break ends<input type="time" aria-label={`${label} break ${i+1} ends`} value={b.end} onChange={e=>onChange({...rule,breaks:rule.breaks.map((v,n)=>n===i?{...v,end:e.target.value}:v)})}/></label><button type="button" className="dp-btn dp-btn-outline dp-btn-sm" onClick={()=>onChange({...rule,breaks:rule.breaks.filter((_,n)=>n!==i)})}>Remove break</button></div>)}
    <div className="dl-actions"><button type="button" disabled={rule.breaks.length>=5} className="dp-btn dp-btn-outline dp-btn-sm" onClick={()=>onChange({...rule,breaks:[...rule.breaks,{start:rule.start,end:rule.end}]})}>Add break</button>{onRemove&&<button type="button" className="dp-btn dp-btn-outline dp-btn-sm" onClick={onRemove}>Remove period</button>}</div>
  </div>;
}
export default function ProfessionalAvailability(){
  const [settings,setSettings]=useState({timezone:'Africa/Lagos',durationMinutes:30,bufferMinutes:5,weeklyHours:defaults()});
  const [blocks,setBlocks]=useState([]),[slots,setSlots]=useState([]);
  const [range,setRange]=useState({from:today(),to:today()}),[block,setBlock]=useState({day:today(),start:'12:00',end:'13:00',reason:''});
  const [exception,setException]=useState({date:today(),hours:[period(new Date(`${today()}T00:00:00Z`).getUTCDay())]});
  const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  async function reload(initial=false){if(initial)setLoading(true);try{const [s,a]=await Promise.all([api.loadSchedule(),api.loadSlots()]);setSettings({...s.settings,weeklyHours:initial&&!s.settings.weeklyHours.length?defaults():s.settings.weeklyHours});setBlocks(s.blocks);setSlots(a.items.filter(v=>v.state!=='CANCELLED'));}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{reload(true);},[]);
  async function act(work){if(busy)return;setBusy(true);setError('');setNotice('');try{setNotice(await work());await reload();}catch(e){setError(e.message);}finally{setBusy(false);}}
  function inputSettings(){const rules=settings.weeklyHours;if(!rules.length)throw new Error('Enable at least one working day.');if(rules.some(d=>!d.consultationTypes.length||d.end<=d.start||d.breaks.some(b=>b.end<=b.start||b.start<d.start||b.end>d.end)))throw new Error('Working hours and breaks must have a valid start/end, with breaks inside working hours and a consultation type selected.');return settings;}
  const changeRule=(index,rule)=>setSettings(s=>({...s,weeklyHours:s.weeklyHours.map((v,n)=>n===index?rule:v)}));
  const display=v=>new Date(v).toLocaleString('en-NG',{timeZone:settings.timezone,dateStyle:'medium',timeStyle:'short'});
  return <div className="dl-page care-workspace"><header className="dl-heading"><div><span className="dl-eyebrow">YOUR PRACTICE, CONNECTED</span><h1>Manage availability</h1><p>Working hours, consultation lengths, breaks and date exceptions. Times use {settings.timezone}.</p></div><button className="dp-btn dp-btn-outline" disabled={busy||loading} onClick={()=>reload()}>Refresh</button></header>
    {error&&<div className="dl-error" role="alert">{error}</div>}{notice&&<div className="dl-notice" role="status">{notice}</div>}
    {loading?<p role="status">Loading your saved schedule…</p>:<><div className="dl-columns"><section className="dp-panel"><h2>Standing weekly hours</h2><p className="dl-muted">Save a weekly pattern, then publish dates. Saving does not change existing slots or booked appointments.</p>
      <fieldset disabled={busy} style={{border:0,padding:0,minWidth:0}}>{[1,2,3,4,5,6,0].map(day=>{const rules=settings.weeklyHours.map((r,index)=>({...r,index})).filter(r=>r.day===day);return <section key={day}><label><input type="checkbox" checked={!!rules.length} onChange={e=>setSettings(s=>({...s,weeklyHours:e.target.checked?[...s.weeklyHours,period(day)]:s.weeklyHours.filter(r=>r.day!==day)}))}/>{names[day]}</label>{rules.map(({index,...rule},n)=><PeriodEditor key={index} label={n===0?names[day]:`${names[day]} period ${n+1}`} rule={rule} onChange={v=>changeRule(index,v)} onRemove={()=>setSettings(s=>({...s,weeklyHours:s.weeklyHours.filter((_,i)=>i!==index)}))}/>)}{!!rules.length&&<button type="button" className="dp-btn dp-btn-outline dp-btn-sm" disabled={settings.weeklyHours.length>=14} onClick={()=>setSettings(s=>({...s,weeklyHours:[...s.weeklyHours,{day,start:'18:00',end:'20:00',breaks:[],consultationTypes:['VIRTUAL']}]}))}>Add {names[day]} period</button>}</section>;})}</fieldset>
      <form className="dl-form" onSubmit={e=>{e.preventDefault();act(async()=>{await api.saveSchedule(inputSettings());return 'Weekly hours saved. Publish your dates to make them bookable.';});}}><div className="dl-form-row"><label>Consultation duration (minutes)<input type="number" min="5" max="240" step="1" required value={settings.durationMinutes} onChange={e=>setSettings(s=>({...s,durationMinutes:Number(e.target.value)}))}/></label><label>Buffer between consultations (minutes)<input type="number" min="0" max="120" step="1" required value={settings.bufferMinutes} onChange={e=>setSettings(s=>({...s,bufferMinutes:Number(e.target.value)}))}/></label></div><label>Schedule timezone<select value={settings.timezone} onChange={e=>setSettings(s=>({...s,timezone:e.target.value}))}><option>Africa/Lagos</option><option>UTC</option></select></label><button disabled={busy} className="dp-btn dp-btn-primary">Save weekly hours</button></form>
    </section><div><section className="dp-panel"><h2>Publish your schedule</h2><p className="dl-muted">Appointments skip breaks and blocks. Existing bookings remain unchanged.</p><form className="dl-form" onSubmit={e=>{e.preventDefault();act(async()=>{await api.saveSchedule(inputSettings());const r=await api.publishSchedule(range);return `${r.created} new slots published; ${r.existing} existing slots kept. Patients can book the open slots.`;});}}><div className="dl-form-row"><label>From<input type="date" required min={today()} value={range.from} onChange={e=>setRange(v=>({...v,from:e.target.value}))}/></label><label>Through<input type="date" required min={range.from} value={range.to} onChange={e=>setRange(v=>({...v,to:e.target.value}))}/></label></div><p className="dl-muted">Publish up to 31 days at once. Choose virtual or in-person hours in your weekly pattern.</p><button disabled={busy} className="dp-btn dp-btn-primary">Publish availability</button></form></section>
      <section className="dp-panel dl-space"><h2>One-off time blocks</h2><p className="dl-muted">Leave, conferences or unavailable dates. Blocks overlapping booked appointments are refused.</p><form className="dl-form" onSubmit={e=>{e.preventDefault();act(async()=>{if(block.end<=block.start)throw new Error('Block end must follow start.');await api.addTimeBlock({startsAt:instant(block.day,block.start,settings.timezone),endsAt:instant(block.day,block.end,settings.timezone),reason:block.reason});setBlock(v=>({...v,reason:''}));return 'Time blocked. Overlapping unbooked slots are no longer offered to patients.';});}}><label>Date<input required type="date" min={today()} value={block.day} onChange={e=>setBlock(v=>({...v,day:e.target.value}))}/></label><div className="dl-form-row"><label>Block starts<input type="time" required value={block.start} onChange={e=>setBlock(v=>({...v,start:e.target.value}))}/></label><label>Block ends<input type="time" required value={block.end} onChange={e=>setBlock(v=>({...v,end:e.target.value}))}/></label></div><label>Reason (private)<input required minLength={2} maxLength={200} value={block.reason} onChange={e=>setBlock(v=>({...v,reason:e.target.value}))}/></label><button disabled={busy} className="dp-btn dp-btn-primary">Add time block</button></form>{blocks.map(b=><div className="dl-slot" key={b.id}><div><strong>{b.reason}</strong><p>{display(b.startsAt)} – {display(b.endsAt)}</p></div><button disabled={busy} className="dp-btn dp-btn-outline" onClick={()=>act(async()=>{await api.removeTimeBlock(b.id);return 'Block removed. Publish your schedule again to restore available slots.';})}>Remove block</button></div>)}</section>
      <section className="dp-panel dl-space"><h2>Date-specific extra hours</h2><p>Publish a special working period without changing your recurring pattern. It uses your saved duration, buffer and timezone. Remove any overlapping unbooked slots first; booked conflicts are refused.</p><form className="dl-form" onSubmit={e=>{e.preventDefault();act(async()=>{await api.saveSchedule(inputSettings());const r=await api.publishException(exception);return `${r.created} date-specific slots published; ${r.existing} existing slots kept.`;});}}><label>Exception date<input type="date" required min={today()} value={exception.date} onChange={e=>{const value=e.target.value;if(value)setException(v=>({...v,date:value,hours:v.hours.map(h=>({...h,day:new Date(`${value}T00:00:00Z`).getUTCDay()}))}));}}/></label><fieldset disabled={busy} style={{border:0,padding:0,minWidth:0}}><PeriodEditor rule={exception.hours[0]} label="Exception" onChange={rule=>setException(v=>({...v,hours:[rule]}))}/></fieldset><button className="dp-btn dp-btn-primary" disabled={busy}>Publish extra hours</button></form></section>
    </div></div><section className="dp-panel dl-space"><h2>Published slots · next 30 days</h2>{!slots.length?<p className="dl-muted">No published availability. Save your hours and publish dates above.</p>:slots.map(s=><div className="dl-slot" key={s.id}><div><strong>{display(s.startsAt)}</strong><p>Until {new Date(s.endsAt).toLocaleTimeString('en-NG',{timeZone:settings.timezone,hour:'2-digit',minute:'2-digit'})} · {s.consultationTypes?.join(' / ').replaceAll('_',' ')}</p></div><span>{s.state}</span>{s.state==='OPEN'&&<button disabled={busy} className="dp-btn dp-btn-outline" onClick={()=>act(async()=>{await api.cancelSlot(s.id);return 'Slot removed.';})}>Remove slot</button>}</div>)}</section></>}
  </div>;
}
