import { defineConfig, loadEnv } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import { sabiPwaOptions } from "../shared-portal/pwa/pwaOptions.ts";
import { fileURLToPath } from "node:url";

const repoRoot = fileURLToPath(new URL("../../../../", import.meta.url));
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, repoRoot, "");
  const preview = mode === "doctor-preview";
  const target = process.env.SABI_DEV_API_TARGET || env.SABI_DEV_API_TARGET;
  return {
    base: "/doctor-portal/",
    envDir: repoRoot,
    // Icons shared with the patient portal (generated by `npm run icons` at the repo root).
    publicDir: "../shared-portal/public",
    plugins: [
      react(),
      VitePWA(sabiPwaOptions({
        cacheId: "professional",
        name: "Sabi Health Professional Portal",
        shortName: "Sabi Practice",
        description: "Sabi Health workspace for appointments, availability and authorised patient care.",
        themeColor: "#0e7c66",
        backgroundColor: "#f6f7f2",
        nestedApps: [],
      })),
    ],
    resolve: { alias: { "design-system": fileURLToPath(new URL("./design-system/index.jsx", import.meta.url)) } },
    define: {
      "import.meta.env.VITE_SABI_IDENTITY_API_URL": JSON.stringify(preview ? "" : process.env.VITE_SABI_IDENTITY_API_URL || env.VITE_SABI_IDENTITY_API_URL || env.VITE_API_BASE_URL || "same-origin"),
    },
    server: { ...(target && !preview ? { proxy: { "/api": { target, changeOrigin: true } } } : {}) },
  };
});
