import React,{useEffect,useState} from 'react';
import {authorizedRequest} from '../../utils/sabiIdentity';
import {PageShell} from '../hospitals/hospitalShared';
import {MealPlanTable} from '../../../../shared-care/MealPlanTable';
import '../../styles/share.css';
const request=(path,method='GET',body)=>authorizedRequest(`/api/v1/professional-care${path}`,{method,...(body?{body}:{})}).then(r=>r.data);
export function DieticianTablePage({support=false}){
  const [plans,setPlans]=useState([]),[providers,setProviders]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[feedback,setFeedback]=useState({});
  async function load(){const [p,c]=await Promise.all([request('/patient/plans'),request('/patient/providers')]);setPlans(p);setProviders(c);}
  useEffect(()=>{load().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
  async function action(work){if(busy)return;setBusy(true);setError('');setNotice('');try{await work();await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <PageShell mainClassName="sabi-main"><div className="care-workspace"><header><h1>{support?'My Care Plans':'Dietician Table'}</h1><p>{support?'Support plans and goals agreed with your professional.':'Your published nutrition plans and meal schedules. These are not medication prescriptions.'}</p></header>
    {error&&<p role="alert" className="care-alert care-error">{error}</p>}{notice&&<p role="status" className="care-alert">{notice}</p>}{loading?<p role="status">Loading your plans…</p>:<>
      <section className="care-card"><h2>Care-plan permissions</h2><p>After a confirmed appointment, you can allow your professional to create plans and record intake and follow-up notes. This does not share your other medical records. Revoke permission at any time; previously published plans remain available to you.</p>{providers.length?providers.map(p=><div className="care-toolbar" key={p.id}><span>{p.name} · {p.specialty} · {p.active?'Permission granted':'Permission not granted'}</span><button disabled={busy} onClick={()=>action(async()=>{await request(`/patient/consents/${p.id}`,'PUT',{active:!p.active,consentVersion:'professional-care-v1'});setNotice(p.active?'Care-plan access revoked.':'Care-plan access granted.');})}>{p.active?'Revoke permission':'Allow care plans'}</button></div>):<p>No eligible professional appointments yet.</p>}</section>
      {plans.filter(p=>p.kind===(support?'SUPPORT':'NUTRITION')).length===0&&<section className="care-card"><h2>No published plans yet</h2><p>Plans appear here after your authorised professional publishes them. Their draft changes are never shown.</p></section>}
      {plans.filter(p=>p.kind===(support?'SUPPORT':'NUTRITION')).map(plan=><section className="care-card" key={plan.id}><h2>{plan.content.title}</h2><p>{plan.professional} · Version {plan.publishedVersion} · {plan.archivedAt?'Archived':'Published'}<br/>{plan.content.startsOn} – {plan.content.endsOn}</p><h3>Your goals</h3><p>{plan.content.goals}</p><p>{plan.content.instructions}</p>{plan.content.activities&&<p>{plan.content.activities}</p>}{plan.content.allergies&&<p>Allergies / precautions: {plan.content.allergies}</p>}{plan.content.restrictions&&<p>Restrictions: {plan.content.restrictions}</p>}{plan.content.preferences&&<p>Preferences: {plan.content.preferences}</p>}{plan.content.budget&&<p>Budget: {plan.content.budget}</p>}{!support&&<MealPlanTable meals={plan.content.meals}/>}{plan.content.targets.map((t,i)=><p key={i}>{t.name}: {t.value} · <a href={t.source} target="_blank" rel="noreferrer">Reviewed source</a></p>)}{plan.content.followUpOn&&<p>Next follow-up: {plan.content.followUpOn}</p>}
        <details><summary>Published updates</summary>{plan.versions.map(v=><p key={v.number}>Version {v.number} · {new Date(v.publishedAt).toLocaleString()}</p>)}</details>
        <h3>Your progress and feedback</h3>{plan.feedback.map(f=><p key={f.id}>v{f.version} · {f.progress.replaceAll('_',' ')}: {f.message}</p>)}
        {!plan.archivedAt&&<form className="care-grid" onSubmit={e=>{e.preventDefault();action(async()=>{await request(`/patient/plans/${plan.id}/feedback`,'POST',{version:plan.publishedVersion,message:feedback[plan.id]?.message||'',progress:feedback[plan.id]?.progress||'ON_TRACK'});setFeedback(f=>({...f,[plan.id]:{}}));setNotice('Your feedback was sent to your professional.');});}}><label>How is your plan going?<select value={feedback[plan.id]?.progress||'ON_TRACK'} onChange={e=>setFeedback(f=>({...f,[plan.id]:{...f[plan.id],progress:e.target.value}}))}><option value="ON_TRACK">On track</option><option value="NEEDS_HELP">Need help</option><option value="NOT_STARTED">Not started</option></select></label><label>Progress / questions<textarea required minLength={2} maxLength={2000} value={feedback[plan.id]?.message||''} onChange={e=>setFeedback(f=>({...f,[plan.id]:{...f[plan.id],message:e.target.value}}))}/></label><button disabled={busy}>Send feedback</button></form>}
      </section>)}
      <button disabled={busy} onClick={()=>action(load)}>Refresh plans</button>
    </>}
  </div></PageShell>;
}
