import { useEffect, useState } from "react";
import { CheckCircle2, FileText, WalletCards } from "lucide-react";
import { formatMoney } from "@/command-center/format";
import type { OrganizationApplication } from "@/registration/domain";
import { useCommercialOnboarding } from "./useCommercialOnboarding";

export function CommercialApplicantPanel({ application }: { application: OrganizationApplication }) {
  const opportunities = useCommercialOnboarding((state) => state.opportunities);
  const syncApprovedApplications = useCommercialOnboarding((state) => state.syncApprovedApplications);
  const acceptQuote = useCommercialOnboarding((state) => state.acceptQuote);
  const item = opportunities.find((entry) => entry.applicationId === application.id);
  const quote = item ? [...item.quotes].sort((a, b) => b.version - a.version)[0] : undefined;
  const [signerName, setSignerName] = useState("");
  const [message, setMessage] = useState("");
  useEffect(() => { if (application.status === "APPROVED") syncApprovedApplications(); }, [application.status, syncApprovedApplications]);
  if (application.status !== "APPROVED" || !item) return null;
  return <section className="mt-7 rounded-2xl border border-brand-200 bg-brand-50/60 p-5"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-brand-600 text-white"><WalletCards size={18}/></span><div><h2 className="font-display text-lg font-bold text-slate-900">Commercial activation</h2><p className="mt-1 text-sm leading-6 text-slate-600">Application approval is complete. Your commercial agreement remains separate from tenant provisioning.</p></div></div><div className="mt-4 rounded-xl bg-white p-4 ring-1 ring-brand-200"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Agreement status</p><p className="mt-1 font-display text-xl font-bold text-slate-900">{item.status.replaceAll("_", " ")}</p></div><span className="rounded-full bg-brand-100 px-2.5 py-1 text-[10px] font-bold text-brand-800">Payment {item.paymentStatus.replaceAll("_", " ")}</span></div>{quote && <div className="mt-4 border-t border-slate-100 pt-4"><div className="flex justify-between gap-4"><div><p className="font-mono text-xs font-bold text-slate-700">{quote.number}</p><p className="mt-1 text-xs text-slate-400">Valid until {new Date(quote.expiresAt).toLocaleDateString()}</p></div><b className="font-display text-xl text-slate-950">{formatMoney(quote.total, quote.currency)}</b></div><div className="mt-3 space-y-2">{quote.lineItems.map((line) => <div key={line.id} className="flex justify-between gap-4 text-xs"><span className="text-slate-500">{line.label}</span><span className="font-semibold">{formatMoney(line.amount, quote.currency)}</span></div>)}</div>{quote.status === "ISSUED" && <div className="mt-4 border-t border-slate-100 pt-4"><label className="block"><span className="label">Authorized signer’s full name</span><input className="input" value={signerName} onChange={(event) => setSignerName(event.target.value)} placeholder="Enter the person accepting this offer"/></label><button className="public-button-primary mt-3" onClick={() => { const result = acceptQuote(application.id, quote.id, signerName); setMessage(result.ok ? "Quote accepted. The Sabi team will confirm the activation pathway." : result.error); }}><FileText size={15}/>Accept quote</button><p className="mt-2 text-xs leading-5 text-slate-400">In production, acceptance will require a signed applicant session and server-generated audit evidence.</p></div>}{quote.status === "ACCEPTED" && <p className="mt-4 flex items-center gap-2 rounded-lg bg-emerald-50 p-3 text-sm font-semibold text-emerald-800"><CheckCircle2 size={16}/>Accepted by {quote.acceptedByName}</p>}</div>}</div>{!quote && <p className="mt-4 rounded-xl bg-white p-4 text-sm text-slate-500 ring-1 ring-brand-200">The commercial team is preparing your versioned quotation.</p>}{message && <p role="status" className="mt-3 text-sm font-semibold text-brand-800">{message}</p>}</section>;
}
