import { useEffect, useState, type ReactNode } from "react";
import { Navigate } from "react-router-dom";
import {
  ArrowRight, BadgeCheck, Building2, Check, CheckCircle2, CircleAlert, Clock3,
  HeartPulse, LockKeyhole, Plus, Save, ShieldCheck, Trash2,
} from "lucide-react";
import { useCommandCenter } from "@/command-center/useCommandCenter";
import { PRODUCTS } from "@/platform/entitlements";
import { useAuth } from "@/store/useAuth";
import { useTenant } from "@/store/useTenant";
import type { SetupActor, TenantSetupConfiguration, TenantSetupRecord, TenantSetupStepKey } from "./domain";
import { useTenantSetup } from "./useTenantSetup";

const SERVICE_OPTIONS = ["Outpatient consultation", "Emergency", "Inpatient care", "Laboratory", "Pharmacy", "Radiology", "Maternity", "Theatre", "Immunization", "Community outreach"];

export default function TenantFirstRunSetup() {
  const tenant = useTenant((state) => state.tenant);
  const identity = useAuth((state) => state.identity);
  const membership = useAuth((state) => state.activeMembership);
  const record = useTenantSetup((state) => state.records.find((item) => item.organizationId === tenant.id));
  const setup = useTenantSetup();
  const command = useCommandCenter();
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { document.title = `Setup Sabi OS — ${tenant.name}`; }, [tenant.name]);
  if (!identity || !membership || membership.organizationId !== tenant.id) return <Navigate to="/login" replace/>;
  if (!record || record.status === "LIVE") return <Navigate to="/workspace" replace/>;
  const actor: SetupActor = { id: identity.id, name: identity.name, role: membership.role };
  const active = record.steps.find((item) => item.key === record.activeStep) ?? record.steps[0];
  const organization = command.organizations.find((item) => item.id === tenant.id);
  const subscription = command.subscriptions.find((item) => item.organizationId === tenant.id);
  const pkg = command.packages.find((item) => item.id === subscription?.packageId);
  const completed = record.steps.filter((item) => item.status === "COMPLETED").length;
  const progress = Math.round((completed / record.steps.length) * 100);
  const editable = !["READY_FOR_REVIEW", "APPROVED"].includes(record.status);

  const update = <K extends keyof TenantSetupConfiguration>(key: K, value: TenantSetupConfiguration[K]) => {
    const result = setup.updateConfiguration(record.organizationId, key, value, actor);
    if (!result.ok) setError(result.error); else { setError(""); setMessage("Saved just now"); }
  };
  const next = () => {
    setError(""); setMessage("");
    const result = active.key === "GO_LIVE_REVIEW" ? setup.submitForReview(record.organizationId, actor) : setup.completeStep(record.organizationId, active.key, actor);
    if (!result.ok) return setError(result.error);
    const index = record.steps.findIndex((item) => item.key === active.key);
    const following = record.steps[index + 1];
    if (following) setup.setActiveStep(record.organizationId, following.key);
    setMessage(active.key === "GO_LIVE_REVIEW" ? "Go-live readiness submitted to the Sabi implementation team." : "Step completed and saved.");
  };

  return <main className="min-h-screen bg-[#f4faf6] text-slate-900">
    <header className="border-b border-slate-200 bg-white/95 px-5 py-3 backdrop-blur"><div className="mx-auto flex max-w-[1440px] items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-slate-950 text-emerald-300"><HeartPulse size={20}/></span><div><b className="font-display">Sabi OS setup</b><p className="text-xs text-slate-400">{tenant.name} · {tenant.tenantId}</p></div></div><div className="hidden items-center gap-2 text-xs text-slate-500 sm:flex"><Save size={14} className="text-emerald-600"/>Configuration is saved to the tenant setup record</div></div></header>
    <div className="mx-auto grid max-w-[1440px] lg:grid-cols-[300px_minmax(0,1fr)]">
      <aside className="border-b border-slate-200 bg-white p-5 lg:min-h-[calc(100vh-65px)] lg:border-b-0 lg:border-r"><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-emerald-700">Welcome to Sabi OS</p><h1 className="mt-2 font-display text-2xl font-extrabold tracking-tight">Prepare your hospital.</h1><p className="mt-2 text-sm leading-6 text-slate-500">Only the setup experience is available until readiness is approved.</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500 transition-all" style={{ width: `${progress}%` }}/></div><div className="mt-2 flex justify-between text-xs"><b>{progress}% complete</b><span className="text-slate-400">{completed}/{record.steps.length}</span></div><nav className="mt-6 grid grid-cols-2 gap-1 sm:grid-cols-3 lg:grid-cols-1">{record.steps.map((item, index) => <button key={item.key} onClick={() => setup.setActiveStep(record.organizationId, item.key)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-left text-xs font-semibold transition ${active.key === item.key ? "bg-slate-950 text-white" : "text-slate-600 hover:bg-slate-50"}`}><span className={`grid h-6 w-6 shrink-0 place-items-center rounded-full ${item.status === "COMPLETED" ? "bg-emerald-100 text-emerald-700" : item.status === "CHANGES_REQUESTED" ? "bg-red-100 text-red-700" : active.key === item.key ? "bg-white/10" : "bg-slate-100 text-slate-500"}`}>{item.status === "COMPLETED" ? <Check size={13}/> : index + 1}</span><span className="truncate">{item.label}</span></button>)}</nav></aside>
      <section className="p-5 sm:p-8 lg:p-10"><div className="mx-auto max-w-[880px]"><div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">{active.moduleKey ? `Required by ${active.moduleKey}` : "Tenant configuration"}</p><h2 className="mt-2 font-display text-3xl font-extrabold tracking-tight">{active.label}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{active.description}</p></div><StatusBadge status={record.status}/></div>
        {record.reviewNotes && record.status === "CHANGES_REQUESTED" && <div className="mb-5 flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><CircleAlert size={18} className="shrink-0"/><div><b>Changes requested</b><p className="mt-1">{record.reviewNotes}</p></div></div>}
        {message && <p role="status" className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</p>}
        {error && <p role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}
        <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><StepContent record={record} step={active.key} update={update} organizationName={organization?.legalName ?? tenant.name} packageName={pkg?.name ?? "Subscription"}/></div>
        <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 text-xs text-slate-400"><LockKeyhole size={14}/>Clinical modules remain locked until activation.</div>{editable && !["ORGANIZATION", "SUBSCRIPTION"].includes(active.key) && <button onClick={next} className="public-button-primary">{active.key === "GO_LIVE_REVIEW" ? <ShieldCheck size={16}/> : <CheckCircle2 size={16}/>} {active.key === "GO_LIVE_REVIEW" ? "Submit for review" : "Complete and continue"}<ArrowRight size={15}/></button>}</div>
        {["READY_FOR_REVIEW", "APPROVED"].includes(record.status) && <div className="mt-5 rounded-2xl bg-slate-950 p-5 text-white"><div className="flex gap-3"><Clock3 className="shrink-0 text-emerald-300"/><div><b>{record.status === "APPROVED" ? "Readiness approved" : "Readiness review in progress"}</b><p className="mt-1 text-sm leading-6 text-white/55">{record.status === "APPROVED" ? "The Sabi implementation team can now activate the workspace. Clinical access remains locked until that activation is recorded." : "Your configuration is read-only while the implementation team performs the final checks."}</p></div></div></div>}
      </div></section>
    </div>
  </main>;
}

function StepContent({ record, step, update, organizationName, packageName }: { record: TenantSetupRecord; step: TenantSetupStepKey; update: <K extends keyof TenantSetupConfiguration>(key: K, value: TenantSetupConfiguration[K]) => void; organizationName: string; packageName: string }) {
  const c = record.configuration;
  if (step === "ORGANIZATION") return <ReadOnlySummary icon={<Building2/>} title={organizationName} rows={[["Tenant ID", record.organizationId], ["Facility code", c.organization.facilityCode], ["Timezone", c.organization.timezone], ["Locale", c.organization.locale]]}/>;
  if (step === "SUBSCRIPTION") return <ReadOnlySummary icon={<BadgeCheck/>} title={packageName} rows={[["Products", record.productIds.map((key) => PRODUCTS[key as keyof typeof PRODUCTS]?.label ?? key).join(", ")], ["Licensed modules", String(record.moduleIds.length)], ["Configuration", "Module-aware setup steps generated"]]}/>;
  if (step === "DEPARTMENTS") return <Departments value={c.departments} onChange={(departments) => update("departments", departments)}/>;
  if (step === "SERVICES") return <Choices title="Facility services" options={SERVICE_OPTIONS} selected={c.services} onChange={(services) => update("services", services)}/>;
  if (step === "STAFF") return <div className="grid gap-5 sm:grid-cols-2"><Field label="How will staff be added?"><select className="input" value={c.staff.invitationMode} onChange={(event) => update("staff", { ...c.staff, invitationMode: event.target.value as typeof c.staff.invitationMode })}><option value="INDIVIDUAL">Individual invitations</option><option value="CSV">CSV import</option><option value="LATER">After setup</option></select></Field><Field label="Expected staff users"><input className="input" type="number" min={1} value={c.staff.expectedUsers} onChange={(event) => update("staff", { ...c.staff, expectedUsers: Math.max(1, Number(event.target.value)) })}/></Field><SafetyNote>Only staff counts and an onboarding method are stored here. Staff identity data is handled through Sabi ID invitations.</SafetyNote></div>;
  if (step === "PATIENT_IMPORT") return <RadioChoices value={c.patientImport.approach} options={[["NO_EXISTING_RECORDS", "Start without existing patient records"], ["TEMPLATE_READY", "Prepare the Sabi migration template"], ["ASSISTED_MIGRATION", "Request assisted migration"], ["LATER", "Decide after setup"]]} onChange={(approach) => update("patientImport", { approach: approach as typeof c.patientImport.approach })}><SafetyNote>No patient names, identifiers or clinical data are stored in this setup record.</SafetyNote></RadioChoices>;
  if (step === "BILLING") return <div className="grid gap-5 sm:grid-cols-2"><Field label="Operating currency"><input className="input" value={c.billing.currency} readOnly/></Field><Field label="Receipt prefix"><input className="input" maxLength={10} value={c.billing.receiptPrefix} onChange={(event) => update("billing", { ...c.billing, receiptPrefix: event.target.value.toUpperCase().replace(/[^A-Z0-9-]/g, "") })}/></Field><Field label="Tax setup"><select className="input" value={c.billing.taxMode} onChange={(event) => update("billing", { ...c.billing, taxMode: event.target.value as typeof c.billing.taxMode })}><option value="CONFIGURE_LATER">Configure with finance team later</option><option value="STANDARD">Use standard configured taxes</option><option value="NO_TAX">No tax at launch</option></select></Field></div>;
  if (step === "PHARMACY") return <div className="space-y-5"><Field label="Default stock rotation"><select className="input" value={c.pharmacy.stockMethod} onChange={(event) => update("pharmacy", { ...c.pharmacy, stockMethod: event.target.value as typeof c.pharmacy.stockMethod })}><option value="FEFO">FEFO — earliest expiry first</option><option value="FIFO">FIFO — oldest stock first</option></select></Field><CheckField checked={c.pharmacy.prescriptionApproval} onChange={(value) => update("pharmacy", { ...c.pharmacy, prescriptionApproval: value })}>Require an authorized prescription before dispensing</CheckField></div>;
  if (step === "LABORATORY") return <div className="space-y-5"><Field label="Default result approver"><select className="input" value={c.laboratory.resultApprovalRole} onChange={(event) => update("laboratory", { ...c.laboratory, resultApprovalRole: event.target.value as typeof c.laboratory.resultApprovalRole })}><option>Lab Scientist</option><option>Pathologist</option><option>Authorized Reviewer</option></select></Field><CheckField checked={c.laboratory.requireSecondReview} onChange={(value) => update("laboratory", { ...c.laboratory, requireSecondReview: value })}>Require a second review for critical results</CheckField></div>;
  if (step === "BRANDING") return <div className="grid gap-5 sm:grid-cols-2"><Field label="Organization display name"><input className="input" value={c.branding.organizationDisplayName} onChange={(event) => update("branding", { ...c.branding, organizationDisplayName: event.target.value })}/></Field><Field label="Product display name"><input className="input" value={c.branding.productDisplayName} onChange={(event) => update("branding", { ...c.branding, productDisplayName: event.target.value })}/></Field><Field label="Primary color"><div className="flex gap-2"><input aria-label="Primary color picker" className="h-11 w-14 rounded-lg border border-slate-200 p-1" type="color" value={c.branding.primaryColor} onChange={(event) => update("branding", { ...c.branding, primaryColor: event.target.value })}/><input className="input" value={c.branding.primaryColor} onChange={(event) => update("branding", { ...c.branding, primaryColor: event.target.value })}/></div></Field><div className="rounded-xl p-4 text-white" style={{ backgroundColor: c.branding.primaryColor }}><p className="text-xs opacity-70">Live preview</p><b className="mt-2 block">{c.branding.organizationDisplayName || "Organization"}</b><span className="text-xs">{c.branding.productDisplayName || "Sabi OS"}</span></div></div>;
  if (step === "TRAINING") return <div className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><Field label="Training owner"><input className="input" value={c.training.ownerName} onChange={(event) => update("training", { ...c.training, ownerName: event.target.value })}/></Field><Field label="Training pathway"><select className="input" value={c.training.pathway} onChange={(event) => update("training", { ...c.training, pathway: event.target.value as typeof c.training.pathway })}><option value="SELF_GUIDED">Self-guided</option><option value="REMOTE">Remote sessions</option><option value="ONSITE">On-site rollout</option></select></Field></div><CheckField checked={c.training.acknowledged} onChange={(value) => update("training", { ...c.training, acknowledged: value })}>I understand that staff permissions, workflow practice and launch support must be confirmed before clinical use.</CheckField></div>;
  return <div><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 shrink-0 text-emerald-600"/><div><h3 className="font-display text-xl font-bold">Review your launch configuration</h3><p className="mt-2 text-sm leading-6 text-slate-500">Submitting makes this record read-only and sends it to the Sabi implementation team. Submission does not activate clinical access.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><Summary label="Departments" value={String(c.departments.length)}/><Summary label="Services" value={String(c.services.length)}/><Summary label="Expected users" value={String(c.staff.expectedUsers)}/><Summary label="Licensed modules" value={String(record.moduleIds.length)}/><Summary label="Training" value={c.training.pathway.replaceAll("_", " ")}/><Summary label="Patient migration" value={c.patientImport.approach.replaceAll("_", " ")}/></div></div>;
}

function Departments({ value, onChange }: { value: TenantSetupConfiguration["departments"]; onChange: (value: TenantSetupConfiguration["departments"]) => void }) { const [name, setName] = useState(""); const add = () => { const clean = name.trim(); if (!clean) return; onChange([...value, { id: `dept_${Date.now().toString(36)}`, name: clean, code: clean.slice(0, 3).toUpperCase() }]); setName(""); }; return <div><div className="flex gap-2"><input className="input flex-1" value={name} onChange={(event) => setName(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); add(); } }} placeholder="e.g. Nursing"/><button type="button" onClick={add} className="public-button-secondary"><Plus size={15}/>Add</button></div><div className="mt-5 space-y-2">{value.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-emerald-50 text-xs font-bold text-emerald-700">{item.code}</span><b className="flex-1 text-sm">{item.name}</b><button aria-label={`Remove ${item.name}`} onClick={() => onChange(value.filter((entry) => entry.id !== item.id))} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={15}/></button></div>)}{value.length === 0 && <p className="rounded-xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-400">Add the departments that must exist on launch.</p>}</div></div>; }
function Choices({ title, options, selected, onChange }: { title: string; options: string[]; selected: string[]; onChange: (values: string[]) => void }) { return <div><p className="mb-3 text-xs font-bold uppercase tracking-widest text-slate-400">{title}</p><div className="grid gap-2 sm:grid-cols-2">{options.map((option) => <label key={option} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm font-semibold ${selected.includes(option) ? "border-emerald-300 bg-emerald-50" : "border-slate-200"}`}><input type="checkbox" checked={selected.includes(option)} onChange={() => onChange(selected.includes(option) ? selected.filter((item) => item !== option) : [...selected, option])} className="h-4 w-4 accent-emerald-600"/>{option}</label>)}</div></div>; }
function RadioChoices({ value, options, onChange, children }: { value: string; options: [string, string][]; onChange: (value: string) => void; children?: ReactNode }) { return <div className="space-y-3">{options.map(([key, label]) => <label key={key} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-4 text-sm font-semibold ${value === key ? "border-emerald-300 bg-emerald-50" : "border-slate-200"}`}><input type="radio" checked={value === key} onChange={() => onChange(key)} className="accent-emerald-600"/>{label}</label>)}{children}</div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block"><span className="label">{label}</span>{children}</label>; }
function CheckField({ checked, onChange, children }: { checked: boolean; onChange: (value: boolean) => void; children: ReactNode }) { return <label className="flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 p-4 text-sm leading-6 text-slate-600"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="mt-1 h-4 w-4 shrink-0 accent-emerald-600"/>{children}</label>; }
function SafetyNote({ children }: { children: ReactNode }) { return <div className="sm:col-span-2 flex gap-3 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-500"><LockKeyhole size={15} className="shrink-0 text-slate-400"/>{children}</div>; }
function ReadOnlySummary({ icon, title, rows }: { icon: ReactNode; title: string; rows: [string, string][] }) { return <div><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-emerald-700">{icon}</span><div><p className="text-xs text-slate-400">Verified provisioning snapshot</p><h3 className="font-display text-lg font-bold">{title}</h3></div></div><div className="mt-6 divide-y divide-slate-100">{rows.map(([label, value]) => <div key={label} className="flex items-start justify-between gap-5 py-3 text-sm"><span className="text-slate-400">{label}</span><b className="text-right">{value}</b></div>)}</div></div>; }
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">{label}</p><b className="mt-1 block text-sm text-slate-800">{value}</b></div>; }
function StatusBadge({ status }: { status: string }) { const label = status.replaceAll("_", " "); return <span className="rounded-full bg-slate-950 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-white">{label}</span>; }
